from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .context import build_context
from .constants import AUDIT_DEFAULT_REPORT
from .core_validators import check_forbidden_root_wrappers, check_prompt_file_extensions, check_prompt_surface_manifest, check_pycache, check_required_files, check_workflow_config
from .design_system_validators import check_design_system
from .design_system_governance_validators import check_design_governance
from .design_system_surface_validators import check_design_surface
from .helpers import iter_linkable_docs, iter_markdown_docs, write_if_changed
from .link_validators import check_markdown_links
from .metadata_validators import check_metadata
from .wave_validators import (
    check_closed_wave_requirements,
    check_cross_artifact_consistency,
    check_prepare_council_verdict,
    _check_agent_category_metadata,
    _check_agent_role_metadata,
    check_journal_docs,
    check_migration_edges,
    check_persona_docs,
    check_plan_filenames,
    check_wave_docs,
    check_wave_roots,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Wave framework docs lint")
    parser.add_argument(
        "--write-migration-audit",
        action="store_true",
        help="Write a stable migration-audit report for warnings/info using write-if-changed semantics",
    )
    parser.add_argument(
        "--migration-audit-path",
        default=AUDIT_DEFAULT_REPORT,
        help="Project-root-relative output path for the optional migration audit report",
    )
    return parser.parse_args()


def _render_audit_report(warnings: list[str], infos: list[str]) -> str:
    lines = [
        "# Wave Migration Audit",
        "",
        "This report is generated by `.wavefoundry/framework/scripts/docs_lint.py`.",
        "It is report-first and does not imply metadata normalization.",
        "",
        "## Warnings",
        "",
    ]
    if warnings:
        lines.extend(f"- {warning}" for warning in warnings)
    else:
        lines.append("- none")
    lines.extend(["", "## Info", ""])
    if infos:
        lines.extend(f"- {info}" for info in infos)
    else:
        lines.append("- none")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    context = build_context()
    root = context.root
    failures: list[str] = []
    warnings: list[str] = []
    infos: list[str] = []

    if not context.docs_root.exists():
        print("docs/: missing repository docs root", file=sys.stderr)
        return 1

    failures.extend(check_required_files(root))
    failures.extend(check_forbidden_root_wrappers(root))
    failures.extend(check_prompt_file_extensions(root))
    failures.extend(check_pycache(root))
    failures.extend(check_wave_roots(root))
    failures.extend(check_workflow_config(root))
    failures.extend(check_prompt_surface_manifest(root))
    failures.extend(check_wave_docs(root))
    failures.extend(check_closed_wave_requirements(root))
    failures.extend(check_plan_filenames(root))
    failures.extend(_check_agent_role_metadata(root))
    failures.extend(_check_agent_category_metadata(root))
    failures.extend(check_journal_docs(root))
    failures.extend(check_persona_docs(root))
    failures.extend(check_cross_artifact_consistency(root))
    warnings.extend(check_migration_edges(root))
    council_errors, council_warnings = check_prepare_council_verdict(root)
    failures.extend(council_errors)
    warnings.extend(council_warnings)
    ds_failures, ds_warnings = check_design_system(root)
    failures.extend(ds_failures)
    warnings.extend(ds_warnings)
    gov_failures, gov_warnings = check_design_governance(root)
    failures.extend(gov_failures)
    warnings.extend(gov_warnings)
    surface_failures, surface_warnings = check_design_surface(root)
    failures.extend(surface_failures)
    warnings.extend(surface_warnings)

    for path in iter_markdown_docs(root):
        failures.extend(check_metadata(root, path))

    for path in iter_linkable_docs(root):
        failures.extend(check_markdown_links(root, path))

    if failures:
        for failure in failures:
            print(f"ERROR: {failure}", file=sys.stderr)
        for warning in warnings:
            print(f"WARNING: {warning}", file=sys.stderr)
        return 1

    for warning in warnings:
        print(f"WARNING: {warning}", file=sys.stderr)
    for info in infos:
        print(f"INFO: {info}", file=sys.stderr)

    if args.write_migration_audit:
        report_path = root / Path(args.migration_audit_path)
        changed = write_if_changed(report_path, _render_audit_report(warnings, infos))
        print(
            f"migration-audit: {'updated' if changed else 'unchanged'} {report_path.relative_to(root)}",
            file=sys.stderr,
        )

    print("docs-lint: ok")
    return 0
