#!/usr/bin/env python3
"""Build a semver distribution zip of Wavefoundry's canonical framework tree.

Produces wavefoundry-MAJOR.MINOR.PATCH.<build>.zip in ~/.wavefoundry/dist/
(or a specified output directory), where <build> is the rightmost 4 characters
of the current Crockford lifecycle prefix generated by lifecycle_id.py --prefix-only.

Before building the archive, writes ``framework/VERSION`` to
``MAJOR.MINOR.PATCH+<build>`` and stamps ``framework_revision`` in
prompt-surface-manifest.json to the same value.

Usage:
    python3 build_pack.py --version MAJOR.MINOR.PATCH [--output <dir>]
"""

import argparse
import datetime
import importlib.util
import os
import re
import subprocess
import sys
import zipfile
from pathlib import Path
from typing import Optional


# Patterns excluded from the zip.
EXCLUDED_NAMES = {".DS_Store"}
EXCLUDED_DIRS = {"__pycache__", ".pytest_cache", ".wavefoundry"}
# Excluded path suffix relative to the framework root (forward-slash separated).
# Tests and the test runner are development-only artifacts; downstream repos that
# vendor the pack have no use for them and seeds must not instruct them to run tests.
EXCLUDED_REL_PATHS = {"scripts/tests/tmp", "scripts/tests", "scripts/run_tests.py", "scripts/benchmarks", "test-cache.json"}

FRAMEWORK_REL = ".wavefoundry/framework"
ZIP_PREFIX = "wavefoundry-"
# wavefoundry-MAJOR.MINOR.PATCH.<build>.zip
_ZIP_NAME_RE = re.compile(r"^wavefoundry-(\d+\.\d+\.\d+)\.([A-Za-z0-9]+)\.zip$")
_LEGACY_ZIP_NAME_RE = re.compile(r"^wavefoundry-(\d{4}-\d{2}-\d{2})([a-z])\.zip$")
_DEFAULT_DIST_DIR = Path("~/.wavefoundry/dist")
_BRIDGE_VERSION = "0.9.0"


def find_repo_root(start: Path) -> Path:
    """Walk up from start until we find the repo root (contains AGENTS.md)."""
    current = start.resolve()
    while current != current.parent:
        if (current / "AGENTS.md").exists():
            return current
        current = current.parent
    raise RuntimeError(f"Could not locate repository root from {start}")


def _get_build_prefix() -> str:
    """Return the current Crockford lifecycle prefix from lifecycle_id.py --prefix-only."""
    script_dir = Path(__file__).resolve().parent
    result = subprocess.run(
        [sys.executable, str(script_dir / "lifecycle_id.py"), "--prefix-only"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _build_suffix(prefix: str) -> str:
    """Return the packaged 4-character build suffix derived from a lifecycle prefix."""
    return prefix[-4:] if len(prefix) > 4 else prefix


def should_exclude(rel_path: str, name: str) -> bool:
    """Return True if this file or directory should be excluded from the zip."""
    if name in EXCLUDED_NAMES:
        return True
    # rel_path uses forward slashes relative to the framework root.
    for excl in EXCLUDED_DIRS:
        parts = rel_path.split("/")
        if excl in parts:
            return True
    for excl_rel in EXCLUDED_REL_PATHS:
        if rel_path == excl_rel or rel_path.startswith(excl_rel + "/"):
            return True
    if name.endswith(".pyc"):
        return True
    return False


def collect_files(framework_dir: Path) -> list[tuple[Path, str]]:
    """Return [(abs_path, zip_arcname)] for every file under framework_dir."""
    entries: list[tuple[Path, str]] = []
    for dirpath, dirnames, filenames in os.walk(framework_dir):
        dirpath = Path(dirpath)
        # Compute path relative to framework_dir using forward slashes.
        rel_dir = dirpath.relative_to(framework_dir).as_posix()
        rel_dir = "" if rel_dir == "." else rel_dir

        # Filter out excluded dirs in-place so os.walk skips them.
        dirnames[:] = [
            d for d in dirnames
            if not should_exclude(
                (rel_dir + "/" + d).lstrip("/"), d
            )
        ]

        for filename in filenames:
            rel_file = (rel_dir + "/" + filename).lstrip("/")
            if should_exclude(rel_file, filename):
                continue
            abs_path = dirpath / filename
            # arcname preserves the full path from repo root so that
            # `unzip -o zip -d <repo-root>` restores the correct layout.
            arcname = FRAMEWORK_REL + ("/" + rel_file if rel_file else "")
            entries.append((abs_path, arcname))
    return entries


def _framework_index_source_files(framework_dir: Path) -> list[Path]:
    """Return the pack-shipped framework source files used to build the index."""
    source_files: list[Path] = []
    for abs_path, arcname in collect_files(framework_dir):
        if not arcname.startswith(FRAMEWORK_REL + "/"):
            continue
        rel_path = arcname[len(FRAMEWORK_REL) + 1 :]
        if rel_path == "VERSION":
            continue
        if rel_path == "MANIFEST" or rel_path.startswith("MANIFEST.pre-"):
            continue
        if rel_path == "index" or rel_path.startswith("index/"):
            continue
        source_files.append(abs_path)
    return source_files


def write_manifest(framework_dir: Path, entries: list[tuple[Path, str]]) -> Path:
    """Write MANIFEST listing all packed paths (relative to framework root).

    The manifest is written to disk so it can be saved before the next upgrade
    and used to prune files that were pack-delivered in the old version but
    absent from the new one.  MANIFEST always lists itself.
    """
    prefix = FRAMEWORK_REL + "/"
    rel_paths = sorted({
        *(arcname[len(prefix):] for _, arcname in entries if arcname.startswith(prefix)),
        "MANIFEST",
    })
    manifest_path = framework_dir / "MANIFEST"
    manifest_path.write_text("\n".join(rel_paths) + "\n", encoding="utf-8")
    return manifest_path


def write_pack_version(framework_dir: Path, version: str, build_prefix: str) -> None:
    """Stamp VERSION with MAJOR.MINOR.PATCH+<build_prefix> so the archive is traceable."""
    version_path = framework_dir / "VERSION"
    version_path.write_text(f"{version}+{build_prefix}\n", encoding="utf-8")


def _bridge_zip_name(output_dir: Path, *, today: datetime.date | None = None) -> str:
    """Return the legacy date-shaped bridge artifact name for v0.9.0 packaging."""
    bridge_date = (today or datetime.date.today()).isoformat()
    max_suffix = ""
    if output_dir.is_dir():
        for entry in output_dir.iterdir():
            match = _LEGACY_ZIP_NAME_RE.match(entry.name)
            if not match or match.group(1) != bridge_date:
                continue
            suffix = match.group(2)
            if suffix > max_suffix:
                max_suffix = suffix
    next_suffix = "a" if not max_suffix else chr(ord(max_suffix) + 1)
    if next_suffix > "z":
        raise RuntimeError(
            f"legacy bridge zip suffix exhausted for {bridge_date} in {output_dir}"
        )
    return f"{ZIP_PREFIX}{bridge_date}{next_suffix}.zip"


def _load_indexer():
    script_dir = Path(__file__).resolve().parent
    spec = importlib.util.spec_from_file_location("indexer", script_dir / "indexer.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["indexer"] = mod
    spec.loader.exec_module(mod)
    return mod


def build_framework_index(
    framework_dir: Path,
    *,
    source_files: list[Path] | None = None,
    verbose: bool = False,
) -> None:
    """Update the packaged framework docs/seed index under framework/index/."""
    indexer = _load_indexer()
    framework_dir = framework_dir.resolve()
    root = framework_dir
    include_prefixes: tuple[str, ...] = ()
    if framework_dir.parent.name == ".wavefoundry":
        root = framework_dir.parent.parent
        include_prefixes = (framework_dir.relative_to(root).as_posix(),)
    indexer.build_index(
        root,
        # Prefer the indexer's incremental path during packaging. The shared
        # build_index logic will automatically escalate to a full rebuild when
        # model, chunker, walker, or on-disk index state requires it.
        full=False,
        content="docs",
        index_dir=framework_dir / "index",
        include_prefixes=include_prefixes,
        respect_ignore=False,
        files=source_files,
        verbose=verbose,
    )


def _compact_framework_index(framework_dir: Path, *, verbose: bool = False) -> None:
    """Compact the packaged framework LanceDB tables after updating them."""
    indexer = _load_indexer()
    index_dir = framework_dir / "index"
    if not index_dir.is_dir():
        return
    try:
        db = indexer._get_lance_db(index_dir)
    except Exception as exc:
        raise RuntimeError(f"unable to open framework index for compaction ({exc})") from exc
    for table_name in ("docs", "code"):
        table_dir = index_dir / f"{table_name}.lance"
        if not table_dir.is_dir():
            continue
        try:
            table = db.open_table(table_name)
            indexer._optimize_lance_table(table)
            if verbose:
                print(
                    f"build_pack: compacted framework index table '{table_name}'",
                    flush=True,
                )
        except Exception as exc:
            raise RuntimeError(f"framework index compaction failed for '{table_name}' ({exc})") from exc


def update_manifest_revision(repo_root: Path, full_version: str) -> None:
    """Write full_version into framework_revision in prompt-surface-manifest.json.

    The build number is set by the packager, so the manifest is updated as a
    post-build step rather than checked as a pre-flight.  Missing or unparseable
    manifest emits a warning but does not fail the build.
    """
    import json

    manifest_path = repo_root / "docs" / "prompts" / "prompt-surface-manifest.json"
    if not manifest_path.exists():
        print(f"warning: manifest not found at {manifest_path}; skipping update.", file=sys.stderr)
        return
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        print(f"warning: could not parse manifest: {exc}; skipping update.", file=sys.stderr)
        return
    data["framework_revision"] = full_version
    manifest_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def check_docs_gate(repo_root: Path) -> None:
    """Run docs-gardener and docs-lint as a pre-packaging gate.

    Looks for each command in ``<repo_root>/.wavefoundry/bin/``.  Exits 1 if
    either command is not found or returns a non-zero exit code.
    """
    import subprocess

    bin_dir = repo_root / ".wavefoundry" / "bin"
    for cmd_name in ("docs-gardener", "docs-lint"):
        cmd_path = bin_dir / cmd_name
        if not cmd_path.exists():
            print(
                f"error: {cmd_name} not found at {cmd_path}",
                file=sys.stderr,
            )
            sys.exit(1)
        result = subprocess.run([str(cmd_path)], cwd=str(repo_root))
        if result.returncode != 0:
            print(
                f"error: {cmd_name} failed — fix docs issues before packaging.",
                file=sys.stderr,
            )
            sys.exit(1)


def build_zip(
    output_dir: Path,
    version: str,
    build_prefix: str,
    *,
    framework_dir: Optional[Path] = None,
    write_version: bool = True,
    update_manifest: bool = True,
    prebuild_index: bool = False,
    verbose: bool = False,
) -> Path:
    if version == _BRIDGE_VERSION:
        zip_name = _bridge_zip_name(output_dir)
    else:
        zip_name = f"{ZIP_PREFIX}{version}.{build_prefix}.zip"
    zip_path = output_dir / zip_name

    script_dir = Path(__file__).resolve().parent
    fw = framework_dir if framework_dir is not None else script_dir.parent
    repo_root = fw.parent.parent if fw.parent.name == ".wavefoundry" else fw.parent

    if write_version:
        write_pack_version(fw, version, build_prefix)
    if update_manifest:
        update_manifest_revision(repo_root, f"{version}+{build_prefix}")

    if prebuild_index:
        source_files = _framework_index_source_files(fw)
        build_framework_index(fw, source_files=source_files, verbose=verbose)
        _compact_framework_index(fw, verbose=verbose)

    # Remove .DS_Store files from the repo root before collecting files.
    for ds in repo_root.rglob(".DS_Store"):
        try:
            ds.unlink()
        except OSError:
            pass

    entries = collect_files(fw)
    # Write MANIFEST (always lists itself) before zipping so it is included.
    manifest_path = write_manifest(fw, entries)
    manifest_arcname = FRAMEWORK_REL + "/MANIFEST"
    # Always replace any pre-existing MANIFEST entry with the freshly written file.
    entries = [(abs_path, arcname) for abs_path, arcname in entries if arcname != manifest_arcname]
    entries.append((manifest_path, manifest_arcname))

    # Include .wavefoundry/README.md (project-owner orientation doc) if it exists.
    # This file sits outside the framework dir so must be added explicitly.
    wavefoundry_readme = fw.parent / "README.md"
    readme_arcname = ".wavefoundry/README.md"
    if wavefoundry_readme.exists() and not any(a == readme_arcname for _, a in entries):
        entries.append((wavefoundry_readme, readme_arcname))

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for abs_path, arcname in entries:
            zf.write(abs_path, arcname)

    # MANIFEST is a packaging artifact — delete it from the source tree after
    # it has been written into the zip so it does not linger as a dirty file.
    try:
        manifest_path.unlink(missing_ok=True)
    except OSError:
        pass

    return zip_path


def _reexec_with_venv_if_needed() -> None:
    """Re-exec this script under the wavefoundry venv when numpy is not importable.

    The index build step loads indexer.py in-process, which requires numpy and
    lancedb. When build_pack.py is invoked with system Python those imports fail.
    Re-execing under the venv is transparent — all argv is preserved.
    """
    try:
        import numpy  # noqa: F401
        return
    except ImportError:
        pass
    venv_python = Path.home() / ".wavefoundry" / "venv" / "bin" / "python"
    if not venv_python.exists():
        return  # no venv available; let the error surface naturally
    os.execv(str(venv_python), [str(venv_python)] + sys.argv)


def main():
    _reexec_with_venv_if_needed()
    parser = argparse.ArgumentParser(
        description="Build a semver distribution zip of Wavefoundry's framework tree."
    )
    parser.add_argument(
        "--version",
        metavar="MAJOR.MINOR.PATCH",
        required=True,
        help="Semver base version for this release (e.g. 0.9.0 or 1.0.0).",
    )
    parser.add_argument(
        "--output",
        metavar="DIR",
        help=(
            "Directory to write the zip into "
            "(default: ~/.wavefoundry/dist/, created if absent)."
        ),
    )
    parser.add_argument(
        "--skip-framework-index",
        action="store_true",
        help="Skip updating and compacting framework/index before packaging.",
    )
    parser.add_argument(
        "--skip-manifest-update",
        action="store_true",
        help="Skip writing framework_revision to prompt-surface-manifest.json after packaging.",
    )
    parser.add_argument(
        "--skip-docs-gate",
        action="store_true",
        help="Skip the docs-gardener / docs-lint pre-flight gate.",
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Print index build progress")
    args = parser.parse_args()

    # Validate version format.
    if not re.match(r"^\d+\.\d+\.\d+$", args.version):
        print(
            f"error: --version must be MAJOR.MINOR.PATCH (e.g. 0.9.0), got: {args.version!r}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Resolve output directory; create ~/.wavefoundry/dist/ if needed.
    if args.output:
        output_dir = Path(args.output).expanduser()
        if not output_dir.exists():
            print(f"error: output directory does not exist: {output_dir}", file=sys.stderr)
            sys.exit(1)
        if not output_dir.is_dir():
            print(f"error: output path is not a directory: {output_dir}", file=sys.stderr)
            sys.exit(1)
    else:
        output_dir = _DEFAULT_DIST_DIR.expanduser()
        output_dir.mkdir(parents=True, exist_ok=True)

    # Always resolve the repo root from the script's location for pre-flight checks.
    _script_dir = Path(__file__).resolve().parent
    try:
        repo_root = find_repo_root(_script_dir)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)

    # Derive the packaged 4-character build suffix from lifecycle_id.py.
    try:
        build_prefix = _build_suffix(_get_build_prefix())
    except subprocess.CalledProcessError as exc:
        print(f"error: failed to get build prefix: {exc}", file=sys.stderr)
        sys.exit(1)

    # Full version string: MAJOR.MINOR.PATCH+<build_prefix>
    full_version = f"{args.version}+{build_prefix}"

    # Pre-flight: docs gate (gardener + lint).
    if not args.skip_docs_gate:
        check_docs_gate(repo_root)

    try:
        zip_path = build_zip(
            output_dir,
            args.version,
            build_prefix,
            update_manifest=not args.skip_manifest_update,
            prebuild_index=not args.skip_framework_index,
            verbose=args.verbose,
        )
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)

    version_path = Path(__file__).resolve().parent.parent / "VERSION"
    stamp = version_path.read_text(encoding="utf-8").strip()
    print(zip_path)
    print(f"Stamped VERSION: {stamp}", file=sys.stderr)

    if args.version == _BRIDGE_VERSION:
        print(
            "Bridge release: packaged v0.9.0 with legacy date-style zip naming so "
            "pre-semver upgrade flows can adopt it directly.",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
