#!/usr/bin/env python3
"""Build a semver distribution zip of Wavefoundry's canonical framework tree.

Produces wavefoundry-MAJOR.MINOR.PATCH.<build>.zip in ~/.wavefoundry/dist/
(or a specified output directory), where <build> is the rightmost 4 characters
of the current Crockford lifecycle prefix generated by lifecycle_id.py --prefix-only.

Before building the archive, writes ``framework/VERSION`` to
``MAJOR.MINOR.PATCH+<build>`` and stamps ``framework_revision`` in
prompt-surface-manifest.json to the same value.

Usage:
    python3 build_pack.py --version MAJOR.MINOR.PATCH [--output <dir>]
"""

import argparse
import datetime
import os
import re
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


# Patterns excluded from the zip.
EXCLUDED_NAMES = {".DS_Store"}
EXCLUDED_DIRS = {"__pycache__", ".pytest_cache", ".wavefoundry"}
# Excluded path suffix relative to the framework root (forward-slash separated).
# Tests and the test runner are development-only artifacts; downstream repos that
# vendor the pack have no use for them and seeds must not instruct them to run tests.
EXCLUDED_REL_PATHS = {"scripts/tests/tmp", "scripts/tests", "scripts/run_tests.py", "scripts/benchmarks", "test-cache.json"}
# Transient/runtime artifact extensions that must never ship in the pack.
# .lock and .log are emitted at runtime by the test runner and the indexer; the
# remaining suffixes are editor/merge-conflict artifacts that should never ship
# even if someone accidentally leaves one behind in the source tree.
TRANSIENT_ARTIFACT_EXTENSIONS = (".lock", ".log", ".bak", ".swp", ".tmp", ".orig", ".rej")

FRAMEWORK_REL = ".wavefoundry/framework"
ZIP_PREFIX = "wavefoundry-"
# wavefoundry-MAJOR.MINOR.PATCH.<build>.zip
_ZIP_NAME_RE = re.compile(r"^wavefoundry-(\d+\.\d+\.\d+)\.([A-Za-z0-9]+)\.zip$")
_DEFAULT_DIST_DIR = Path("~/.wavefoundry/dist")


def find_repo_root(start: Path) -> Path:
    """Walk up from start until we find the repo root (contains AGENTS.md)."""
    current = start.resolve()
    while current != current.parent:
        if (current / "AGENTS.md").exists():
            return current
        current = current.parent
    raise RuntimeError(f"Could not locate repository root from {start}")


def _get_build_prefix() -> str:
    """Return the current Crockford lifecycle prefix from lifecycle_id.py --prefix-only.

    Retained for callers that need the full 5-character lifecycle prefix (waves,
    changes, plans). The build pack itself uses ``compute_build_suffix`` directly
    so the suffix is temporally lex-sortable; the lifecycle prefix's tail char
    (minute mod 36) is not.
    """
    script_dir = Path(__file__).resolve().parent
    result = subprocess.run(
        [sys.executable, str(script_dir / "lifecycle_id.py"), "--prefix-only"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _build_suffix(prefix: str) -> str:
    """Legacy: return the rightmost 4 characters of a lifecycle prefix.

    Kept for the test surface and any out-of-tree caller. The packaged build
    suffix now goes through ``compute_build_suffix`` directly so two consecutive
    builds always lex-sort in temporal order.
    """
    return prefix[-4:] if len(prefix) > 4 else prefix


# Wave 131bt close-out (131bu): build suffix is the last 4 chars of the
# lifecycle prefix — single source of truth.
#
# The lifecycle prefix and the build suffix both encode
# ``(days_since_epoch * 288 + bucket_5min) mod 36^k`` in base36, just with
# different widths (5 chars for the prefix, 4 for the suffix). Last 4 chars of
# the 5-char prefix == base36(packed mod 36^4), so truncation is mathematically
# equivalent to a separate 4-char encoding with the same packing.
#
# Lex order matches wall-clock order: 5832 days (~15.97 yr) for the suffix's
# 36^4 horizon, 209,952 days (~575 yr) for the prefix's 36^5 horizon. Builds
# within the same 5-minute bucket produce identical suffixes — covered by the
# same-semver-collision warning + the upgrade-selector mtime tie-break (131ht plan).


def compute_build_suffix(now_utc: datetime, epoch_utc: datetime) -> str:
    """Return the 4-character build suffix for ``now_utc`` relative to ``epoch_utc``.

    Delegates to ``lifecycle_id.build_prefix`` and truncates to the last 4 chars
    so the build suffix and the lifecycle prefix stay in sync by construction.
    """
    from lifecycle_id import build_prefix
    return build_prefix(now_utc, policy=(epoch_utc, 0))[-4:]


def _current_build_suffix() -> str:
    """Return the build suffix for the current wall-clock time using the project epoch."""
    from lifecycle_id import build_prefix
    return build_prefix()[-4:]


def _warn_on_same_semver_collision(output_dir: Path, version: str) -> None:
    """Emit a warning when ``version`` already has pack(s) in ``output_dir``.

    Non-blocking. Operators have legitimate reasons to repackage at the same
    semver (e.g., reproducing a bad build, content-only fix). The warning
    surfaces the existing pack filenames so the operator can choose to bump
    semver instead — bumping makes the upgrade selector path unambiguous
    independent of mtime tie-break behavior.
    """
    if not output_dir.is_dir():
        return
    pattern = re.compile(
        rf"^{re.escape(ZIP_PREFIX)}{re.escape(version)}\.[A-Za-z0-9]{{4}}\.zip$"
    )
    existing = sorted(p.name for p in output_dir.iterdir() if pattern.match(p.name))
    if not existing:
        return
    print(
        f"build_pack: WARNING: {len(existing)} existing pack(s) at version "
        f"{version} found in {output_dir}:",
        file=sys.stderr,
    )
    for name in existing:
        print(f"  - {name}", file=sys.stderr)
    print(
        "  Consider bumping semver (MAJOR.MINOR.PATCH) — same-version repackages "
        "rely on the upgrade selector's mtime tie-break to surface the newest. "
        "Bumping semver makes the selection unambiguous.",
        file=sys.stderr,
    )


def should_exclude(rel_path: str, name: str) -> bool:
    """Return True if this file or directory should be excluded from the zip."""
    if name in EXCLUDED_NAMES:
        return True
    # rel_path uses forward slashes relative to the framework root.
    for excl in EXCLUDED_DIRS:
        parts = rel_path.split("/")
        if excl in parts:
            return True
    for excl_rel in EXCLUDED_REL_PATHS:
        if rel_path == excl_rel or rel_path.startswith(excl_rel + "/"):
            return True
    if name.endswith(".pyc"):
        return True
    if name.endswith(TRANSIENT_ARTIFACT_EXTENSIONS):
        return True
    return False


def collect_files(framework_dir: Path) -> list[tuple[Path, str]]:
    """Return [(abs_path, zip_arcname)] for every file under framework_dir."""
    entries: list[tuple[Path, str]] = []
    for dirpath, dirnames, filenames in os.walk(framework_dir):
        dirpath = Path(dirpath)
        # Compute path relative to framework_dir using forward slashes.
        rel_dir = dirpath.relative_to(framework_dir).as_posix()
        rel_dir = "" if rel_dir == "." else rel_dir

        # Filter out excluded dirs in-place so os.walk skips them.
        dirnames[:] = [
            d for d in dirnames
            if not should_exclude(
                (rel_dir + "/" + d).lstrip("/"), d
            )
        ]

        for filename in filenames:
            rel_file = (rel_dir + "/" + filename).lstrip("/")
            if should_exclude(rel_file, filename):
                continue
            abs_path = dirpath / filename
            # arcname preserves the full path from repo root so that
            # `unzip -o zip -d <repo-root>` restores the correct layout.
            arcname = FRAMEWORK_REL + ("/" + rel_file if rel_file else "")
            entries.append((abs_path, arcname))
    return entries


def write_manifest(framework_dir: Path, entries: list[tuple[Path, str]]) -> Path:
    """Write MANIFEST listing all packed paths (relative to framework root).

    The manifest is written to disk so it can be saved before the next upgrade
    and used to prune files that were pack-delivered in the old version but
    absent from the new one.  MANIFEST always lists itself.
    """
    prefix = FRAMEWORK_REL + "/"
    rel_paths = sorted({
        *(arcname[len(prefix):] for _, arcname in entries if arcname.startswith(prefix)),
        "MANIFEST",
    })
    manifest_path = framework_dir / "MANIFEST"
    manifest_path.write_text("\n".join(rel_paths) + "\n", encoding="utf-8")
    return manifest_path


def write_pack_version(framework_dir: Path, version: str, build_prefix: str) -> None:
    """Stamp VERSION with MAJOR.MINOR.PATCH+<build_prefix> so the archive is traceable."""
    version_path = framework_dir / "VERSION"
    version_path.write_text(f"{version}+{build_prefix}\n", encoding="utf-8")


def update_manifest_revision(repo_root: Path, full_version: str) -> None:
    """Write full_version into framework_revision in prompt-surface-manifest.json.

    The build number is set by the packager, so the manifest is updated as a
    post-build step rather than checked as a pre-flight.  Missing or unparseable
    manifest emits a warning but does not fail the build.
    """
    import json

    manifest_path = repo_root / "docs" / "prompts" / "prompt-surface-manifest.json"
    if not manifest_path.exists():
        print(f"warning: manifest not found at {manifest_path}; skipping update.", file=sys.stderr)
        return
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        print(f"warning: could not parse manifest: {exc}; skipping update.", file=sys.stderr)
        return
    data["framework_revision"] = full_version
    manifest_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def check_docs_gate(repo_root: Path) -> None:
    """Run docs-gardener and docs-lint as a pre-packaging gate.

    Looks for each command in ``<repo_root>/.wavefoundry/bin/``.  Exits 1 if
    either command is not found or returns a non-zero exit code.
    """
    import subprocess

    bin_dir = repo_root / ".wavefoundry" / "bin"
    for cmd_name in ("docs-gardener", "docs-lint"):
        cmd_path = bin_dir / cmd_name
        if not cmd_path.exists():
            print(
                f"error: {cmd_name} not found at {cmd_path}",
                file=sys.stderr,
            )
            sys.exit(1)
        result = subprocess.run([str(cmd_path)], cwd=str(repo_root))
        if result.returncode != 0:
            print(
                f"error: {cmd_name} failed — fix docs issues before packaging.",
                file=sys.stderr,
            )
            sys.exit(1)


# ---------------------------------------------------------------------------
# Release-orchestration helpers (wave 1p347)
# ---------------------------------------------------------------------------
#
# These helpers support the `--release` flag, which extends `build_pack.py`
# from a local-build CLI into the official release CLI: after a successful
# local build, `--release` tags the commit, pushes the tag to origin, and
# uploads the zip as a GitHub Release asset via `gh release create`.
#
# Pre-flight checks run BEFORE the build so failures (dirty tree, wrong
# branch, missing CHANGELOG section, gh not auth'd) abort cheaply. Wave 1p4ww
# removed the shipped framework index, so there is no post-build index
# assertion. `--release-dry-run` walks the entire pipeline without side
# effects (no git tag, no push, no gh upload) so the orchestration logic
# itself can be smoke-tested before a real release.


RELEASE_NOTES_INSTALL_BLOCK_REL = Path(".wavefoundry/framework/install/install-block.md")


def _read_release_install_block(repo_root: Path) -> str:
    """Read the install block that gets prepended to every release's notes.

    Returns the block content (no trailing newline normalization beyond what
    the file itself carries) or empty string if the file is missing. Missing
    file is recoverable — callers fall through to CHANGELOG-only notes.
    """
    path = repo_root / RELEASE_NOTES_INSTALL_BLOCK_REL
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8")


def _assemble_release_notes(repo_root: Path, changelog_body: str) -> str:
    """Prepend the install block to the CHANGELOG-extracted notes.

    Wave 1p35d (1p35p): every published release carries an `## Install` block
    at the top of its notes so an agent or operator landing on the Releases
    page sees the zip-at-root → shortcut-phrase flow alongside the download
    link. Source of truth is `.wavefoundry/framework/install/install-block.md`.
    """
    block = _read_release_install_block(repo_root)
    if not block.strip():
        return changelog_body
    # Single blank line between block and changelog body. The block itself
    # ends with `---\n\n` so the join produces clean visual separation.
    joined = block.rstrip() + "\n\n" + changelog_body.lstrip()
    return joined


def _extract_changelog_section(changelog_path: Path, version: str) -> str:
    """Extract the body of the ``## [<version>]`` section from CHANGELOG.md.

    Returns the section body (excluding the heading) as a string. Empty
    string if the section is missing. The section ends at the next ``## [``
    heading or end of file.
    """
    if not changelog_path.exists():
        return ""
    text = changelog_path.read_text(encoding="utf-8")
    section_pat = re.compile(rf"^## \[{re.escape(version)}\](?:\s|$)")
    next_pat = re.compile(r"^## \[")
    out: list[str] = []
    in_section = False
    for line in text.splitlines():
        if not in_section:
            if section_pat.match(line):
                in_section = True
            continue
        if next_pat.match(line):
            break
        out.append(line)
    # Trim leading and trailing blank lines.
    while out and not out[0].strip():
        out.pop(0)
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out)


def _check_git_working_tree_clean(repo_root: Path) -> None:
    """Refuse if any tracked file is modified or any untracked-non-ignored file exists."""
    import subprocess

    result = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=str(repo_root),
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git status failed: {result.stderr.strip()}")
    if result.stdout.strip():
        raise RuntimeError(
            "working tree is not clean — commit or stash changes before --release. "
            "Uncommitted work is a signal the release isn't ready.\n"
            f"  git status --porcelain output:\n{result.stdout}"
        )


def _check_on_main_branch(repo_root: Path) -> None:
    """Refuse on any branch other than `main`."""
    import subprocess

    result = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        cwd=str(repo_root),
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git rev-parse failed: {result.stderr.strip()}")
    branch = result.stdout.strip()
    if branch != "main":
        raise RuntimeError(
            f"current branch is `{branch}` — releases must be cut from `main`."
        )


def _check_tag_does_not_exist(repo_root: Path, tag: str) -> None:
    """Refuse if the target tag exists locally or on the `origin` remote."""
    import subprocess

    local = subprocess.run(
        ["git", "rev-parse", "--verify", f"refs/tags/{tag}"],
        cwd=str(repo_root),
        check=False,
        capture_output=True,
        text=True,
    )
    if local.returncode == 0:
        raise RuntimeError(
            f"local tag `{tag}` already exists. Delete it explicitly "
            f"(`git tag -d {tag}`) before re-running --release for the same version."
        )

    remote = subprocess.run(
        ["git", "ls-remote", "--tags", "origin", f"refs/tags/{tag}"],
        cwd=str(repo_root),
        check=False,
        capture_output=True,
        text=True,
    )
    if remote.returncode != 0:
        # Network failure or no remote configured — surface but don't fail
        # the check on inability to verify. Reuse subprocess.CalledProcessError
        # semantics: empty stdout means no matching ref.
        raise RuntimeError(
            f"git ls-remote failed: {remote.stderr.strip() or 'unknown error'}"
        )
    if remote.stdout.strip():
        raise RuntimeError(
            f"remote tag `{tag}` already exists on `origin`. Delete it explicitly "
            f"(`git push origin :refs/tags/{tag}`) before re-running --release."
        )


def _check_gh_authenticated() -> None:
    """Refuse if `gh auth status` fails — the upload would fail anyway."""
    import subprocess

    result = subprocess.run(
        ["gh", "auth", "status"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "`gh auth status` failed — sign in with `gh auth login` (or `gh auth switch` "
            "to select the account that owns the release repo) before --release."
        )


def _derive_tag_message(repo_root: Path, version: str) -> str:
    """Derive an annotated-tag message from the most recent wave-close commit subject.

    Looks for commit subjects matching `Close wave <id> and ship <prev> -> <new>`
    (with either unicode `→` or ASCII `->`). On match, returns the close-wave subject
    verbatim. Falls back to a generic `Release v<version>` if no match.
    """
    import subprocess

    result = subprocess.run(
        ["git", "log", "-1", "--format=%s"],
        cwd=str(repo_root),
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return f"Release v{version}"
    subject = result.stdout.strip()
    close_pat = re.compile(r"^Close wave \S+ and ship .+\s*(?:→|->)\s*.+$")
    if close_pat.match(subject):
        return subject
    return f"Release v{version}"


def _run_release_orchestration(
    repo_root: Path,
    version: str,
    zip_path: Path,
    release_notes_body: str,
    *,
    dry_run: bool,
) -> None:
    """Commit the build stamp, tag, push main + tag, and upload via `gh release create`.

    Ordering (wave 1p5l4 fix): ``build_zip`` stamps ``VERSION`` +
    ``prompt-surface-manifest.json`` AFTER the clean-tree preflight, so those
    edits are uncommitted when this runs. We commit them FIRST, so the
    annotated tag lands on the stamp commit — matching the v1.4/v1.5 release
    convention where ``vX`` points at the "Bump VERSION to X" commit, not the
    pre-stamp commit. Then push ``main`` (so origin reflects the tagged commit)
    and the tag, then create the Release.

    On any step failure, raises RuntimeError with an actionable recovery hint
    that names the exact command to re-run the failed step manually. Partial
    state (e.g., tag pushed but `gh release create` failed) is documented
    inline in the error message.
    """
    import subprocess
    import tempfile

    tag = f"v{version}"
    tag_message = _derive_tag_message(repo_root, version)
    stamp = (repo_root / FRAMEWORK_REL / "VERSION").read_text(encoding="utf-8").strip()
    stamp_message = f"Bump VERSION to {stamp} after release"

    if dry_run:
        print(f"[--release-dry-run] would run: git add -A && git commit -m {stamp_message!r}", file=sys.stderr)
        print(f"[--release-dry-run] would run: git tag -a {tag} -m {tag_message!r}", file=sys.stderr)
        print(f"[--release-dry-run] would run: git push origin HEAD:main", file=sys.stderr)
        print(f"[--release-dry-run] would run: git push origin {tag}", file=sys.stderr)
        print(
            f"[--release-dry-run] would run: gh release create {tag} "
            f"--title {version!r} --notes-file <tmp> {zip_path}",
            file=sys.stderr,
        )
        print(
            f"[--release-dry-run] release notes (first 200 chars): {release_notes_body[:200]!r}",
            file=sys.stderr,
        )
        return

    # Step 1: commit the build stamp so the tag lands on it (not the pre-stamp
    # commit). Everything dirty here is build output — the preflight guaranteed a
    # clean tree before build_zip ran — so `git add -A` captures exactly the
    # stamp (VERSION + manifest, plus any gardener output from the docs gate).
    add_result = subprocess.run(
        ["git", "add", "-A"],
        cwd=str(repo_root),
        check=False,
        capture_output=True,
        text=True,
    )
    if add_result.returncode != 0:
        raise RuntimeError(
            f"step 1/5 (git add stamp) failed: {add_result.stderr.strip()}\n"
            f"  recovery: investigate the error above; the local repo is untouched."
        )
    # Commit only if the stamp changed something (normally it does).
    staged = subprocess.run(
        ["git", "diff", "--cached", "--quiet"],
        cwd=str(repo_root),
        check=False,
        capture_output=True,
        text=True,
    )
    if staged.returncode != 0:
        commit_result = subprocess.run(
            ["git", "commit", "-m", stamp_message],
            cwd=str(repo_root),
            check=False,
            capture_output=True,
            text=True,
        )
        if commit_result.returncode != 0:
            raise RuntimeError(
                f"step 1/5 (git commit stamp) failed: {commit_result.stderr.strip()}\n"
                f"  recovery: the stamp is staged; commit it manually "
                f"(`git commit -m {stamp_message!r}`) and re-run the remaining steps."
            )

    # Step 2: create the annotated tag locally — now on the stamp commit.
    tag_result = subprocess.run(
        ["git", "tag", "-a", tag, "-m", tag_message],
        cwd=str(repo_root),
        check=False,
        capture_output=True,
        text=True,
    )
    if tag_result.returncode != 0:
        raise RuntimeError(
            f"step 2/5 (git tag) failed: {tag_result.stderr.strip()}\n"
            f"  recovery: the stamp commit is in place; investigate the tag error, "
            f"then re-run the tag + push + release steps manually."
        )

    # Step 3: push main so origin reflects the stamp commit the tag points at.
    push_main = subprocess.run(
        ["git", "push", "origin", "HEAD:main"],
        cwd=str(repo_root),
        check=False,
        capture_output=True,
        text=True,
    )
    if push_main.returncode != 0:
        raise RuntimeError(
            f"step 3/5 (git push main) failed: {push_main.stderr.strip()}\n"
            f"  recovery: the stamp commit and local tag `{tag}` exist but nothing "
            f"was pushed. Fix the push issue, then run `git push origin HEAD:main`, "
            f"`git push origin {tag}`, and the gh release step manually — or delete "
            f"the tag (`git tag -d {tag}`) and re-run --release."
        )

    # Step 4: push the tag to origin.
    push_result = subprocess.run(
        ["git", "push", "origin", tag],
        cwd=str(repo_root),
        check=False,
        capture_output=True,
        text=True,
    )
    if push_result.returncode != 0:
        raise RuntimeError(
            f"step 4/5 (git push tag) failed: {push_result.stderr.strip()}\n"
            f"  recovery: main is pushed and local tag `{tag}` was created. Push it "
            f"manually (`git push origin {tag}`) once the underlying issue is fixed."
        )

    # Step 5: create the GitHub Release with the local zip as the asset.
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, encoding="utf-8"
    ) as notes_file:
        notes_file.write(release_notes_body)
        notes_path = notes_file.name
    try:
        release_result = subprocess.run(
            [
                "gh", "release", "create", tag,
                "--title", version,
                "--notes-file", notes_path,
                str(zip_path),
            ],
            cwd=str(repo_root),
            check=False,
            capture_output=True,
            text=True,
        )
    finally:
        try:
            os.unlink(notes_path)
        except OSError:
            pass

    if release_result.returncode != 0:
        raise RuntimeError(
            f"step 5/5 (gh release create) failed: {release_result.stderr.strip()}\n"
            f"  recovery: tag `{tag}` is already on origin. Re-run only the "
            f"release-create step:\n"
            f"    gh release create {tag} --title {version} "
            f"--notes-file <CHANGELOG-{version}-section> {zip_path}\n"
            f"  Or, if the wrong tag was pushed, delete it "
            f"(`git push origin :refs/tags/{tag}` and `git tag -d {tag}`) "
            f"and re-run --release."
        )

    print(release_result.stdout.strip(), file=sys.stderr)


def build_zip(
    output_dir: Path,
    version: str,
    build_prefix: str,
    *,
    framework_dir: Optional[Path] = None,
    write_version: bool = True,
    update_manifest: bool = True,
    inject_install_templates: bool = True,
    verbose: bool = False,
) -> Path:
    # Wave 1p4ww: the framework index is no longer built or shipped — framework
    # seeds/README fold into each project's docs index at setup/upgrade time.
    zip_name = f"{ZIP_PREFIX}{version}.{build_prefix}.zip"
    zip_path = output_dir / zip_name

    script_dir = Path(__file__).resolve().parent
    fw = framework_dir if framework_dir is not None else script_dir.parent
    repo_root = fw.parent.parent if fw.parent.name == ".wavefoundry" else fw.parent

    if write_version:
        write_pack_version(fw, version, build_prefix)
    if update_manifest:
        update_manifest_revision(repo_root, f"{version}+{build_prefix}")

    # Remove .DS_Store files from the repo root before collecting files.
    for ds in repo_root.rglob(".DS_Store"):
        try:
            ds.unlink()
        except OSError:
            pass

    entries = collect_files(fw)
    # Write MANIFEST (always lists itself) before zipping so it is included.
    manifest_path = write_manifest(fw, entries)
    manifest_arcname = FRAMEWORK_REL + "/MANIFEST"
    # Always replace any pre-existing MANIFEST entry with the freshly written file.
    entries = [(abs_path, arcname) for abs_path, arcname in entries if arcname != manifest_arcname]
    entries.append((manifest_path, manifest_arcname))

    # Include .wavefoundry/README.md (project-owner orientation doc) if it exists.
    # This file sits outside the framework dir so must be added explicitly.
    wavefoundry_readme = fw.parent / "README.md"
    readme_arcname = ".wavefoundry/README.md"
    if wavefoundry_readme.exists() and not any(a == readme_arcname for _, a in entries):
        entries.append((wavefoundry_readme, readme_arcname))

    # Source CHANGELOG.md from the wavefoundry repo root (the canonical single
    # source of truth) and place it into the pack zip at .wavefoundry/CHANGELOG.md.
    # Consumers receive the file at .wavefoundry/CHANGELOG.md on every upgrade —
    # they read it but never edit it; the wavefoundry repo's root CHANGELOG.md is
    # the only place release history is maintained. The wavefoundry repo itself
    # carries no .wavefoundry/CHANGELOG.md, so there is no duplication in git.
    # Wave 1p3i6 supersedes wave 131at's vendored-canonical design.
    root_changelog = repo_root / "CHANGELOG.md"
    changelog_arcname = ".wavefoundry/CHANGELOG.md"
    if root_changelog.exists() and not any(a == changelog_arcname for _, a in entries):
        entries.append((root_changelog, changelog_arcname))

    # Top-level entry doc sits OUTSIDE .wavefoundry/ so the unzipped folder
    # has a visible file at the root. Without it, macOS Finder shows the
    # extracted folder as empty because the only entry is `.wavefoundry/`
    # (dot-prefixed = hidden by default). The entry doc is reference
    # content — overwritten on every install/upgrade extract.
    #
    # The LIVE install log (.wavefoundry/install-log.md) is intentionally
    # NOT written to the zip. The agent copies the template to that path on
    # first install; on upgrades, the live log is preserved (not in the zip
    # to overwrite). This separates framework artifact (template, overwrites)
    # from operator state (live log, preserved).
    #
    # Wave 1p35d (1p35f): templates source-of-truth lives at
    # .wavefoundry/framework/install/. Filename convention follows the
    # framework's prompt.md pattern: foo.template.md (NOT foo.md.template).
    # Variables {{version}} and {{generated_at}} are replaced at packaging
    # time. Tests using stub framework dirs pass inject_install_templates=False.
    install_wavefoundry_md = None
    if inject_install_templates:
        install_dir = fw / "install"
        install_wavefoundry_template = install_dir / "install-wavefoundry.template.md"
        install_log_template = install_dir / "install-log.template.md"

        if not install_wavefoundry_template.exists():
            raise RuntimeError(
                f"missing template: {install_wavefoundry_template} — expected at "
                "`.wavefoundry/framework/install/install-wavefoundry.template.md`"
            )
        if not install_log_template.exists():
            raise RuntimeError(
                f"missing template: {install_log_template} — expected at "
                "`.wavefoundry/framework/install/install-log.template.md`"
            )

        install_wavefoundry_md = install_wavefoundry_template.read_text(encoding="utf-8")
        install_wavefoundry_md = install_wavefoundry_md.replace("{{version}}", version)

        # NOTE: install-log.template.md ships in the zip via the framework
        # tree scan (it lives under .wavefoundry/framework/install/ which
        # collect_files() includes). No explicit writestr for it here.
        # The template's {{generated_at}} substitution happens when the
        # agent copies it to .wavefoundry/install-log.md, not at packaging.

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for abs_path, arcname in entries:
            zf.write(abs_path, arcname)
        if install_wavefoundry_md is not None:
            zf.writestr("install-wavefoundry.md", install_wavefoundry_md)

    # MANIFEST is a packaging artifact — delete it from the source tree after
    # it has been written into the zip so it does not linger as a dirty file.
    try:
        manifest_path.unlink(missing_ok=True)
    except OSError:
        pass

    return zip_path


def _reexec_with_venv_if_needed() -> None:
    """Re-exec this script under the wavefoundry venv when numpy is not importable.

    The index build step loads indexer.py in-process, which requires numpy and
    lancedb. When build_pack.py is invoked with system Python those imports fail.
    Re-execing under the venv is transparent — all argv is preserved.
    """
    try:
        import numpy  # noqa: F401
        return
    except ImportError:
        pass
    venv_python = Path.home() / ".wavefoundry" / "venv" / "bin" / "python"
    if not venv_python.exists():
        return  # no venv available; let the error surface naturally
    script_path = str(Path(__file__).resolve())
    os.execv(str(venv_python), [str(venv_python), script_path, *sys.argv[1:]])


def main():
    _reexec_with_venv_if_needed()
    parser = argparse.ArgumentParser(
        description="Build a semver distribution zip of Wavefoundry's framework tree."
    )
    parser.add_argument(
        "--version",
        metavar="MAJOR.MINOR.PATCH",
        required=True,
        help="Semver base version for this release (e.g. 1.0.0).",
    )
    parser.add_argument(
        "--output",
        metavar="DIR",
        help=(
            "Directory to write the zip into "
            "(default: ~/.wavefoundry/dist/, created if absent)."
        ),
    )
    parser.add_argument(
        "--skip-manifest-update",
        action="store_true",
        help="Skip writing framework_revision to prompt-surface-manifest.json after packaging.",
    )
    parser.add_argument(
        "--skip-docs-gate",
        action="store_true",
        help="Skip the docs-gardener / docs-lint pre-flight gate.",
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Print index build progress")
    parser.add_argument(
        "--release",
        action="store_true",
        help=(
            "After a successful local build, also tag the commit, push the tag "
            "to origin, and publish a GitHub Release with the local zip attached. "
            "Pre-flight checks refuse on dirty tree, non-main branch, existing "
            "tag, missing CHANGELOG section, or unauthenticated gh."
        ),
    )
    parser.add_argument(
        "--release-dry-run",
        action="store_true",
        help=(
            "Walk the --release pre-flight checks and orchestration without "
            "any side effects (no git tag, no push, no gh upload). Use to "
            "smoke-test the release pipeline before a real --release."
        ),
    )
    args = parser.parse_args()

    # Validate version format.
    if not re.match(r"^\d+\.\d+\.\d+$", args.version):
        print(
            f"error: --version must be MAJOR.MINOR.PATCH (e.g. 1.0.0), got: {args.version!r}",
            file=sys.stderr,
        )
        sys.exit(1)
    version_parts = tuple(int(part) for part in args.version.split("."))
    if version_parts < (1, 0, 0):
        print(
            f"error: --version must be 1.0.0 or later; pre-1.0.0 packaging targets are no longer supported ({args.version!r})",
            file=sys.stderr,
        )
        sys.exit(1)


    # Resolve output directory; create ~/.wavefoundry/dist/ if needed.
    if args.output:
        output_dir = Path(args.output).expanduser()
        if not output_dir.exists():
            print(f"error: output directory does not exist: {output_dir}", file=sys.stderr)
            sys.exit(1)
        if not output_dir.is_dir():
            print(f"error: output path is not a directory: {output_dir}", file=sys.stderr)
            sys.exit(1)
    else:
        output_dir = _DEFAULT_DIST_DIR.expanduser()
        output_dir.mkdir(parents=True, exist_ok=True)

    # Always resolve the repo root from the script's location for pre-flight checks.
    _script_dir = Path(__file__).resolve().parent
    try:
        repo_root = find_repo_root(_script_dir)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)

    # Wave 131bt close-out: 4-character base36 build suffix that is temporally
    # lex-sortable. Replaces the prior lifecycle-prefix tail (which wrapped
    # every 36 minutes and broke `_find_latest_release_zip`'s lex tie-break).
    try:
        build_prefix = _current_build_suffix()
    except (ImportError, ValueError, OSError) as exc:
        print(f"error: failed to compute build suffix: {exc}", file=sys.stderr)
        sys.exit(1)

    # Full version string: MAJOR.MINOR.PATCH+<build_prefix>
    full_version = f"{args.version}+{build_prefix}"

    # Pre-flight: release-mode gates run BEFORE the build so failures abort
    # cheaply without wasting time on a packaging pass that's about to be
    # discarded.
    release_notes_body = ""
    if args.release or args.release_dry_run:
        try:
            _check_git_working_tree_clean(repo_root)
            _check_on_main_branch(repo_root)
            _check_tag_does_not_exist(repo_root, f"v{args.version}")
            _check_gh_authenticated()
            changelog_body = _extract_changelog_section(
                repo_root / "CHANGELOG.md", args.version
            )
            if not changelog_body.strip():
                raise RuntimeError(
                    f"CHANGELOG.md has no `## [{args.version}]` section. "
                    "Add the section (with release notes) before --release."
                )
            release_notes_body = _assemble_release_notes(repo_root, changelog_body)
        except RuntimeError as exc:
            print(f"error: release preflight failed: {exc}", file=sys.stderr)
            sys.exit(1)

    # Pre-flight: docs gate (gardener + lint).
    if not args.skip_docs_gate:
        check_docs_gate(repo_root)

    # Pre-flight: same-semver collision warning (wave 131bt 131ht). When packs at
    # the same MAJOR.MINOR.PATCH already exist in the dist dir, surface the existing
    # filenames so the operator can decide whether to bump semver or proceed. Non-
    # blocking: same-semver repackages have legitimate uses (bad-artifact recovery,
    # content-only fixes). Mtime tie-break in `_find_latest_release_zip` ensures the
    # newest pack still wins on `wave_upgrade`, but bumping semver makes it explicit.
    _warn_on_same_semver_collision(output_dir, args.version)

    try:
        zip_path = build_zip(
            output_dir,
            args.version,
            build_prefix,
            update_manifest=not args.skip_manifest_update,
            # 1p4ww: the framework index is no longer shipped — framework seeds/README
            # fold into each project's own docs index. The pack ships framework SOURCE only.
            verbose=args.verbose,
        )
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)

    version_path = Path(__file__).resolve().parent.parent / "VERSION"
    stamp = version_path.read_text(encoding="utf-8").strip()
    print(zip_path)
    print(f"Stamped VERSION: {stamp}", file=sys.stderr)

    # Release mode: post-build assertion + orchestration. Post-build because
    # the zip-contains-index check has to actually inspect the produced zip;
    # nothing earlier can verify it.
    if args.release or args.release_dry_run:
        # 1p4ww: the framework index is no longer shipped (folded into each project's
        # docs index), so the old "published zip must contain a framework index" guard
        # is removed. The dead build/guard functions are cleaned up in Stage 4.
        try:
            _run_release_orchestration(
                repo_root,
                args.version,
                zip_path,
                release_notes_body,
                dry_run=args.release_dry_run,
            )
        except RuntimeError as exc:
            print(f"error: release orchestration failed: {exc}", file=sys.stderr)
            sys.exit(1)
        if args.release_dry_run:
            print(f"[--release-dry-run] complete; no side effects taken.", file=sys.stderr)
        else:
            print(f"Released v{args.version}.", file=sys.stderr)


if __name__ == "__main__":
    main()
