#!/usr/bin/env python3
"""Render agent routing surfaces (auto-Guru tier 2–3) for Wave Framework hosts."""

from __future__ import annotations

import re
from pathlib import Path
from textwrap import dedent

MARKER_BEGIN = "<!-- waveframework:auto-guru begin — generated by render_agent_surfaces.py; do not edit -->"
MARKER_END = "<!-- waveframework:auto-guru end -->"

GURU_ROLE_REL = "docs/agents/guru.md"

AUTO_GURU_BULLET = (
    "- Code and documentation Q&A: follow **Codebase and documentation questions (auto-Guru)** "
    "in `AGENTS.md` and `docs/agents/guru.md`; use Wavefoundry MCP (`code_ask`, `docs_search`) "
    "when attached; do not answer from memory alone."
)

CURSOR_AUTO_GURU_MDC = dedent(
    """\
    ---
    description: Auto-route code and documentation questions to Guru (code_ask, docs_search, validated reads)
    globs: ["**/*"]
    alwaysApply: true
    ---

    # Auto-Guru (Cursor — optional native surface)

    Canonical rules for **all** agent hosts: `AGENTS.md` § **Codebase and documentation questions (auto-Guru)** and `docs/agents/guru.md`. This file is a Cursor-specific reinforcement of that contract.

    Applies to every chat in this workspace unless the user is invoking a **wave lifecycle** command from `docs/prompts/index.md` (**Plan feature**, **Implement wave**, **Close wave**, etc.).

    ## When this rule applies

    Treat the message as **Guru work** when the user is asking to **understand, locate, or explain** repository **source code** or **project documentation** (including `docs/architecture/`, `docs/specs/`, framework scripts, seeds, and MCP/index behavior).

    ## Required workflow

    1. Read `AGENTS.md` § **Codebase and documentation questions (auto-Guru)** and `docs/agents/guru.md`.
    2. Call Wavefoundry MCP **`code_ask`** and/or **`docs_search`** before synthesizing (server: `.cursor/mcp.json` → `wavefoundry`).
    3. Complete Guru **Pass 3** (`code_outline`, targeted `code_read`, `code_keyword`) — never answer from the `code_ask` `answer` field or memory alone.
    4. For deep technical pipelines, follow Guru **architecture write-up escalation** (architecture-reviewer + council when enabled).

    ## Cursor-specific delegation

    - Prefer MCP tools over raw `grep`/`read` for orientation when the index is healthy (`wave_index_health`).
    - For large investigations, use a **read-only subagent** (Task) with `docs/agents/guru.md` as the prompt and return cited findings to the parent thread.
    - Operators do **not** need to say **Guru**; the explicit shortcut remains in `docs/prompts/index.md`.
    """
)

CLAUDE_AUTO_GURU_SECTION = dedent(
    """\
    ## Code and documentation questions (auto-Guru)

    - Follow **Codebase and documentation questions (auto-Guru)** in `AGENTS.md` and `docs/agents/guru.md`.
    - **Delegate** code/doc Q&A to the **`guru`** subagent (`.claude/agents/guru.md`) when the investigation is large or would flood the main thread — Claude selects it automatically from the subagent `description` when appropriate.
    - Use **wavefoundry** MCP (`code_ask`, `docs_search`) when attached (`.mcp.json` at repo root).
    """
)

CURSOR_PROJECT_CONTEXT_BLOCK = dedent(
    """\
    ## Code and documentation questions (auto-Guru)

    Follow **`.cursor/rules/auto-guru.mdc`** (always-on Guru routing for code and doc Q&A).
    """
)

CLAUDE_GURU_AGENT = dedent(
    """\
    ---
    name: guru
    description: PROACTIVELY use when the user asks how this repository's source code or project documentation works — behavior, architecture, specs, framework scripts, indexing, chunking, retrieval, or where to find implementation. Do not use for wave lifecycle commands (Plan feature, Implement wave, Close wave, Prepare wave, etc.).
    tools: Read, Grep, Glob, Bash
    model: sonnet
    ---

    # Guru (Claude Code subagent — optional native surface)

    Canonical role for **all** hosts: `docs/agents/guru.md` and `AGENTS.md` § **Codebase and documentation questions (auto-Guru)**.

    ## Your job

    Answer code and documentation questions with **indexed, cited evidence** — not memory.

    1. Follow the retrieval loop, mechanism completeness, and citation rules in `docs/agents/guru.md`.
    2. Use the **wavefoundry** MCP server when attached: `code_ask`, `docs_search`, `code_search`, `code_outline`, `code_read`, `code_keyword`, `code_definition`, `code_references`, `code_dependencies`.
    3. Treat `code_ask` `answer` as a navigation pointer only; validate with Pass 3 reads before responding.
    4. Return a complete answer with file:line citations and a short list of files/ranges you read.

    ## Boundaries

    - Read-only in this subagent — do not edit source, seeds, or wave records here.
    - Architecture doc drafts and journal writes belong in the main session per `docs/agents/guru.md` write permissions.
    - Wave lifecycle execution stays with the main agent / wave-coordinator prompts.
    """
)

CODEX_AUTO_GURU_SKILL = dedent(
    """\
    ---
    name: auto-guru
    description: PROACTIVELY use when the user asks how repository source code or project documentation works — locating behavior, explaining pipelines, architecture, specs, framework scripts, indexing, chunking, retrieval, or MCP tools. Not for wave lifecycle commands (Plan feature, Implement wave, Close wave, etc.).
    ---

    # Auto-Guru (Codex skill — optional native surface)

    Canonical rules for **all** hosts: `AGENTS.md` § **Codebase and documentation questions (auto-Guru)** and `docs/agents/guru.md`.

    ## Trigger

    Use this skill for **code** and **documentation** Q&A. Skip when the user is running a wave lifecycle shortcut from `docs/prompts/index.md`.

    ## Instructions

    1. Read `AGENTS.md` § **Codebase and documentation questions (auto-Guru)**.
    2. Read and follow `docs/agents/guru.md` (classification, retrieval loop, Pass 3, citations).
    3. Register MCP if needed: `.wavefoundry/bin/register-codex-mcp` (then attach the `wavefoundry-*` server for this checkout).
    4. Prefer **`code_ask`** and **`docs_search`** over ad-hoc search when MCP is available.
    5. Complete Pass 3 validation before answering; never paraphrase only the `code_ask` `answer` field.

    ## Codex notes

    - Operators do not need to say **Guru**; this skill is the default path for code/doc questions.
    - Explicit shortcut **Guru** remains in `docs/prompts/index.md`.
    """
)


def guru_available(repo_root: Path) -> bool:
    return (repo_root / GURU_ROLE_REL).is_file()


def upsert_marked_region(text: str, region: str) -> str:
    block = f"{MARKER_BEGIN}\n{region.rstrip()}\n{MARKER_END}"
    pattern = re.compile(
        re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END),
        re.DOTALL,
    )
    if pattern.search(text):
        return pattern.sub(block, text, count=1)
    return text.rstrip() + "\n\n" + block + "\n"


def insert_after_heading(text: str, heading: str, inner: str) -> str:
    """Insert marked block after the first line matching ``heading`` (markdown ## title)."""
    if MARKER_BEGIN in text:
        return upsert_marked_region(text, inner)
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines):
        if line.strip() == heading:
            insert_at = index + 1
            while insert_at < len(lines) and lines[insert_at].strip() == "":
                insert_at += 1
            marked = f"{MARKER_BEGIN}\n{inner}\n{MARKER_END}"
            new_lines = lines[:insert_at] + ["\n", marked, "\n"] + lines[insert_at:]
            return "".join(new_lines)
    marked = f"{MARKER_BEGIN}\n{inner}\n{MARKER_END}"
    return text.rstrip() + "\n\n" + marked + "\n"


def strip_legacy_auto_guru_section(text: str) -> str:
    """Remove unmarked ``## Code and documentation questions (auto-Guru)`` sections."""
    pattern = re.compile(
        r"\n## Code and documentation questions \(auto-Guru\)\n.*?(?=\n## |\n<!-- waveframework:|\Z)",
        re.DOTALL,
    )
    return pattern.sub("\n", text)


def strip_legacy_auto_guru_lines(text: str) -> str:
    """Remove hand-seeded auto-Guru bullets superseded by marker blocks."""
    pattern = re.compile(
        r"^\- Code and documentation Q&A:.*\n",
        re.MULTILINE,
    )
    if MARKER_BEGIN in text:
        parts = []
        in_marker = False
        for line in text.splitlines(keepends=True):
            if MARKER_BEGIN in line:
                in_marker = True
                parts.append(line)
                continue
            if MARKER_END in line:
                in_marker = False
                parts.append(line)
                continue
            if in_marker:
                parts.append(line)
                continue
            if line.strip().startswith("- Code and documentation Q&A:"):
                continue
            parts.append(line)
        return "".join(parts)
    return pattern.sub("", text)


def patch_thin_pointer(
    path: Path,
    inner: str,
    *,
    after_heading: str | None = None,
) -> bool:
    if not path.is_file():
        return False
    original = strip_legacy_auto_guru_section(
        strip_legacy_auto_guru_lines(path.read_text(encoding="utf-8"))
    )
    if after_heading:
        updated = insert_after_heading(original, after_heading, inner)
    else:
        updated = upsert_marked_region(original, inner)
    if updated != original:
        path.write_text(updated, encoding="utf-8")
        return True
    return False


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def render_agent_surfaces(repo_root: Path) -> list[str]:
    """Render auto-Guru tier 2–3 surfaces. Returns paths written or updated."""
    if not guru_available(repo_root):
        return []

    written: list[str] = []

    # Tier 3 — optional native surfaces
    if (repo_root / ".cursor").exists():
        cursor_rule = repo_root / ".cursor" / "rules" / "auto-guru.mdc"
        write_text(cursor_rule, CURSOR_AUTO_GURU_MDC)
        written.append(str(cursor_rule.relative_to(repo_root)))

    if (repo_root / ".claude").exists():
        claude_agent = repo_root / ".claude" / "agents" / "guru.md"
        write_text(claude_agent, CLAUDE_GURU_AGENT)
        written.append(str(claude_agent.relative_to(repo_root)))

    codex_skill = repo_root / ".codex" / "skills" / "auto-guru" / "SKILL.md"
    write_text(codex_skill, CODEX_AUTO_GURU_SKILL)
    written.append(str(codex_skill.relative_to(repo_root)))

    # Tier 2 — thin pointers (marker blocks)
    claude_path = repo_root / "CLAUDE.md"
    if claude_path.is_file():
        claude_body = CLAUDE_AUTO_GURU_SECTION.strip()
        claude_block = f"{MARKER_BEGIN}\n{claude_body}\n{MARKER_END}"
        text = strip_legacy_auto_guru_lines(claude_path.read_text(encoding="utf-8"))
        if MARKER_BEGIN in text:
            text = re.sub(
                re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END),
                claude_block,
                text,
                count=1,
                flags=re.DOTALL,
            )
        else:
            # Replace legacy hand-authored section if present
            legacy = re.compile(
                r"\n## Code and documentation questions \(auto-Guru\)\n.*?(?=\n## |\Z)",
                re.DOTALL,
            )
            if legacy.search(text):
                text = legacy.sub("\n" + claude_block + "\n", text, count=1)
            else:
                text = insert_after_heading(text, "## Startup Order", claude_block)
        if text != claude_path.read_text(encoding="utf-8"):
            claude_path.write_text(text, encoding="utf-8")
            written.append("CLAUDE.md")

    pointer_specs: list[tuple[Path, str]] = [
        (repo_root / ".junie" / "guidelines.md", "## Key Rules"),
        (repo_root / "WARP.md", "## Key Rules"),
        (repo_root / ".github" / "copilot-instructions.md", "## Key Guardrails"),
    ]
    for path, heading in pointer_specs:
        if patch_thin_pointer(path, AUTO_GURU_BULLET, after_heading=heading):
            written.append(str(path.relative_to(repo_root)))

    cursor_ctx = repo_root / ".cursor" / "rules" / "project-context.mdc"
    if cursor_ctx.is_file():
        text = strip_legacy_auto_guru_section(
            strip_legacy_auto_guru_lines(cursor_ctx.read_text(encoding="utf-8"))
        )
        updated = upsert_marked_region(text, CURSOR_PROJECT_CONTEXT_BLOCK.strip())
        if updated != cursor_ctx.read_text(encoding="utf-8"):
            cursor_ctx.write_text(updated, encoding="utf-8")
            written.append(str(cursor_ctx.relative_to(repo_root)))

    return written


def main() -> int:
    import argparse
    import sys

    from render_platform_surfaces import discover_repo_root

    parser = argparse.ArgumentParser(description="Render auto-Guru agent routing surfaces.")
    parser.add_argument("--repo-root", default="", help="Repository root (default: auto-discover).")
    args = parser.parse_args()
    repo_root = Path(args.repo_root).resolve() if args.repo_root else discover_repo_root()
    paths = render_agent_surfaces(repo_root)
    if not paths:
        if not guru_available(repo_root):
            print(f"skip: {GURU_ROLE_REL} not found", file=sys.stderr)
        return 0
    for rel in paths:
        print(rel)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
