#!/usr/bin/env python3
"""Render agent routing surfaces (auto-Guru tier 2–3), never MCP host config."""

from __future__ import annotations

import copy
import os
import re
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent

from review_policy import (
    REVIEW_POLICY_CARRIER_REGISTRY,
    REVIEW_POLICY_SURFACE_BLOCKS,
    REVIEW_POLICY_SURFACE_MARKER_BEGIN,
    REVIEW_POLICY_SURFACE_MARKER_END,
)
from review_policy_reconcile import (
    UPGRADE_POLICY_DESTINATION,
    reconcile_upgrade_policy_surface,
)

try:
    from context_efficiency import (
        CONTEXT_EFFICIENCY_CARRIER_BLOCK,
        CONTEXT_EFFICIENCY_CARRIER_MARKER_BEGIN,
        CONTEXT_EFFICIENCY_CARRIER_MARKER_END,
        replace_carrier_block as _replace_context_efficiency_carrier_block,
    )
except ImportError:
    # Keep the renderer importable in a partially extracted/old framework so
    # setup can report one actionable propagation error at call time.
    CONTEXT_EFFICIENCY_CARRIER_BLOCK = None
    CONTEXT_EFFICIENCY_CARRIER_MARKER_BEGIN = None
    CONTEXT_EFFICIENCY_CARRIER_MARKER_END = None
    _replace_context_efficiency_carrier_block = None

MARKER_BEGIN = "<!-- wave:auto-guru begin — generated by render_agent_surfaces.py; do not edit -->"
MARKER_END = "<!-- wave:auto-guru end -->"

# Root @AGENTS.md import bridge (wave 1p5xc). The ONLY @import the framework
# adopts, and only at the root: it makes the root AGENTS.md the single source of
# truth Claude loads deterministically, while AGENTS.md-native agents read it
# directly. No per-folder bridge files, no nested @import.
ROOT_BRIDGE_MARKER_BEGIN = "<!-- wave:root-bridge begin — generated by render_agent_surfaces.py; do not edit -->"
ROOT_BRIDGE_MARKER_END = "<!-- wave:root-bridge end -->"
ROOT_BRIDGE_BLOCK = (
    f"{ROOT_BRIDGE_MARKER_BEGIN}\n"
    "@AGENTS.md\n"
    f"{ROOT_BRIDGE_MARKER_END}"
)
# The legacy prose pointer this bridge replaces.
_LEGACY_THIN_POINTER_RE = re.compile(
    r"^Thin pointer\. Read `AGENTS\.md` first[^\n]*\n",
    re.MULTILINE,
)

GURU_ROLE_REL = "docs/agents/guru.md"


@dataclass(frozen=True)
class ReviewProtocolCarrier:
    """One framework-owned review-protocol destination.

    ``conditional_existing`` is reserved for repo-local reviewers whose role
    documents are intentionally project-defined.  The reconciler updates
    those files only when the project has enabled them by creating the file.
    """

    source_seed: str
    destination: str
    conditional_existing: bool = False
    create_if_missing: bool = True


# Wave 1skt1: one typed source of truth for the finite canonical carrier set.
# Tests and reconciliation both derive from this registry; do not maintain a
# second hand-written destination list.
REVIEW_PROTOCOL_CARRIER_REGISTRY: tuple[ReviewProtocolCarrier, ...] = tuple(
    ReviewProtocolCarrier(
        carrier.source,
        carrier.destination,
        carrier.conditional_existing,
        carrier.create_if_missing,
    )
    for carrier in REVIEW_POLICY_CARRIER_REGISTRY
    if carrier.owner == "renderer" and "executable_review" in carrier.obligations
)

REVIEW_PROTOCOL_CARRIER_MANIFEST: tuple[str, ...] = tuple(
    carrier.destination for carrier in REVIEW_PROTOCOL_CARRIER_REGISTRY
)

REVIEW_PROTOCOL_MARKER_BEGIN = (
    "<!-- wave:executable-review-evidence begin — generated by "
    "render_agent_surfaces.py; preserve project-authored content outside this region -->"
)
REVIEW_PROTOCOL_MARKER_END = "<!-- wave:executable-review-evidence end -->"
REVIEW_PROTOCOL_CARRIER_BLOCK = dedent(
    """\
    ## Executable review evidence

    Follow the canonical **Executable Review Evidence Protocol** in
    `.wavefoundry/framework/seeds/209-agent-harness-core.prompt.md` for material
    approval claims and blocking findings. Exercise the public or registered
    path when one exists; keep state/interleaving probes within the protocol's
    finite risk-selected budget; record expected versus observed evidence and
    honest limitations; and never broaden task authority to run destructive,
    external, credential-bearing, or cost-bearing probes.

    Do not hand-author canonical JSONL when the lifecycle coordinator exposes
    the typed review-evidence authoring surface. Reviewers supply the
    load-bearing judgment facts to that coordinator; the authoring surface
    derives only bookkeeping, appends the fixed sibling
    `docs/waves/<wave>/events.jsonl` authority, and rebuilds the compact
    Markdown current-state projection in `wave.md`. A role without lifecycle
    mutation authority returns those facts to its coordinator instead of
    writing wave state.

    Under the current review policy, after validation apply the ordered
    four-way actionability gate:
    `do_now`, `maybe_later`, `dont_do_later`, or `not_issue`. Complete bounded
    `do_now`/`maybe_later` work before closure, create no backlog for rejected
    states, and use focused repair replay unless a load-bearing boundary change
    objectively requires a full council.

    Repair/reverification independence is enforced chain-aware at the typed
    authoring surface: a reverification sharing its `repair_start`'s context
    while declaring `fresh_context=true` is rejected as a contradiction
    (`reverification_context_not_fresh`), and a same-actor reverification is
    rejected as protocol policy (`reverification_actor_not_distinct`); both
    append nothing. The close gate audits open and reopened waves' current
    chains (`review_evidence_independence_invalid`); closed archives are never
    retroactively invalidated. Actor equality is protocol policy, not caller
    authentication — the truth of `fresh_context`, `independent`, and actor
    identity itself remains a declaration the validator cannot verify.
    """
).strip()

CONTEXT_EFFICIENCY_DESTINATION = "docs/prompts/create-wave.prompt.md"

LIFECYCLE_PROMPT_BASELINES: tuple[tuple[str, str], ...] = (
    ("docs/prompts/create-wave.prompt.md", "create-wave.prompt.md"),
    ("docs/prompts/implement-wave.prompt.md", "implement-wave.prompt.md"),
    ("docs/prompts/memory-review.prompt.md", "memory-review.prompt.md"),
    *(
        (carrier.destination, carrier.source.removeprefix("lifecycle:"))
        for carrier in REVIEW_POLICY_CARRIER_REGISTRY
        if carrier.owner == "renderer" and carrier.source.startswith("lifecycle:")
    ),
)

SCAFFOLD_BASELINES: tuple[tuple[str, str], ...] = (
    ("docs/plans/plan-template.md", "plan-template.md"),
)

PLAN_TEMPLATE_REQUIRED_HEADINGS: tuple[str, ...] = (
    "Rationale",
    "Requirements",
    "Scope",
    "Acceptance Criteria",
    "Tasks",
    "Agent Execution Graph",
    "Serialization Points",
    "Affected Architecture Docs",
    "AC Priority",
    "Progress Log",
    "Decision Log",
    "Risks",
    "Session Handoff",
)

INDEPENDENT_REFERENCE_CARRIER_BLOCK = dedent(
    """\
    ### Independent-reference verification

    For any changed implementation — feature, API or tool-surface change,
    config-driven change, bug fix, or deterministic mechanism — apply seed
    209's independent-reference rule: verify against a reference that does not
    share the implementation's assumptions (a specification, the
    independently-read acceptance criteria, the consumer/caller contract, the
    original reproduction, a materially independent implementation, a
    schema/model, or a metamorphic invariant). Name the reference, exact
    promised property, and common-mode limitations; keep one highest-risk probe
    bounded, reproducible, and limited to valid inputs and the public contract
    surface. A same-hypothesis helper or agent brief is not an independent
    reference, and implementer-authored evidence remains `independent: false`.

    Code review identifies the applicable reference and property. QA names the
    assertion that would falsify each load-bearing correctness, complexity,
    compatibility, or parity claim. Carrier-presence tests prove propagation,
    not reviewer adherence.
    """
).strip()


def _review_role_slug(carrier: ReviewProtocolCarrier) -> str | None:
    path = Path(carrier.destination)
    if path.suffix != ".md" or tuple(path.parts[:2]) != ("docs", "agents"):
        return None
    if "journals" in path.parts or "memory" in path.parts or "personas" in path.parts:
        return None
    return path.stem


def review_protocol_carriers(repo_root: Path | None = None) -> tuple[ReviewProtocolCarrier, ...]:
    """Return canonical carriers plus explicitly enabled native role wrappers.

    Native wrappers are enabled by their on-disk presence and are derived only
    from a registered canonical role.  An arbitrary wrapper therefore cannot
    opt itself into framework ownership merely by matching a directory glob.
    """

    carriers = list(REVIEW_PROTOCOL_CARRIER_REGISTRY)
    if repo_root is None:
        return tuple(carriers)
    seen = {carrier.destination for carrier in carriers}
    for carrier in REVIEW_PROTOCOL_CARRIER_REGISTRY:
        role = _review_role_slug(carrier)
        if role is None:
            continue
        candidates = (
            f".claude/agents/{role}.md",
            f".codex/skills/agent-role-{role}/SKILL.md",
        ) + ((".codex/skills/wf-guru/SKILL.md",) if role == "guru" else ())
        for destination in candidates:
            if destination in seen or not (repo_root / destination).is_file():
                continue
            carriers.append(
                ReviewProtocolCarrier(carrier.source_seed, destination, conditional_existing=True)
            )
            seen.add(destination)
    return tuple(carriers)


def review_protocol_carrier_manifest(repo_root: Path | None = None) -> tuple[str, ...]:
    return tuple(carrier.destination for carrier in review_protocol_carriers(repo_root))

AUTO_GURU_BULLET = (
    "- Code and documentation Q&A: follow **Codebase and documentation questions (auto-Guru)** "
    "in `AGENTS.md` and `docs/agents/guru.md`; use Wavefoundry MCP (`code_ask`, `docs_search`) "
    "when attached; do not answer from memory alone."
)

CURSOR_AUTO_GURU_MDC = dedent(
    """\
    ---
    description: Auto-route code and documentation questions to Guru (code_ask, docs_search, validated reads)
    globs: ["**/*"]
    alwaysApply: true
    ---

    # Auto-Guru (Cursor — optional native surface)

    Canonical rules for **all** agent hosts: `AGENTS.md` § **Codebase and documentation questions (auto-Guru)** and `docs/agents/guru.md`. This file is a Cursor-specific reinforcement of that contract.

    Applies to every chat in this workspace unless the user is invoking a **wave lifecycle** command from `docs/prompts/index.md` (**Plan feature**, **Implement wave**, **Close wave**, etc.).

    ## When this rule applies

    Treat the message as **Guru work** when the user is asking to **understand, locate, or explain** repository **source code** or **project documentation** (including `docs/architecture/`, `docs/specs/`, framework scripts, seeds, and MCP/index behavior).

    ## Required workflow

    1. Read `AGENTS.md` § **Codebase and documentation questions (auto-Guru)** and `docs/agents/guru.md`.
    2. Call Wavefoundry MCP **`code_ask`** and/or **`docs_search`** before synthesizing (server: `.cursor/mcp.json` → `wavefoundry`).
    3. Complete Guru **Pass 3** (`code_outline`, targeted `code_read`, `code_keyword`) — never answer from the `code_ask` `answer` field or memory alone.
    4. For deep technical pipelines, follow Guru **architecture write-up escalation** (architecture-reviewer + council when enabled).

    ## Cursor-specific delegation

    - Prefer MCP tools over raw `grep`/`read` for orientation when the index is healthy (`index_health`).
    - For large investigations, use a **read-only subagent** (Task) with `docs/agents/guru.md` as the prompt and return cited findings to the parent thread.
    - Operators do **not** need to say **Guru**; the explicit shortcut remains in `docs/prompts/index.md`.
    """
)

CLAUDE_AUTO_GURU_SECTION = dedent(
    """\
    ## Code and documentation questions (auto-Guru)

    - Follow **Codebase and documentation questions (auto-Guru)** in `AGENTS.md` and `docs/agents/guru.md`.
    - **Delegate** code/doc Q&A to the **`guru`** subagent (`.claude/agents/guru.md`) when the investigation is large or would flood the main thread — Claude selects it automatically from the subagent `description` when appropriate.
    - Use **wavefoundry** MCP (`code_ask`, `docs_search`) when attached (`.mcp.json` at repo root).
    """
)

CURSOR_PROJECT_CONTEXT_BLOCK = dedent(
    """\
    ## Code and documentation questions (auto-Guru)

    Follow **`.cursor/rules/auto-guru.mdc`** (always-on Guru routing for code and doc Q&A).
    """
)

CLAUDE_GURU_AGENT = dedent(
    """\
    ---
    name: guru
    description: PROACTIVELY use when the user asks how this repository's source code or project documentation works — behavior, architecture, specs, framework scripts, indexing, chunking, retrieval, or where to find implementation. Do not use for wave lifecycle commands (Plan feature, Implement wave, Close wave, Prepare wave, etc.).
    tools: Read, Grep, Glob, Bash, ToolSearch, mcp__wavefoundry__code_ask, mcp__wavefoundry__code_search, mcp__wavefoundry__code_keyword, mcp__wavefoundry__code_lexical, mcp__wavefoundry__code_read, mcp__wavefoundry__code_outline, mcp__wavefoundry__code_definition, mcp__wavefoundry__code_references, mcp__wavefoundry__code_callhierarchy, mcp__wavefoundry__code_dependencies, mcp__wavefoundry__code_impact, mcp__wavefoundry__code_list_files, mcp__wavefoundry__code_constants, mcp__wavefoundry__code_pattern, mcp__wavefoundry__code_callgraph, mcp__wavefoundry__code_graph_path, mcp__wavefoundry__code_graph_community, mcp__wavefoundry__docs_search, mcp__wavefoundry__seed_get
    model: sonnet
    ---

    # Guru (Claude Code subagent — optional native surface)

    Canonical role for **all** hosts: `docs/agents/guru.md` and `AGENTS.md` § **Codebase and documentation questions (auto-Guru)**.

    ## Your job

    Answer code and documentation questions with **indexed, cited evidence** — not memory.

    1. Follow the retrieval loop, mechanism completeness, and citation rules in `docs/agents/guru.md`.
    2. Use the **wavefoundry** MCP server when attached: `code_ask`, `docs_search`, `code_search`, `code_outline`, `code_read`, `code_keyword`, `code_definition`, `code_references`, `code_dependencies`. Load and prefer these over `grep`/`Read` for locating and understanding code; when your host defers MCP tool schemas, load them once via `ToolSearch` (e.g. `select:mcp__wavefoundry__code_ask,mcp__wavefoundry__code_references`) before falling back to shell.
    3. Treat `code_ask` `answer` as a navigation pointer only; validate with Pass 3 reads before responding.
    4. Return a complete answer with citations that lead with the symbol and keep `path:start-end` beside it, plus a short list of files/ranges you read.

    ## Boundaries

    - Read-only in this subagent — do not edit source, seeds, or wave records here.
    - Architecture doc drafts and journal writes belong in the main session per `docs/agents/guru.md` write permissions.
    - Wave lifecycle execution stays with the main agent / wave-coordinator prompts.
    """
)

# ---------------------------------------------------------------------------
# Skill registry (wave 1p6lp / change 1p6lo)
#
# One declarative registry + one emitter renders every Wavefoundry skill as
# standard SKILL.md (YAML frontmatter name/description + markdown body) into
# each ACTIVE skill-supporting host's project-local directory. Skill names
# live in a `wf-` kebab-case namespace so `/wf` filters a host's command list
# to the whole family and the names cannot collide with third-party skills in
# target repos. Bodies are THIN POINTERS to the backing prompt/seed surfaces;
# workflow content is never inlined here.
# ---------------------------------------------------------------------------

_SKILL_NAME_PATTERN = re.compile(r"^wf-[a-z0-9]+(?:-[a-z0-9]+)*$")

# Hosts that consume the cross-tool SKILL.md standard. Emission is gated on
# the host root directory existing — the same presence test the other tier-3
# surfaces use — so a repo that never enabled a host gains no stray tree.
# (`.codex` always exists after a render: render_codex_mcp_config writes the
# baseline `.codex/config.toml` unconditionally before this pass runs.)
SKILL_HOSTS: "tuple[tuple[str, str], ...]" = (
    (".codex", ".codex/skills"),
    (".claude", ".claude/skills"),
    (".agents", ".agents/skills"),
)

# Retired by the wave-1p6lp migration onto the registry: the flat,
# frontmatter-less Claude upgrade skill (invisible to current Claude Code
# skill discovery) and the pre-namespace Codex guru skill.
STALE_SKILL_PATHS: "tuple[str, ...]" = (
    ".claude/skills/upgrade-wave.md",
    ".codex/skills/auto-guru/SKILL.md",
)


@dataclass(frozen=True)
class Skill:
    """One registry entry, rendered as SKILL.md to every active skill host.

    ``requires_doc`` (wave 1ve3a, generalizing the wf-guru gate): when set, the
    skill emits only where that repo-relative doc exists. The gate follows the
    CAPABILITY (the backing doc), never a repo identity — e.g. wf-package gates
    on the packaging prompt, which seed 100 declares public-only/when-present,
    so it renders in the framework source repository and nowhere else.
    """

    name: str
    description: str
    body: str
    requires_doc: "str | None" = None


WF_GURU_SKILL_BODY = dedent(
    """\
    # Wavefoundry Guru (skill — optional native surface)

    Canonical rules for **all** hosts: `AGENTS.md` § **Codebase and documentation questions (auto-Guru)** and `docs/agents/guru.md`.

    ## Trigger

    Use this skill for **code** and **documentation** Q&A. Skip when the user is running a wave lifecycle shortcut from `docs/prompts/index.md`.

    ## Instructions

    1. Read `AGENTS.md` § **Codebase and documentation questions (auto-Guru)**.
    2. Read and follow `docs/agents/guru.md` (classification, retrieval loop, Pass 3, citations).
    3. Attach the `wavefoundry` MCP server via your host's project-local registration (see the `AGENTS.md` MCP table; Codex loads it automatically from the committed `.codex/config.toml`).
    4. Prefer **`code_ask`** and **`docs_search`** over ad-hoc search when MCP is available.
    5. Complete Pass 3 validation before answering; never paraphrase only the `code_ask` `answer` field.

    ## Notes

    - Operators do not need to say **Guru**; this skill is the default path for code/doc questions.
    - Explicit shortcut **Guru** remains in `docs/prompts/index.md`.
    """
)

WF_UPGRADE_SKILL_BODY = dedent(
    """\
    # Upgrade Wavefoundry

    **Backwards-compatible operator phrases:** *Upgrade wave framework*, *Upgrade wave context* — same checklist.

    Use this checklist when intentionally editing the wave framework or repo-local wave surfaces.

    ## Gate sequence

    1. Read `AGENTS.md` and `docs/prompts/upgrade-wavefoundry.prompt.md`.
    2. Produce a file-level patch plan and wait for operator approval before broad framework-maintenance edits.
    3. Create or update `.wavefoundry/guard-overrides.json` before editing:
       - `.wavefoundry/framework/`
       - `docs/prompts/`
       - `AGENTS.md`
       - tracked hook config files
    4. Set `framework_edit_allowed.enabled: true` after the operator approves the file-level plan.
    5. Set `seed_edit_allowed.enabled: true` before editing any `.wavefoundry/framework/seeds/*.prompt.md` file.
    6. Delete the override file or set both flags back to `false` when the maintenance pass is complete.

    ## Verification sequence

    1. Run framework tests when the test suite is present (development installs only — not included in distribution packs): `python3 -B .wavefoundry/framework/scripts/run_tests.py` (skip if `run_tests.py` does not exist)
    2. `wf render-surfaces` (hooks, MCP, bin launchers, and `render_agent_surfaces.py` when `docs/agents/guru.md` exists)
    3. Backfill `AGENTS.md` auto-Guru tier-1 sections per `seed-050` when missing; ensure `docs/agents/guru.md` exists; re-run step 2 if tier-1 was just added
    4. `./.wavefoundry/bin/wf docs-gardener` — native Windows: `.\\.wavefoundry\\bin\\wf.cmd docs-gardener` (or MCP `wf_garden_docs`)
    5. `./.wavefoundry/bin/wf docs-lint` — native Windows: `.\\.wavefoundry\\bin\\wf.cmd docs-lint` (or MCP `wf_validate_docs`)

    ## Guardrails

    - Keep inventory and drift-detection lanes read-only unless explicit write ownership was granted.
    - Update existing canonical docs in place instead of creating parallel files when a topical home already exists.
    - Preserve journals, personas, wave archives, and historical records unless the upgrade explicitly retires a live replacement surface.
    """
)

def _thin_pointer_body(title: str, prompt_doc: str, lines: "tuple[str, ...]") -> str:
    """Build a thin-pointer skill body: the workflow stays in the prompt doc.

    Wave 1p6lp (1p6lw) design contract: skill bodies never inline workflow
    content, so they cannot drift from the seeds/prompts that own behavior.
    """

    bullet_block = "\n".join(f"- {line}" for line in lines)
    return (
        f"# {title} (Wavefoundry skill)\n\n"
        f"This skill is a thin pointer: the workflow lives in `{prompt_doc}`. "
        "Read that document and follow it; do not improvise the steps from this summary.\n\n"
        f"{bullet_block}\n"
    )


WF_COUNCIL_SKILL_BODY = dedent(
    """\
    # Convene a review council (Wavefoundry skill)

    This skill is a router: pick the review form that fits the artifact, then read and follow that form's prompt doc. The full chooser table lives in `docs/prompts/archetype-council.prompt.md`.

    - Code, architecture, or trust-boundary artifact: **Council review**, `docs/prompts/council-review.prompt.md`.
    - Prose, naming, AC formulation, or decision narrative: **Archetype review**, `docs/prompts/archetype-council.prompt.md`.
    - One sharp adversarial challenge on a single artifact: **Red-team review**, `docs/prompts/red-team-review.prompt.md`.
    - These on-demand reviews record no lifecycle signoffs and satisfy no gate; when a prompt directs recording against a wave, use the `wf_review_event` MCP tool.
    - Boundary: the open wave's REQUIRED review lanes run under Review wave (`wf_review_wave`), and a change doc heading for admission gets Interrogate this plan; this router is for on-demand reviews outside both.
    """
)

SKILL_REGISTRY: "tuple[Skill, ...]" = (
    Skill(
        name="wf-plan-feature",
        description="Plan a change of any kind (feature, bug fix, enhancement, refactor, documentation, tech debt, task, maintenance, operations) and produce a consolidated change doc ready for wave admission. The Plan feature workflow.",
        body=_thin_pointer_body(
            "Plan a change",
            "docs/prompts/plan-feature.prompt.md",
            (
                "The workflow selects the scaffold among the `wf_new_<kind>` MCP creation tools (feature, bug, enhancement, refactor, documentation, tech debt, task, maintenance, operations, change) by change kind, then admits the doc with `wf_add_change`.",
                "Gate reminder: planning writes docs only; no repository code edits until the stage gate (change doc, wave admission, recorded readiness) is satisfied.",
            ),
        ),
    ),
    Skill(
        name="wf-prepare-wave",
        description="Confirm a wave's readiness before implementation (docs validation, gardening, lint, and the prepare-phase council gate). The Prepare wave / Ready wave workflow.",
        body=_thin_pointer_body(
            "Prepare a wave",
            "docs/prompts/prepare-wave.prompt.md",
            (
                "Prefer the `wf_prepare_wave` MCP tool: `dry_run` to validate, `ready` to record readiness without opening, `create` to prepare and open.",
                "The prepare-phase council review runs as the last prepare step; `wave-council-readiness` must be recorded before the wave readies.",
                "Gate reminder: only one wave may be OPEN at a time; readiness alone never takes that slot.",
            ),
        ),
    ),
    Skill(
        name="wf-implement-wave",
        description="Open a readied wave and coordinate multi-change implementation with real-time AC and task tracking. The Implement wave workflow.",
        body=_thin_pointer_body(
            "Implement a wave",
            "docs/prompts/implement-wave.prompt.md",
            (
                "Prefer the `wf_implement_wave` MCP tool to open the readied wave and receive the ordered change list and watchpoints.",
                "Gate reminder: the stage gate applies before any code edit (change doc, wave admission, recorded readiness); mark ACs and tasks as work completes, not at wave end.",
                "Single-change variant: Implement feature (`docs/prompts/implement-feature.prompt.md`).",
            ),
        ),
    ),
    Skill(
        name="wf-review-wave",
        description="Run the open wave's required review lanes and record typed review evidence ahead of closure. The Review wave workflow.",
        body=_thin_pointer_body(
            "Review a wave",
            "docs/prompts/review-wave.prompt.md",
            (
                "Start from the `wf_review_wave` MCP tool for guided actions; record evidence with `wf_review_event` (dry-run first, then create).",
                "Reminder: review evidence is typed and executable; approvals bind to the current receipt and lapse when the reviewed surface changes.",
            ),
        ),
    ),
    Skill(
        name="wf-close-wave",
        description="Finalize and archive a wave after delivery review, reconciling every AC and task checkbox. Closure is operator-owned. The Close wave workflow.",
        body=_thin_pointer_body(
            "Close a wave",
            "docs/prompts/close-wave.prompt.md",
            (
                "Prefer the `wf_close_wave` MCP tool; run `dry_run` freely to validate close readiness.",
                'Gate reminder: closure is operator-owned. Call `mode="create"` only when the operator explicitly instructs closure in the current request; closure is never inferred from adjacent actions such as "run the review" or "fix the tests".',
                "Single-change variant: Finalize feature (`docs/prompts/finalize-feature.prompt.md`).",
            ),
        ),
    ),
    Skill(
        name="wf-interrogate-plan",
        description="Stress-test a change doc before wave admission by walking every unresolved decision branch one question at a time. The Interrogate this plan workflow.",
        body=_thin_pointer_body(
            "Interrogate a plan",
            "docs/prompts/interrogate-plan.prompt.md",
            (
                "Load the change doc with the `wf_get_change` MCP tool; the interrogation itself is prompt-driven.",
                "Self-answer from project resources first; surface only the questions that genuinely need operator judgment.",
            ),
        ),
    ),
    Skill(
        name="wf-evaluate-decision",
        description="Structured evaluation of an ADR-shaped decision between two named options, running a red-team pass, council review, and operator interview, ending in an Architecture Decision Record. Not for ordinary in-flight decisions. The Evaluate decision workflow.",
        body=_thin_pointer_body(
            "Evaluate a decision",
            "docs/prompts/evaluate-decision.prompt.md",
            (
                "The workflow is prompt-driven (no dedicated MCP tool) and ends in an Architecture Decision Record.",
                "Frame two specific options before running; a poorly framed question produces a confident but useless evaluation.",
            ),
        ),
    ),
    Skill(
        name="wf-memory-review",
        description="Review and apply eligible agent-memory consolidation, archival, and purge per the memory lifecycle gates. The Memory review workflow.",
        body=_thin_pointer_body(
            "Review memories",
            "docs/prompts/memory-review.prompt.md",
            (
                "Prefer the `memory_reconcile`, `memory_consolidate`, and `memory_purge` MCP tools.",
                "Gate reminder: consolidation, archival, and purge apply only per the prompt's eligibility gates; nothing is purged on judgment alone.",
            ),
        ),
    ),
    Skill(
        name="wf-pause-wave",
        description="Park the current session's wave state in the durable handoff artifact when stopping work or handing off. The Pause wave workflow.",
        body=_thin_pointer_body(
            "Pause a wave",
            "docs/prompts/pause-wave.prompt.md",
            (
                "Prefer the `wf_pause_wave` MCP tool; it also closes any open edit gates.",
                "Write the durable handoff artifact; do not improvise a summary in its place.",
            ),
        ),
    ),
    Skill(
        name="wf-council",
        description="Convene an on-demand review on one artifact, choosing among the role-based Wave Council, the stance-based Archetype Council, and standalone Red-team review. Not the open wave's required lanes (Review wave) and not a change-doc stress test (Interrogate this plan).",
        body=WF_COUNCIL_SKILL_BODY,
    ),
    Skill(
        name="wf-guru",
        description="PROACTIVELY use when the user asks how repository source code or project documentation works — locating behavior, explaining pipelines, architecture, specs, framework scripts, indexing, chunking, retrieval, or MCP tools. Not for wave lifecycle commands (Plan feature, Implement wave, Close wave, etc.).",
        body=WF_GURU_SKILL_BODY,
        requires_doc=GURU_ROLE_REL,
    ),
    Skill(
        name="wf-upgrade",
        description="Operator checklist for intentionally editing the Wave Framework or repo-local wave surfaces (Upgrade Wavefoundry). Framework maintenance only, never product code changes.",
        body=WF_UPGRADE_SKILL_BODY,
    ),
    Skill(
        name="wf-package",
        description="Build the Wavefoundry framework distribution pack with build_pack.py (Package Wavefoundry). Available only where the packaging prompt doc exists, normally the framework source repository.",
        body=_thin_pointer_body(
            "Package Wavefoundry",
            "docs/prompts/package-wavefoundry.prompt.md",
            (
                "Prefer `--release` for a published release; a bare `--version` build only packages. `build_pack.py` hard-fails without a matching `## [version]` CHANGELOG section, so write the changelog first.",
                "Gate reminder: publishing a release is operator-owned; never push tags or publish without explicit operator instruction in the current session.",
                "The ordered verification commands live in `docs/contributing/build-and-verification.md`.",
            ),
        ),
        requires_doc="docs/prompts/package-wavefoundry.prompt.md",
    ),
    Skill(
        name="wf-code-cleanup",
        description="Recommend-only maintainability sweep of the whole codebase for dead code, duplication, complexity, abandoned files, and technical debt, producing keep/simplify/remove recommendations (Codebase cleanup review / Dead code review). It changes nothing itself; not a review of one artifact (wf-council) and not the open wave's required lanes (wf-review-wave).",
        body=_thin_pointer_body(
            "Codebase cleanup review",
            "docs/prompts/codebase-cleanup-review.prompt.md",
            (
                "The sweep is graph-based and recommend-only; it proposes, the operator disposes.",
                "Acting on a recommendation is ordinary lifecycle work (plan, admit, implement); never an inline mass deletion.",
            ),
        ),
        requires_doc="docs/prompts/codebase-cleanup-review.prompt.md",
    ),
)


def skill_document(skill: Skill) -> str:
    """Assemble the standard SKILL.md text for one registry entry."""

    return (
        f"---\nname: {skill.name}\ndescription: {skill.description}\n---\n\n{skill.body}"
    )


def _skill_output_destinations(repo_root: Path) -> list[str]:
    """Every skill path the registry pass may write, honoring both gates."""

    destinations: list[str] = []
    for skill in SKILL_REGISTRY:
        if skill.requires_doc and not (repo_root / skill.requires_doc).is_file():
            continue
        for host_root, skills_dir in SKILL_HOSTS:
            if (repo_root / host_root).is_dir():
                destinations.append(f"{skills_dir}/{skill.name}/SKILL.md")
    return destinations


def render_skills(repo_root: Path) -> list[str]:
    """Render every registry skill to each active skill host.

    Returns changed paths only (write_text compares bytes first). Runs on
    every render — per-skill doc-presence gates (requires_doc) decide skill
    eligibility; host-dir presence decides where each eligible skill lands.
    Also removes the pre-registry stale paths so migrated skills never
    coexist with their old locations.
    """

    for skill in SKILL_REGISTRY:
        if not _SKILL_NAME_PATTERN.fullmatch(skill.name):
            raise RuntimeError(
                f"skill name violates the wf- kebab-case policy: {skill.name!r}"
            )
    written: list[str] = []
    root = repo_root.resolve()
    for rel in STALE_SKILL_PATHS:
        stale = repo_root / rel
        # Containment before deletion: unlink through a symlinked component
        # would delete OUTSIDE the repository. A tampered legacy wrapper path
        # fails loudly (the same refusal contract the old write path had)
        # rather than being silently skipped or followed.
        try:
            resolved_parent = stale.parent.resolve(strict=False)
        except OSError as exc:
            raise RuntimeError(
                f"stale skill path cannot be resolved safely: {rel}: {exc}"
            ) from exc
        if stale.is_symlink() or not resolved_parent.is_relative_to(root):
            raise RuntimeError(
                f"stale skill path escapes the repository root through a symlink: {rel}"
            )
        if stale.is_file():
            stale.unlink()
            written.append(rel)
            parent = stale.parent
            # Remove the emptied per-skill directory (never the shared
            # skills/ root, which other skills may populate).
            if parent.name != "skills":
                try:
                    parent.rmdir()
                except OSError:
                    pass
    for skill in SKILL_REGISTRY:
        if skill.requires_doc and not (repo_root / skill.requires_doc).is_file():
            continue
        for host_root, skills_dir in SKILL_HOSTS:
            if not (repo_root / host_root).is_dir():
                continue
            rel = f"{skills_dir}/{skill.name}/SKILL.md"
            target = repo_root / rel
            document = skill_document(skill)
            # A skill file can also be a review carrier (wf-guru on Codex):
            # the reconcile passes own marked regions inside it. Graft any
            # existing well-formed regions into the fresh template with the
            # SAME upsert functions the reconcilers use, so a re-render is
            # byte-identical and the changed-only manifest stays quiet.
            if target.is_file():
                try:
                    existing = target.read_text(encoding="utf-8")
                except OSError:
                    existing = ""
                protocol_block = _extract_marked_block(
                    existing, REVIEW_PROTOCOL_MARKER_BEGIN, REVIEW_PROTOCOL_MARKER_END
                )
                if protocol_block is not None:
                    document = (
                        _upsert_review_protocol_region(document, protocol_block)
                        or document
                    )
                policy_block = _extract_marked_block(
                    existing,
                    REVIEW_POLICY_SURFACE_MARKER_BEGIN,
                    REVIEW_POLICY_SURFACE_MARKER_END,
                )
                if policy_block is not None:
                    document = (
                        _upsert_review_policy_region(document, policy_block)
                        or document
                    )
            if write_text(target, document):
                written.append(rel)
    return written

CODEX_MCP_CONFIG_TOML = dedent(
    """\
    [mcp_servers.wavefoundry]
    command = "python3"
    args = [".wavefoundry/framework/scripts/server.py"]
    """
)

# Wave 1p9pe (renderer-overwrite-safety): `.codex/config.toml` is an
# operator-extensible surface (approval modes, tool policy, other MCP servers).
# The renderer owns ONLY the marked region below; everything outside it is
# operator-owned and must survive every render byte-for-byte. TOML `#` comment
# markers mirror the markdown MARKER_BEGIN/MARKER_END precedent.
CODEX_CONFIG_MARKER_BEGIN = (
    "# wave:codex-mcp begin — generated by render_platform_surfaces.py; "
    "do not edit inside this region; add operator config outside it"
)
CODEX_CONFIG_MARKER_END = "# wave:codex-mcp end"

_LEGACY_OWNED_MARKERS = {
    (
        "# waveframework:codex-mcp begin — generated by render_platform_surfaces.py; "
        "do not edit inside this region; add operator config outside it"
    ): CODEX_CONFIG_MARKER_BEGIN,
    (
        "# wave:codex-mcp begin — generated by render_agent_surfaces.py; "
        "do not edit inside this region; add operator config outside it"
    ): CODEX_CONFIG_MARKER_BEGIN,
    "<!-- waveframework:auto-guru begin — generated by render_agent_surfaces.py; do not edit -->": MARKER_BEGIN,
    "<!-- waveframework:auto-guru end -->": MARKER_END,
    "<!-- waveframework:root-bridge begin — generated by render_agent_surfaces.py; do not edit -->": ROOT_BRIDGE_MARKER_BEGIN,
    "<!-- waveframework:root-bridge end -->": ROOT_BRIDGE_MARKER_END,
    (
        "<!-- waveframework:executable-review-evidence begin — generated by "
        "render_agent_surfaces.py; preserve project-authored content outside this region -->"
    ): REVIEW_PROTOCOL_MARKER_BEGIN,
    "<!-- waveframework:executable-review-evidence end -->": REVIEW_PROTOCOL_MARKER_END,
    (
        "# waveframework:codex-mcp begin — generated by render_agent_surfaces.py; "
        "do not edit inside this region; add operator config outside it"
    ): CODEX_CONFIG_MARKER_BEGIN,
    "# waveframework:codex-mcp end": CODEX_CONFIG_MARKER_END,
}


def _canonicalize_owned_markers(text: str) -> str:
    """Migrate exact legacy renderer markers without touching project prose."""

    for legacy, canonical in _LEGACY_OWNED_MARKERS.items():
        text = text.replace(legacy, canonical)
    return text

_CODEX_FRAMEWORK_KEYS = ("command", "args")

# Review-fix (1p9pe follow-up hardening): line-anchored marker-region match.
# Both markers must sit on their own lines (they are TOML comments) — a marker
# string embedded inside an operator string value must never select the
# replace-region branch, or the substitution would slice through the string.
# The line tails tolerate a trailing \r so a CRLF-rewritten config (editor or
# tooling re-encoded the file) still matches its marker region and gets a
# fresh framework block instead of perpetually fail-safing with a stale one.
_CODEX_MARKER_REGION_RE = re.compile(
    "^"
    + re.escape(CODEX_CONFIG_MARKER_BEGIN)
    + r"[ \t\r]*\n.*?^"
    + re.escape(CODEX_CONFIG_MARKER_END)
    + r"[ \t\r]*(?:\n|\Z)",
    re.MULTILINE | re.DOTALL,
)

# Review-fix: the unmarked-table migration must accept the TOML-equivalent
# header spellings — quoted keys ([mcp_servers."wavefoundry"]) and whitespace
# around the dot / inside the brackets — so those shapes MIGRATE instead of
# being re-declared by the append branch (a duplicate table is invalid TOML).
_CODEX_TABLE_HEADER_RE = re.compile(
    r"""^\[\s*(?:mcp_servers|"mcp_servers"|'mcp_servers')\s*\.\s*"""
    r"""(?:wavefoundry|"wavefoundry"|'wavefoundry')\s*\]\s*$"""
)

# Review-fix: hard bound on multi-line value absorption. The framework template
# has only ever emitted one-line values; a continuation run longer than this is
# a bracket-count desync (e.g. an unbalanced "[" inside an operator-edited
# string), and absorbing further would eat operator content.
_CODEX_ABSORB_MAX_VALUE_LINES = 10


def _codex_value_bracket_delta(fragment: str) -> int:
    """Net bracket-nesting delta for a TOML value fragment.

    Used only to absorb multi-line ``command``/``args`` values during the
    one-time unmarked-table migration. Plain counting cannot see string
    boundaries, so an unbalanced bracket INSIDE a string desyncs the count —
    ``upsert_codex_mcp_config`` guards that with the continuation-line cap
    and the end-of-absorption ``value_depth != 0`` fail-safe.
    """
    return (
        fragment.count("[")
        + fragment.count("{")
        - fragment.count("]")
        - fragment.count("}")
    )


def _codex_marker_in_multiline_string(value) -> bool:
    """True if any string in a parsed TOML value tree embeds a marker line.

    A MULTILINE operator string (triple-quoted) whose body reproduces a marker
    comment as a whole physical line defeats the line-anchored region regex:
    the region replace would slice through the string, and the sliced result
    can still parse, so a parse check alone is blind to the loss. Legitimate
    marked regions keep marker text only in TOML comment lines — which the
    parser drops — so marker text inside a PARSED string value that spans
    lines is always an embedding and no rewrite is safe. Single-line strings
    cannot line-anchor the regex (their opening quote precedes the marker on
    the physical line) and are tolerated.
    """
    if isinstance(value, str):
        return "\n" in value and (
            CODEX_CONFIG_MARKER_BEGIN in value or CODEX_CONFIG_MARKER_END in value
        )
    if isinstance(value, dict):
        return any(_codex_marker_in_multiline_string(item) for item in value.values())
    if isinstance(value, list):
        return any(_codex_marker_in_multiline_string(item) for item in value)
    return False


def _codex_normalized_doc(doc: dict) -> dict:
    """Normalize a parsed config for the semantic-equivalence exit guard.

    Strips exactly the differences a legitimate upsert makes — the framework-
    owned ``command``/``args`` keys of ``[mcp_servers.wavefoundry]`` (refreshed
    to the current template) and the creation of that table (or its
    ``mcp_servers`` parent) where it was absent. Marker comments are invisible
    to the parser and need no tolerance. After normalization, ANY difference
    between the existing and candidate documents is operator-owned content the
    merge would corrupt — valid-TOML content loss a parse check cannot flag.
    """
    normalized = copy.deepcopy(doc)
    servers = normalized.get("mcp_servers")
    if isinstance(servers, dict):
        table = servers.get("wavefoundry")
        if isinstance(table, dict):
            table.pop("command", None)
            table.pop("args", None)
            if not table:
                del servers["wavefoundry"]
        if not servers:
            del normalized["mcp_servers"]
    return normalized


def upsert_codex_mcp_config(
    existing: str | None,
    on_fail_safe=None,
) -> str:
    """Return new `.codex/config.toml` content with the framework region upserted.

    Non-destructive by contract (AGENTS.md: "Never overwrite project-local
    customizations"):

    - No file / empty file: return just the marked framework region.
    - Marker region present (both markers on their own lines; CRLF line
      endings tolerated): replace only the region between them; all operator
      content outside survives byte-for-byte, and a re-render is idempotent.
    - Markers absent but an unmarked top-level ``[mcp_servers.wavefoundry]``
      table exists (pre-marker renders; TOML-equivalent quoted/whitespace
      header spellings included): one-time migration — absorb the contiguous
      framework-owned ``command``/``args`` lines into the marked region
      without duplicating the table. Because the markers are TOML comments,
      any operator-added keys left in place directly after the end marker
      still belong to ``[mcp_servers.wavefoundry]``.
    - Neither markers nor table: append the marked region after the operator
      content.

    Single-exit fail-safe (review hardening): every branch that MERGES with
    operator content computes a candidate that is validated before being
    returned — it must parse with ``tomllib`` AND be semantically equivalent
    to the parsed existing content after normalizing the framework-owned
    differences (see ``_codex_normalized_doc``). If validation fails — or the
    merge looks ambiguous up front (marker text outside a well-formed region
    or embedded in a multiline string value, bracket-depth desync, oversized
    absorption) — the existing content is returned unchanged (a stale
    framework block is recoverable; a corrupted operator config is not). When
    that happens the optional ``on_fail_safe(reason)`` callback is invoked so
    the caller can warn loudly and skip reporting the file as written. One
    deliberate exception to the validated exit: the no-existing-content branch
    returns the constant framework block directly — it is renderer-constant
    content with no operator merge, so there is nothing to corrupt.
    """

    original_existing = existing

    def fail_safe(reason: str) -> str:
        if on_fail_safe is not None:
            on_fail_safe(reason)
        return original_existing if original_existing is not None else ""

    import tomllib

    block = (
        f"{CODEX_CONFIG_MARKER_BEGIN}\n"
        f"{CODEX_MCP_CONFIG_TOML.rstrip()}\n"
        f"{CODEX_CONFIG_MARKER_END}\n"
    )
    if existing is None or existing.strip() == "":
        # Unvalidated by design: constant framework content, no operator merge.
        return block
    existing = _canonicalize_owned_markers(existing)

    # Parse the existing content once, up front. An unparseable operator file
    # (already broken before we arrived) keeps the historical branch behavior:
    # the string-embedding pre-check and the semantic-equivalence exit guard
    # below both require a parsed baseline and are skipped.
    existing_doc: dict | None = None
    try:
        existing_doc = tomllib.loads(existing)
    except Exception:
        existing_doc = None

    # Fail-safe BEFORE branch selection: a multiline operator string that
    # reproduces a marker comment as a whole physical line would match the
    # line-anchored region regex and slice the string — and the sliced result
    # can still parse, so only this structural check catches it early with a
    # precise reason (the equivalence exit guard is the backstop).
    if existing_doc is not None and _codex_marker_in_multiline_string(existing_doc):
        return fail_safe(
            "marker text found inside a multiline operator string value; "
            "region matching would slice the string — cannot upsert safely"
        )

    candidate: str
    region_match = _CODEX_MARKER_REGION_RE.search(existing)
    if region_match is not None:
        candidate = existing[: region_match.start()] + block + existing[region_match.end():]
    elif CODEX_CONFIG_MARKER_BEGIN in existing or CODEX_CONFIG_MARKER_END in existing:
        # Marker text exists but not as a well-formed whole-line region (e.g.
        # inside an operator string, or a half-deleted region). Any rewrite
        # here risks slicing operator content — leave the file alone.
        return fail_safe(
            "marker text present outside a well-formed marker region; "
            "cannot upsert safely"
        )
    else:
        lines = existing.splitlines(keepends=True)
        header_index = next(
            (
                index
                for index, line in enumerate(lines)
                if _CODEX_TABLE_HEADER_RE.match(line.strip())
            ),
            None,
        )
        if header_index is None:
            candidate = existing.rstrip("\n") + "\n\n" + block
        else:
            # One-time absorption of the unmarked framework table: consume the
            # header plus the contiguous run of framework-owned assignments
            # (with multi-line value continuations). Stop at the first
            # operator-authored line (comment, unknown key, blank-line-then-
            # next-table) so operator content — including subtables like
            # [mcp_servers.wavefoundry.tools.*] — stays in place.
            absorbed_end = header_index + 1
            index = header_index + 1
            value_depth = 0
            continuation_lines = 0
            while index < len(lines):
                stripped = lines[index].strip()
                if value_depth > 0:
                    continuation_lines += 1
                    if continuation_lines > _CODEX_ABSORB_MAX_VALUE_LINES:
                        return fail_safe(
                            "unmarked-table migration would absorb more than "
                            f"{_CODEX_ABSORB_MAX_VALUE_LINES} value-continuation "
                            "lines — likely a bracket-count desync"
                        )
                    value_depth += _codex_value_bracket_delta(stripped)
                    index += 1
                    absorbed_end = index
                    continue
                if stripped == "":
                    # Tentatively skip: absorbed only if more framework lines follow.
                    index += 1
                    continue
                key, separator, value = stripped.partition("=")
                if separator == "=" and key.strip().strip("\"'") in _CODEX_FRAMEWORK_KEYS:
                    value_depth = _codex_value_bracket_delta(value)
                    continuation_lines = 0
                    index += 1
                    absorbed_end = index
                    continue
                break
            if value_depth != 0:
                # Bracket depth never returned to zero: an unbalanced bracket
                # (typically inside an operator-modified string) desynced the
                # counter and absorption would silently eat operator content
                # — possibly producing VALID TOML the parse guard below cannot
                # flag. Fail safe instead.
                return fail_safe(
                    "unmarked-table migration ended with unbalanced bracket "
                    "depth — refusing to absorb (operator content would be lost)"
                )
            candidate = "".join(lines[:header_index] + [block] + lines[absorbed_end:])

    # Single exit: no merged content leaves this function unvalidated.
    try:
        candidate_doc = tomllib.loads(candidate)
    except Exception:
        # Never write a config Codex cannot parse. Leaving the file
        # untouched keeps the operator's working config; the framework
        # block simply stays stale until resolved manually.
        return fail_safe("merged result would not parse as TOML")
    # Semantic-equivalence guard: the parse check alone is blind to
    # valid-TOML content loss (an absorption desync or string slice can
    # eat operator content and still produce parseable TOML). After
    # normalizing the framework-owned differences, existing and candidate
    # must describe the SAME document; anything else is operator content
    # the merge would silently drop or alter.
    if existing_doc is not None and (
        _codex_normalized_doc(existing_doc) != _codex_normalized_doc(candidate_doc)
    ):
        return fail_safe(
            "merged result would change operator-owned parsed content "
            "(valid-TOML content loss the parse check cannot flag) — "
            "refusing to write"
        )
    return candidate


def guru_available(repo_root: Path) -> bool:
    return (repo_root / GURU_ROLE_REL).is_file()


def upsert_marked_region(text: str, region: str) -> str:
    text = _canonicalize_owned_markers(text)
    block = f"{MARKER_BEGIN}\n{region.rstrip()}\n{MARKER_END}"
    pattern = re.compile(
        re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END),
        re.DOTALL,
    )
    if pattern.search(text):
        return pattern.sub(block, text, count=1)
    return text.rstrip() + "\n\n" + block + "\n"


def insert_after_heading(text: str, heading: str, inner: str) -> str:
    """Insert marked block after the first line matching ``heading`` (markdown ## title)."""
    if MARKER_BEGIN in text:
        return upsert_marked_region(text, inner)
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines):
        if line.strip() == heading:
            insert_at = index + 1
            while insert_at < len(lines) and lines[insert_at].strip() == "":
                insert_at += 1
            marked = f"{MARKER_BEGIN}\n{inner}\n{MARKER_END}"
            new_lines = lines[:insert_at] + ["\n", marked, "\n"] + lines[insert_at:]
            return "".join(new_lines)
    marked = f"{MARKER_BEGIN}\n{inner}\n{MARKER_END}"
    return text.rstrip() + "\n\n" + marked + "\n"


def strip_legacy_auto_guru_section(text: str) -> str:
    """Remove unmarked ``## Code and documentation questions (auto-Guru)`` sections."""
    pattern = re.compile(
        r"\n## Code and documentation questions \(auto-Guru\)\n.*?(?=\n## |\n<!-- (?:wave|waveframework):|\Z)",
        re.DOTALL,
    )
    return pattern.sub("\n", text)


def strip_legacy_auto_guru_lines(text: str) -> str:
    """Remove hand-seeded auto-Guru bullets superseded by marker blocks."""
    text = _canonicalize_owned_markers(text)
    pattern = re.compile(
        r"^\- Code and documentation Q&A:.*\n",
        re.MULTILINE,
    )
    if MARKER_BEGIN in text:
        parts = []
        in_marker = False
        for line in text.splitlines(keepends=True):
            if MARKER_BEGIN in line:
                in_marker = True
                parts.append(line)
                continue
            if MARKER_END in line:
                in_marker = False
                parts.append(line)
                continue
            if in_marker:
                parts.append(line)
                continue
            if line.strip().startswith("- Code and documentation Q&A:"):
                continue
            parts.append(line)
        return "".join(parts)
    return pattern.sub("", text)


def patch_thin_pointer(
    path: Path,
    inner: str,
    *,
    after_heading: str | None = None,
) -> bool:
    if not path.is_file():
        return False
    disk_text = path.read_text(encoding="utf-8")
    original = strip_legacy_auto_guru_section(
        strip_legacy_auto_guru_lines(_canonicalize_owned_markers(disk_text))
    )
    if after_heading:
        updated = insert_after_heading(original, after_heading, inner)
    else:
        updated = upsert_marked_region(original, inner)
    if updated != disk_text:
        path.write_text(updated, encoding="utf-8")
        return True
    return False


def patch_root_bridge(path: Path) -> bool:
    """Ensure the root CLAUDE.md is a real ``@AGENTS.md`` import (1p5xc).

    Replaces the legacy prose pointer ("Thin pointer. Read `AGENTS.md` first…")
    with a marked ``@AGENTS.md`` import block so Claude loads AGENTS.md
    deterministically. Idempotent. This is the only ``@import`` the framework
    adopts and only at the root — never per-folder.
    """
    if not path.is_file():
        return False
    original = path.read_text(encoding="utf-8")
    text = _canonicalize_owned_markers(original)

    # Refresh an existing bridge block in place.
    bridge_re = re.compile(
        re.escape(ROOT_BRIDGE_MARKER_BEGIN) + r".*?" + re.escape(ROOT_BRIDGE_MARKER_END),
        re.DOTALL,
    )
    if bridge_re.search(text):
        text = bridge_re.sub(ROOT_BRIDGE_BLOCK, text, count=1)
        if text != original:
            path.write_text(text, encoding="utf-8")
            return True
        return False

    # Replace the legacy prose pointer if present; otherwise insert after the H1.
    if _LEGACY_THIN_POINTER_RE.search(text):
        text = _LEGACY_THIN_POINTER_RE.sub(ROOT_BRIDGE_BLOCK + "\n", text, count=1)
    else:
        lines = text.splitlines(keepends=True)
        insert_at = 0
        for index, line in enumerate(lines):
            if line.startswith("# "):
                insert_at = index + 1
                while insert_at < len(lines) and lines[insert_at].strip() == "":
                    insert_at += 1
                break
        block = ROOT_BRIDGE_BLOCK + "\n"
        new_lines = lines[:insert_at] + ["\n", block, "\n"] + lines[insert_at:]
        text = "".join(new_lines)

    if text != original:
        path.write_text(text, encoding="utf-8")
        return True
    return False


def write_text(path: Path, content: str) -> bool:
    """Write ``content`` and report whether the on-disk bytes changed.

    Wave 1t72b (1t727-adjacent live find): callers report written paths into
    the sync manifest, so a byte-identical rewrite must return False — the
    same changed-only semantics as this module's marker-block writers.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        if path.exists() and path.read_bytes() == content.encode("utf-8"):
            return False
    except OSError:
        pass
    # newline="" disables newline translation so the embedded line terminators are written
    # VERBATIM, byte-identical on every rendering host (mirrors render_platform_surfaces.write_text,
    # wave 1p7tz). With the default newline=None, a re-render on native Windows translates every
    # "\n" → os.linesep ("\r\n"), so the freshly generated agent surfaces (auto-guru.mdc, guru.md,
    # SKILL.md, config.toml) would gain CRLF and diff full-file on re-render. The source strings
    # already carry LF terminators, so newline="" is right for all hosts.
    with path.open("w", encoding="utf-8", newline="") as handle:
        handle.write(content)
    return True


def _carrier_protocol_block(carrier: ReviewProtocolCarrier) -> str:
    """Return the shared minimum plus any destination-specific obligations."""

    block = REVIEW_PROTOCOL_CARRIER_BLOCK
    if carrier.source_seed in {
        "221-code-reviewer.prompt.md",
        "239-qa-reviewer.prompt.md",
    }:
        block += "\n\n" + INDEPENDENT_REFERENCE_CARRIER_BLOCK
    if carrier.destination != "docs/agents/qa-reviewer.md":
        return block
    return block + "\n\n" + dedent(
        """\
        ### QA evidence integrity

        Required QA evidence must run with zero unintended skips, reach the
        named public path, use realistic boundary values, make non-vacuous
        assertions, and demonstrate detection of the known-bad behavior. A
        skipped, vacuous, impossible-shape, or wrong-reason failure is not
        approval evidence. The repairing actor must not reverify its own
        repair: the tool rejects the decidable contradictions, and QA verifies
        the part no validator can — that the independence and freshness
        declarations are truthful.
        """
    ).strip()


def _upsert_review_protocol_region(text: str, block: str) -> str | None:
    """Return text with the owned protocol block refreshed, or ``None`` on malformed markers."""

    text = _canonicalize_owned_markers(text)
    begin_count = text.count(REVIEW_PROTOCOL_MARKER_BEGIN)
    end_count = text.count(REVIEW_PROTOCOL_MARKER_END)
    if begin_count != end_count or begin_count > 1:
        return None
    marked = (
        f"{REVIEW_PROTOCOL_MARKER_BEGIN}\n"
        f"{block}\n"
        f"{REVIEW_PROTOCOL_MARKER_END}"
    )
    if begin_count == 1:
        region = re.compile(
            r"^" + re.escape(REVIEW_PROTOCOL_MARKER_BEGIN) + r"[ \t\r]*\n.*?^"
            + re.escape(REVIEW_PROTOCOL_MARKER_END) + r"[ \t\r]*(?=\n|\Z)",
            re.MULTILINE | re.DOTALL,
        )
        if not region.search(text):
            return None
        return region.sub(marked, text, count=1)
    # Project-authored bytes are an exact prefix on first adoption. Do not use
    # rstrip(): trailing spaces and blank lines outside the owned region belong
    # to the project even when they look cosmetically redundant.
    separator = "" if not text or text.endswith("\n") else "\n"
    return text + separator + "\n" + marked + "\n"


def _upsert_review_policy_region(text: str, block: str) -> str | None:
    """Refresh the single registry-owned lifecycle policy block."""

    begin_count = text.count(REVIEW_POLICY_SURFACE_MARKER_BEGIN)
    end_count = text.count(REVIEW_POLICY_SURFACE_MARKER_END)
    if begin_count != end_count or begin_count > 1:
        return None
    marked = (
        f"{REVIEW_POLICY_SURFACE_MARKER_BEGIN}\n{block}\n"
        f"{REVIEW_POLICY_SURFACE_MARKER_END}"
    )
    if begin_count == 1:
        region = re.compile(
            r"^" + re.escape(REVIEW_POLICY_SURFACE_MARKER_BEGIN) + r"[ \t\r]*\n.*?^"
            + re.escape(REVIEW_POLICY_SURFACE_MARKER_END) + r"[ \t\r]*(?=\n|\Z)",
            re.MULTILINE | re.DOTALL,
        )
        if not region.search(text):
            return None
        return region.sub(marked, text, count=1)
    if REVIEW_PROTOCOL_MARKER_BEGIN in text:
        # Keep project-authored suffix bytes at the end of an adopted review
        # carrier. The policy block belongs beside the existing framework-owned
        # review block, not after a project's trailing extension.
        return text.replace(
            REVIEW_PROTOCOL_MARKER_BEGIN,
            marked + "\n\n" + REVIEW_PROTOCOL_MARKER_BEGIN,
            1,
        )
    separator = "" if not text or text.endswith("\n") else "\n"
    return text + separator + "\n" + marked + "\n"


def _extract_marked_block(text: str, begin: str, end: str) -> "str | None":
    """Return the inner block of a single well-formed marker region, else None."""

    if text.count(begin) != 1 or text.count(end) != 1:
        return None
    match = re.search(
        r"^"
        + re.escape(begin)
        + r"[ \t\r]*\n(.*?)\n"
        + re.escape(end)
        + r"[ \t\r]*(?=\n|\Z)",
        text,
        re.MULTILINE | re.DOTALL,
    )
    return match.group(1) if match else None


def _context_efficiency_carrier_block() -> str:
    """Load the canonical carrier without duplicating its prose in the renderer.

    The local import keeps old setup/upgrade environments importable until the
    public render path actually needs the new carrier. A partially extracted
    framework must fail with one actionable error rather than silently render a
    stale fallback copy.
    """

    block = CONTEXT_EFFICIENCY_CARRIER_BLOCK
    begin = CONTEXT_EFFICIENCY_CARRIER_MARKER_BEGIN
    end = CONTEXT_EFFICIENCY_CARRIER_MARKER_END
    if (
        not isinstance(block, str)
        or not block.strip()
        or not isinstance(begin, str)
        or not isinstance(end, str)
        or block.count(begin) != 1
        or block.count(end) != 1
        or not callable(_replace_context_efficiency_carrier_block)
    ):
        raise RuntimeError(
            "context-efficiency carrier source is invalid; expected non-empty "
            "canonical block and marker constants from context_efficiency.py"
        )
    return block.strip()


def _initial_review_carrier_text(repo_root: Path, carrier: ReviewProtocolCarrier) -> str:
    """Return a usable canonical minimum for a missing enabled carrier.

    Most carrier seeds are themselves complete role/prompt bodies, so the
    public renderer can materialize them directly.  The two bootstrap-owner
    seeds (100 and 209) describe several outputs rather than one file; those
    destinations receive a small durable pointer instead of an unrelated full
    bootstrap document.  Later project-specific refreshes may extend either
    form outside the owned protocol region.
    """

    if carrier.destination == "docs/prompts/create-wave.prompt.md":
        return dedent(
            """\
            # Create Wave

            New waves must use `wf_create_wave` when MCP is available. The
            scaffold creates an exactly empty sibling `events.jsonl` (the sole
            machine authority for review evidence), declares
            `review-evidence-source: events.jsonl` in `wave.md`, and renders
            the non-authoritative `## Finding Synthesis` current-state
            projection.

            Never put canonical JSONL inside `wave.md`. Without MCP, create the
            sibling as an exactly empty file and reproduce this minimal
            Markdown declaration/projection:

            review-evidence-source: events.jsonl

            ## Finding Synthesis

            No review findings recorded.
            """
        )
    seed_path = repo_root / ".wavefoundry" / "framework" / "seeds" / carrier.source_seed
    if carrier.source_seed not in {
        "100-project-prompt-surface-bootstrap.prompt.md",
        "209-agent-harness-core.prompt.md",
    } and seed_path.is_file():
        return seed_path.read_text(encoding="utf-8")
    title = Path(carrier.destination).stem.replace(".prompt", "").replace("-", " ").title()
    # Wave 1viyu (CODE-DEL-1): a fresh pointer carrier is a `docs/**/*.md`
    # file that `check_metadata` requires Owner/Status/Last verified on, so
    # the materialized minimum carries them (stamped with today's date).
    return (
        f"# {title}\n\n"
        "Owner: Engineering\n"
        "Status: active\n"
        f"Last verified: {time.strftime('%Y-%m-%d')}\n\n"
        f"Canonical framework source: `.wavefoundry/framework/seeds/{carrier.source_seed}`.\n\n"
        "This minimum carrier was materialized by the public Wavefoundry "
        "setup/upgrade renderer. Project-specific guidance may be added "
        "outside the framework-owned region below.\n"
    )


_AGENT_ROLE_LINE_RE = re.compile(r"^Role:\s+", re.MULTILINE)
_AGENT_CATEGORY_LINE_RE = re.compile(r"^Category:\s+", re.MULTILINE)


def _ensure_agent_frontmatter(content: str, destination: str) -> str:
    """Inject the `Role:`/`Category:` frontmatter a fresh ``docs/agents/**`` carrier needs.

    The agent-metadata docs-lint validator requires every ``docs/agents/**/*.md`` to
    declare ``Role:`` (equal to the filename slug) and ``Category:`` (path-derived). A
    carrier materialized fresh from a seed body that omits those lines would fail the
    pack's own validator (the failure that blocked a 1.13.0 upgrade at the docs gate),
    so inject the missing field(s) here — **only when absent**, never overwriting a
    value the seed or an existing project-authored file already provides. Category is
    derived from the validator's own ``_expected_agent_category`` so the two never
    drift; a destination the validator exempts (category ``None``) gets nothing.
    Destinations the validator does not govern (e.g. ``docs/prompts/**``) are returned
    unchanged. Applied on the fresh-carrier path only, so the update path is untouched.
    """

    if not (destination.startswith("docs/agents/") and destination.endswith(".md")):
        return content
    # Local import: defer the wave_lint_lib edge to call time so module load stays
    # decoupled across the setup/upgrade/hook subprocess contexts that run rendering.
    from wave_lint_lib.wave_validators import _expected_agent_category

    dest = Path(destination)
    category = _expected_agent_category(dest)
    if category is None:
        return content
    needed: list[str] = []
    if not _AGENT_ROLE_LINE_RE.search(content):
        needed.append(f"Role: {dest.stem}")
    if not _AGENT_CATEGORY_LINE_RE.search(content):
        needed.append(f"Category: {category}")
    if not needed:
        return content
    block = "\n".join(needed)
    status_match = re.search(r"^Status:.*$", content, re.MULTILINE)
    if status_match:
        idx = status_match.end()
        return content[:idx] + "\n" + block + content[idx:]
    heading_match = re.search(r"^#\s.*$", content, re.MULTILINE)
    if heading_match:
        idx = heading_match.end()
        return content[:idx] + "\n\n" + block + content[idx:]
    return block + "\n\n" + content


def _contained_review_carrier_path(repo_root: Path, destination: str) -> Path:
    """Resolve one registered carrier and refuse writes outside ``repo_root``.

    Carrier destinations are fixed by the typed registry, but an existing
    repository can place a symlink at the destination or in one of its parent
    directories.  Setup, upgrade, and direct rendering must not follow that
    repository-controlled path into a sibling directory.  Returning the
    resolved path also prevents a later open from re-following the symlink
    chain that was checked here.
    """

    root = repo_root.resolve()
    candidate = repo_root / destination
    try:
        resolved = candidate.resolve(strict=False)
    except OSError as exc:
        raise RuntimeError(
            f"review carrier path cannot be resolved safely: {destination}: {exc}"
        ) from exc
    if not resolved.is_relative_to(root):
        raise RuntimeError(
            "review carrier path escapes the repository root through a symlink: "
            f"{destination}"
        )
    return resolved


def _write_review_carrier_text(path: Path, content: str) -> None:
    """Write a checked carrier without following a raced final symlink."""

    path.parent.mkdir(parents=True, exist_ok=True)
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    try:
        fd = os.open(path, flags, 0o666)
    except OSError as exc:
        raise RuntimeError(f"review carrier write refused for {path}: {exc}") from exc
    with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
        handle.write(content)


def _agent_surface_output_destinations(repo_root: Path) -> list[str]:
    """Return every non-registry agent destination this pass may write.

    Skill paths are not listed here: the skill registry pass owns them and
    reports its own destinations via ``_skill_output_destinations`` (which the
    preflight consults regardless of Guru availability).
    """

    if not guru_available(repo_root):
        return []
    destinations: list[str] = []
    if (repo_root / ".cursor").exists():
        destinations.append(".cursor/rules/auto-guru.mdc")
    if (repo_root / ".claude").exists():
        destinations.append(".claude/agents/guru.md")
    for optional in (
        "CLAUDE.md",
        ".junie/guidelines.md",
        "WARP.md",
        ".github/copilot-instructions.md",
        ".cursor/rules/project-context.mdc",
    ):
        if (repo_root / optional).is_file():
            destinations.append(optional)
    return destinations


def preflight_agent_surface_paths(repo_root: Path) -> None:
    """Refuse every registered/native agent escape before the first write."""

    destinations = [
        *(carrier.destination for carrier in review_protocol_carriers(repo_root)),
        *(destination for destination, _template in LIFECYCLE_PROMPT_BASELINES),
        *(destination for destination, _template in SCAFFOLD_BASELINES),
        UPGRADE_POLICY_DESTINATION,
        *_agent_surface_output_destinations(repo_root),
        *_skill_output_destinations(repo_root),
    ]
    for destination in dict.fromkeys(destinations):
        _contained_review_carrier_path(repo_root, destination)


def reconcile_review_protocol_surfaces(repo_root: Path) -> list[str]:
    """Reconcile framework-owned protocol regions without replacing project prose.

    The public setup/upgrade renderer materializes missing canonical minimums
    for enabled framework carriers and repairs their protocol section. Guru,
    repo-local reviewers, and native wrappers remain explicitly existing-only
    so rendering cannot silently enable optional capabilities. A malformed
    marker pair fails safe and leaves the file untouched with a loud diagnostic.
    """

    carriers = review_protocol_carriers(repo_root)
    preflight_agent_surface_paths(repo_root)
    written: list[str] = []
    for carrier in carriers:
        path = _contained_review_carrier_path(repo_root, carrier.destination)
        if not path.is_file():
            if carrier.conditional_existing or not carrier.create_if_missing:
                continue
            original = _initial_review_carrier_text(repo_root, carrier)
            # Fresh-only: guarantee a docs/agents/** carrier carries the Role:/Category:
            # frontmatter the pack's own docs-lint requires, even if the seed omits it.
            original = _ensure_agent_frontmatter(original, carrier.destination)
        else:
            with path.open("r", encoding="utf-8", newline="") as handle:
                original = handle.read()
        updated = _upsert_review_protocol_region(original, _carrier_protocol_block(carrier))
        if updated is None:
            print(
                "render_agent_surfaces: WARNING — left "
                f"{path} unchanged (malformed executable-review-evidence markers)",
                file=sys.stderr,
            )
            continue
        if updated != original:
            _write_review_carrier_text(path, updated)
            written.append(carrier.destination)
    return written


def review_protocol_carriers_skipped_by_render(repo_root: Path) -> list[str]:
    """Return the carriers ``reconcile_review_protocol_surfaces`` would SKIP.

    1v4mt: the upgrade summary reports this class, and it cannot reach the
    docs-lint validator that gates it. ``upgrade_wavefoundry`` is a mandatory
    feature module under ``upgrade_protocol``, whose ``_validate_imports``
    admits only top-level pack modules; ``wave_lint_lib`` is a package and is
    deliberately not importable from there, so the bridge bundle can run on its
    own. Rather than obfuscate that import, the summary derives the finding from
    this module, which the protocol does admit.

    The DISPOSITION is still defined in exactly one place: a carrier is skipped
    precisely when ``_upsert_review_protocol_region`` returns ``None``, the same
    call the reconciler and the gate both make. Only the drift half of the
    gate's judgment is absent here, and deliberately: a drifted region is
    re-rendered by the run rather than skipped by it.
    """

    skipped: list[str] = []
    for carrier in review_protocol_carriers(repo_root):
        path = _contained_review_carrier_path(repo_root, carrier.destination)
        if not path.is_file():
            continue
        try:
            with path.open("r", encoding="utf-8", newline="") as handle:
                text = handle.read()
        except (OSError, UnicodeError):
            continue
        if (
            REVIEW_PROTOCOL_MARKER_BEGIN not in text
            and REVIEW_PROTOCOL_MARKER_END not in text
        ):
            continue
        if _upsert_review_protocol_region(text, _carrier_protocol_block(carrier)) is None:
            skipped.append(carrier.destination)
    return list(dict.fromkeys(skipped))


def reconcile_lifecycle_prompt_baselines(repo_root: Path) -> list[str]:
    """Materialize missing lifecycle baselines without replacing project prose."""

    written: list[str] = []
    template_root = (
        repo_root
        / ".wavefoundry"
        / "framework"
        / "install"
        / "lifecycle-prompts"
    )
    if not template_root.is_dir():
        # Public setup may execute the framework checkout's renderer against a
        # different target root. The templates are packaged beside this module,
        # so use that canonical artifact source until extraction has populated
        # the target's identical copy.
        template_root = (
            Path(__file__).resolve().parent.parent
            / "install"
            / "lifecycle-prompts"
        )
    today = time.strftime("%Y-%m-%d")
    for destination, template_name in LIFECYCLE_PROMPT_BASELINES:
        path = _contained_review_carrier_path(repo_root, destination)
        if path.is_file():
            continue
        template = template_root / template_name
        if not template.is_file():
            raise RuntimeError(
                "missing lifecycle prompt baseline: "
                f"{template.as_posix()}"
            )
        with template.open("r", encoding="utf-8", newline="") as handle:
            # Wave 1viyu (CODE-DEL-1): the shipped baselines carry a
            # `Last verified: {{generated_at}}` placeholder so a freshly
            # materialized carrier satisfies `check_metadata` on the first
            # docs-lint pass; stamp it exactly as the scaffold baselines do.
            content = handle.read().replace("{{generated_at}}", today)
        _write_review_carrier_text(path, content)
        written.append(destination)
    return written


def _resolve_install_asset(repo_root: Path, template_name: str) -> Path:
    """Resolve one install asset per file, target first then packaged module."""

    target = repo_root / ".wavefoundry" / "framework" / "install" / template_name
    if target.is_file():
        return target
    packaged = Path(__file__).resolve().parent.parent / "install" / template_name
    if packaged.is_file():
        return packaged
    raise RuntimeError(
        f"missing install scaffold baseline: expected {target.as_posix()} "
        f"or packaged fallback {packaged.as_posix()}"
    )


def reconcile_scaffold_baselines(repo_root: Path) -> list[str]:
    """Materialize missing project scaffolds without replacing operator copies."""

    written: list[str] = []
    today = time.strftime("%Y-%m-%d")
    for destination, template_name in SCAFFOLD_BASELINES:
        path = _contained_review_carrier_path(repo_root, destination)
        if path.is_file():
            continue
        template = _resolve_install_asset(repo_root, template_name)
        with template.open("r", encoding="utf-8", newline="") as handle:
            content = handle.read().replace("{{generated_at}}", today)
        _write_review_carrier_text(path, content)
        written.append(destination)
    return written


def reconcile_review_policy_surfaces(repo_root: Path) -> list[str]:
    """Render the policy registry's lifecycle obligations into owned regions."""

    written: list[str] = []
    for carrier in REVIEW_POLICY_CARRIER_REGISTRY:
        block = REVIEW_POLICY_SURFACE_BLOCKS.get(carrier.destination)
        if carrier.owner != "renderer" or block is None:
            continue
        path = _contained_review_carrier_path(repo_root, carrier.destination)
        if not path.is_file():
            if carrier.conditional_existing or not carrier.create_if_missing:
                continue
            raise RuntimeError(
                f"missing review-policy lifecycle carrier: {carrier.destination}"
            )
        with path.open("r", encoding="utf-8", newline="") as handle:
            original = handle.read()
        updated = _upsert_review_policy_region(original, block)
        if updated is None:
            print(
                "render_agent_surfaces: WARNING — left "
                f"{path} unchanged (malformed review-policy markers)",
                file=sys.stderr,
            )
            continue
        if updated != original:
            _write_review_carrier_text(path, updated)
            written.append(carrier.destination)
    return written


def reconcile_context_efficiency_surface(repo_root: Path) -> list[str]:
    """Reconcile the Create-wave telemetry carrier without replacing project prose."""

    path = _contained_review_carrier_path(repo_root, CONTEXT_EFFICIENCY_DESTINATION)
    if not path.is_file():
        carrier = next(
            row
            for row in REVIEW_PROTOCOL_CARRIER_REGISTRY
            if row.destination == CONTEXT_EFFICIENCY_DESTINATION
        )
        original = _initial_review_carrier_text(repo_root, carrier)
    else:
        with path.open("r", encoding="utf-8", newline="") as handle:
            original = handle.read()
    _context_efficiency_carrier_block()
    try:
        updated = _replace_context_efficiency_carrier_block(original)
    except ValueError:
        print(
            "render_agent_surfaces: WARNING — left "
            f"{path} unchanged (malformed context-efficiency markers)",
            file=sys.stderr,
        )
        return []
    if updated == original:
        return []
    _write_review_carrier_text(path, updated)
    return [CONTEXT_EFFICIENCY_DESTINATION]


def render_agent_surfaces(repo_root: Path) -> list[str]:
    """Render auto-Guru tier 2–3 surfaces. Returns paths written or updated."""
    # Wave 1skt1: this must run before the historical Guru-availability early
    # return so setup/upgrade/render can repair review carriers in repositories
    # that intentionally do not expose Guru.
    preflight_agent_surface_paths(repo_root)
    # Wave 1p6lp: the skill registry renders BEFORE the reconcile passes so a
    # freshly migrated carrier skill (wf-guru on Codex) is reconciled in the
    # same render, and BEFORE the Guru gate because lifecycle skills are not
    # Guru-gated (per-skill gates live in the registry).
    skills_written = render_skills(repo_root)
    lifecycle_written = reconcile_lifecycle_prompt_baselines(repo_root)
    scaffold_written = reconcile_scaffold_baselines(repo_root)
    # The phase-0c in-process reconciler can still be old code on the upgrade
    # that installs this release. Replay only its shared upgrade-policy marker
    # from the extracted renderer so this one surface converges in that run.
    try:
        upgrade_policy_written = list(reconcile_upgrade_policy_surface(repo_root))
    except ValueError as exc:
        raise RuntimeError(str(exc)) from exc
    review_written = reconcile_review_protocol_surfaces(repo_root)
    # Policy companions include optional carriers materialized by the review
    # protocol pass (for example the agent and council review prompts). Run
    # policy second so one render converges from a sparse pre-adoption tree.
    policy_written = reconcile_review_policy_surfaces(repo_root)
    context_written = reconcile_context_efficiency_surface(repo_root)
    framework_written = list(
        dict.fromkeys(
            [
                *skills_written,
                *lifecycle_written,
                *scaffold_written,
                *upgrade_policy_written,
                *review_written,
                *policy_written,
                *context_written,
            ]
        )
    )
    if not guru_available(repo_root):
        return framework_written

    # Preflight every path this Guru-enabled pass may write before the first
    # native/thin-pointer mutation.  The initial carrier census intentionally
    # ignores a missing native wrapper, so a symlinked wrapper directory with
    # no leaf file would otherwise escape during materialization and be noticed
    # only by the second carrier reconciliation.
    preflight_agent_surface_paths(repo_root)

    written: list[str] = list(framework_written)

    # Wave 1t72b (1t729 live find): tier-3 templates are written unconditionally
    # and then RECONCILED by the closing carrier pass, so write-time comparison
    # oscillates (template != reconciled bytes every render). "Written" for the
    # manifest means NET change across the whole render: snapshot pre-render
    # bytes here, decide after the closing reconcile pass below.
    tier3_candidates: list[Path] = []
    tier3_pre_bytes: dict[Path, "bytes | None"] = {}

    def _tier3_write(path: Path, content: str) -> None:
        try:
            tier3_pre_bytes[path] = path.read_bytes() if path.exists() else None
        except OSError:
            tier3_pre_bytes[path] = None
        tier3_candidates.append(path)
        write_text(path, content)

    # Tier 3 — optional native surfaces
    if (repo_root / ".cursor").exists():
        cursor_rule = repo_root / ".cursor" / "rules" / "auto-guru.mdc"
        _tier3_write(cursor_rule, CURSOR_AUTO_GURU_MDC)

    if (repo_root / ".claude").exists():
        claude_agent = repo_root / ".claude" / "agents" / "guru.md"
        _tier3_write(claude_agent, CLAUDE_GURU_AGENT)

    # Wave 1p6lp: the Codex guru skill is registry-rendered (wf-guru) by
    # render_skills above; the ad-hoc CODEX_AUTO_GURU_SKILL write is retired.

    # Root @import bridge — make CLAUDE.md a real @AGENTS.md import (1p5xc).
    # The single, contained @import; replaces the prose "read AGENTS.md first"
    # pointer so AGENTS.md is the deterministic single source of truth.
    if patch_root_bridge(repo_root / "CLAUDE.md"):
        written.append("CLAUDE.md")

    # Tier 2 — thin pointers (marker blocks)
    claude_path = repo_root / "CLAUDE.md"
    if claude_path.is_file():
        claude_body = CLAUDE_AUTO_GURU_SECTION.strip()
        claude_block = f"{MARKER_BEGIN}\n{claude_body}\n{MARKER_END}"
        text = strip_legacy_auto_guru_lines(claude_path.read_text(encoding="utf-8"))
        if MARKER_BEGIN in text:
            text = re.sub(
                re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END),
                claude_block,
                text,
                count=1,
                flags=re.DOTALL,
            )
        else:
            # Replace legacy hand-authored section if present
            legacy = re.compile(
                r"\n## Code and documentation questions \(auto-Guru\)\n.*?(?=\n## |\Z)",
                re.DOTALL,
            )
            if legacy.search(text):
                text = legacy.sub("\n" + claude_block + "\n", text, count=1)
            else:
                text = insert_after_heading(text, "## Startup Order", claude_block)
        if text != claude_path.read_text(encoding="utf-8"):
            claude_path.write_text(text, encoding="utf-8")
            written.append("CLAUDE.md")

    pointer_specs: list[tuple[Path, str]] = [
        (repo_root / ".junie" / "guidelines.md", "## Key Rules"),
        (repo_root / "WARP.md", "## Key Rules"),
        (repo_root / ".github" / "copilot-instructions.md", "## Key Guardrails"),
    ]
    for path, heading in pointer_specs:
        if patch_thin_pointer(path, AUTO_GURU_BULLET, after_heading=heading):
            written.append(path.relative_to(repo_root).as_posix())  # Wave 1p6dx: forward-slash

    cursor_ctx = repo_root / ".cursor" / "rules" / "project-context.mdc"
    if cursor_ctx.is_file():
        text = strip_legacy_auto_guru_section(
            strip_legacy_auto_guru_lines(cursor_ctx.read_text(encoding="utf-8"))
        )
        updated = upsert_marked_region(text, CURSOR_PROJECT_CONTEXT_BLOCK.strip())
        if updated != cursor_ctx.read_text(encoding="utf-8"):
            cursor_ctx.write_text(updated, encoding="utf-8")
            written.append(cursor_ctx.relative_to(repo_root).as_posix())  # Wave 1p6dx: forward-slash

    # Native Guru wrappers are materialized above, after the initial carrier
    # census. Reconcile again so the first public render gives them the same
    # protocol minimum and later renders cannot overwrite it away.
    reconciled_again = reconcile_review_protocol_surfaces(repo_root)

    # Net-change decision for the tier-3 candidates: a file whose final
    # post-reconcile bytes equal its pre-render bytes was not written in any
    # sense the manifest should report.
    for path in tier3_candidates:
        try:
            post = path.read_bytes() if path.exists() else None
        except OSError:
            continue
        if post != tier3_pre_bytes.get(path):
            written.append(path.relative_to(repo_root).as_posix())  # Wave 1p6dx: forward-slash

    # The closing reconcile pass legitimately rewrites tier-3 templates back to
    # their reconciled form every render; those paths' NET verdict was already
    # decided above, so only non-candidate carriers merge from its return.
    tier3_rels = {
        path.relative_to(repo_root).as_posix() for path in tier3_candidates
    }
    for rel in reconciled_again:
        if rel not in written and rel not in tier3_rels:
            written.append(rel)

    # Dedupe while preserving order (CLAUDE.md may be touched by both the
    # root-bridge step and the auto-Guru tier-2 step).
    deduped: list[str] = []
    for rel in written:
        if rel not in deduped:
            deduped.append(rel)
    return deduped


def main() -> int:
    import argparse
    import sys

    from render_platform_surfaces import discover_repo_root

    parser = argparse.ArgumentParser(description="Render auto-Guru agent routing surfaces.")
    parser.add_argument("--repo-root", default="", help="Repository root (default: auto-discover).")
    args = parser.parse_args()
    repo_root = Path(args.repo_root).resolve() if args.repo_root else discover_repo_root()
    try:
        paths = render_agent_surfaces(repo_root)
    except RuntimeError as exc:
        print(f"render_agent_surfaces: ERROR — {exc}", file=sys.stderr)
        return 1
    if not paths:
        if not guru_available(repo_root):
            print(f"skip: {GURU_ROLE_REL} not found", file=sys.stderr)
        return 0
    for rel in paths:
        print(rel)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
