#!/usr/bin/env python3
"""Render agent routing surfaces (auto-Guru tier 2–3) for Wave Framework hosts."""

from __future__ import annotations

import copy
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent

MARKER_BEGIN = "<!-- waveframework:auto-guru begin — generated by render_agent_surfaces.py; do not edit -->"
MARKER_END = "<!-- waveframework:auto-guru end -->"

# Root @AGENTS.md import bridge (wave 1p5xc). The ONLY @import the framework
# adopts, and only at the root: it makes the root AGENTS.md the single source of
# truth Claude loads deterministically, while AGENTS.md-native agents read it
# directly. No per-folder bridge files, no nested @import.
ROOT_BRIDGE_MARKER_BEGIN = "<!-- waveframework:root-bridge begin — generated by render_agent_surfaces.py; do not edit -->"
ROOT_BRIDGE_MARKER_END = "<!-- waveframework:root-bridge end -->"
ROOT_BRIDGE_BLOCK = (
    f"{ROOT_BRIDGE_MARKER_BEGIN}\n"
    "@AGENTS.md\n"
    f"{ROOT_BRIDGE_MARKER_END}"
)
# The legacy prose pointer this bridge replaces.
_LEGACY_THIN_POINTER_RE = re.compile(
    r"^Thin pointer\. Read `AGENTS\.md` first[^\n]*\n",
    re.MULTILINE,
)

GURU_ROLE_REL = "docs/agents/guru.md"


@dataclass(frozen=True)
class ReviewProtocolCarrier:
    """One framework-owned review-protocol destination.

    ``conditional_existing`` is reserved for repo-local reviewers whose role
    documents are intentionally project-defined.  The reconciler updates
    those files only when the project has enabled them by creating the file.
    """

    source_seed: str
    destination: str
    conditional_existing: bool = False
    create_if_missing: bool = True


# Wave 1skt1: one typed source of truth for the finite canonical carrier set.
# Tests and reconciliation both derive from this registry; do not maintain a
# second hand-written destination list.
REVIEW_PROTOCOL_CARRIER_REGISTRY: tuple[ReviewProtocolCarrier, ...] = (
    # Guru is an optional capability: do not enable it merely by rendering
    # protocol carriers.  When present, it is still reconciled normally.
    ReviewProtocolCarrier("211-guru.prompt.md", "docs/agents/guru.md", create_if_missing=False),
    ReviewProtocolCarrier("239-qa-reviewer.prompt.md", "docs/agents/qa-reviewer.md"),
    ReviewProtocolCarrier("214-architecture-reviewer.prompt.md", "docs/agents/architecture-reviewer.md"),
    ReviewProtocolCarrier("212-performance-reviewer.prompt.md", "docs/agents/performance-reviewer.md"),
    ReviewProtocolCarrier("221-code-reviewer.prompt.md", "docs/agents/code-reviewer.md"),
    ReviewProtocolCarrier("213-security-reviewer.prompt.md", "docs/agents/security-reviewer.md"),
    ReviewProtocolCarrier("050-agent-entry-surface-bootstrap.prompt.md", "docs/agents/docs-contract-reviewer.md", True, False),
    ReviewProtocolCarrier("050-agent-entry-surface-bootstrap.prompt.md", "docs/agents/release-reviewer.md", True, False),
    ReviewProtocolCarrier("225-red-team.prompt.md", "docs/agents/specialists/red-team.md"),
    ReviewProtocolCarrier("216-reality-checker.prompt.md", "docs/agents/specialists/reality-checker.md"),
    ReviewProtocolCarrier("215-wave-council.prompt.md", "docs/agents/specialists/wave-council.md"),
    ReviewProtocolCarrier("236-archetype-council.prompt.md", "docs/agents/specialists/archetype-council.md"),
    ReviewProtocolCarrier("217-senior-engineering-challenger.prompt.md", "docs/agents/specialists/senior-engineering-challenger.md"),
    ReviewProtocolCarrier("236-archetype-council.prompt.md", "docs/prompts/archetype-council.prompt.md"),
    ReviewProtocolCarrier("237-council-review.prompt.md", "docs/prompts/council-review.prompt.md"),
    ReviewProtocolCarrier("100-project-prompt-surface-bootstrap.prompt.md", "docs/prompts/review-wave.prompt.md"),
    ReviewProtocolCarrier("100-project-prompt-surface-bootstrap.prompt.md", "docs/prompts/agents/review-wave.prompt.md"),
    ReviewProtocolCarrier("100-project-prompt-surface-bootstrap.prompt.md", "docs/prompts/create-wave.prompt.md"),
    ReviewProtocolCarrier("209-agent-harness-core.prompt.md", "docs/contributing/review-and-evals.md"),
)

REVIEW_PROTOCOL_CARRIER_MANIFEST: tuple[str, ...] = tuple(
    carrier.destination for carrier in REVIEW_PROTOCOL_CARRIER_REGISTRY
)

REVIEW_PROTOCOL_MARKER_BEGIN = (
    "<!-- waveframework:executable-review-evidence begin — generated by "
    "render_agent_surfaces.py; preserve project-authored content outside this region -->"
)
REVIEW_PROTOCOL_MARKER_END = "<!-- waveframework:executable-review-evidence end -->"
REVIEW_PROTOCOL_CARRIER_BLOCK = dedent(
    """\
    ## Executable review evidence

    Follow the canonical **Executable Review Evidence Protocol** in
    `.wavefoundry/framework/seeds/209-agent-harness-core.prompt.md` for material
    approval claims and blocking findings. Exercise the public or registered
    path when one exists; keep state/interleaving probes within the protocol's
    finite risk-selected budget; record expected versus observed evidence and
    honest limitations; and never broaden task authority to run destructive,
    external, credential-bearing, or cost-bearing probes.

    Do not hand-author canonical JSONL when the lifecycle coordinator exposes
    the typed review-evidence authoring surface. Reviewers supply the
    load-bearing judgment facts to that coordinator; the authoring surface
    derives only bookkeeping, appends the fixed sibling
    `docs/waves/<wave>/events.jsonl` authority, and rebuilds the compact
    Markdown current-state projection in `wave.md`. A role without lifecycle
    mutation authority returns those facts to its coordinator instead of
    writing wave state.

    After validation, apply the ordered four-way actionability gate:
    `do_now`, `maybe_later`, `dont_do_later`, or `not_issue`. Complete bounded
    `do_now`/`maybe_later` work before closure, create no backlog for rejected
    states, and use focused repair replay unless a load-bearing boundary change
    objectively requires a full council.
    """
).strip()

INDEPENDENT_REFERENCE_CARRIER_BLOCK = dedent(
    """\
    ### Independent-reference verification

    For any changed implementation — feature, API or tool-surface change,
    config-driven change, bug fix, or deterministic mechanism — apply seed
    209's independent-reference rule: verify against a reference that does not
    share the implementation's assumptions (a specification, the
    independently-read acceptance criteria, the consumer/caller contract, the
    original reproduction, a materially independent implementation, a
    schema/model, or a metamorphic invariant). Name the reference, exact
    promised property, and common-mode limitations; keep one highest-risk probe
    bounded, reproducible, and limited to valid inputs and the public contract
    surface. A same-hypothesis helper or agent brief is not an independent
    reference, and implementer-authored evidence remains `independent: false`.

    Code review identifies the applicable reference and property. QA names the
    assertion that would falsify each load-bearing correctness, complexity,
    compatibility, or parity claim. Carrier-presence tests prove propagation,
    not reviewer adherence.
    """
).strip()


def _review_role_slug(carrier: ReviewProtocolCarrier) -> str | None:
    path = Path(carrier.destination)
    if path.suffix != ".md" or tuple(path.parts[:2]) != ("docs", "agents"):
        return None
    if "journals" in path.parts or "memory" in path.parts or "personas" in path.parts:
        return None
    return path.stem


def review_protocol_carriers(repo_root: Path | None = None) -> tuple[ReviewProtocolCarrier, ...]:
    """Return canonical carriers plus explicitly enabled native role wrappers.

    Native wrappers are enabled by their on-disk presence and are derived only
    from a registered canonical role.  An arbitrary wrapper therefore cannot
    opt itself into framework ownership merely by matching a directory glob.
    """

    carriers = list(REVIEW_PROTOCOL_CARRIER_REGISTRY)
    if repo_root is None:
        return tuple(carriers)
    seen = {carrier.destination for carrier in carriers}
    for carrier in REVIEW_PROTOCOL_CARRIER_REGISTRY:
        role = _review_role_slug(carrier)
        if role is None:
            continue
        candidates = (
            f".claude/agents/{role}.md",
            f".codex/skills/agent-role-{role}/SKILL.md",
        ) + ((".codex/skills/auto-guru/SKILL.md",) if role == "guru" else ())
        for destination in candidates:
            if destination in seen or not (repo_root / destination).is_file():
                continue
            carriers.append(
                ReviewProtocolCarrier(carrier.source_seed, destination, conditional_existing=True)
            )
            seen.add(destination)
    return tuple(carriers)


def review_protocol_carrier_manifest(repo_root: Path | None = None) -> tuple[str, ...]:
    return tuple(carrier.destination for carrier in review_protocol_carriers(repo_root))

AUTO_GURU_BULLET = (
    "- Code and documentation Q&A: follow **Codebase and documentation questions (auto-Guru)** "
    "in `AGENTS.md` and `docs/agents/guru.md`; use Wavefoundry MCP (`code_ask`, `docs_search`) "
    "when attached; do not answer from memory alone."
)

CURSOR_AUTO_GURU_MDC = dedent(
    """\
    ---
    description: Auto-route code and documentation questions to Guru (code_ask, docs_search, validated reads)
    globs: ["**/*"]
    alwaysApply: true
    ---

    # Auto-Guru (Cursor — optional native surface)

    Canonical rules for **all** agent hosts: `AGENTS.md` § **Codebase and documentation questions (auto-Guru)** and `docs/agents/guru.md`. This file is a Cursor-specific reinforcement of that contract.

    Applies to every chat in this workspace unless the user is invoking a **wave lifecycle** command from `docs/prompts/index.md` (**Plan feature**, **Implement wave**, **Close wave**, etc.).

    ## When this rule applies

    Treat the message as **Guru work** when the user is asking to **understand, locate, or explain** repository **source code** or **project documentation** (including `docs/architecture/`, `docs/specs/`, framework scripts, seeds, and MCP/index behavior).

    ## Required workflow

    1. Read `AGENTS.md` § **Codebase and documentation questions (auto-Guru)** and `docs/agents/guru.md`.
    2. Call Wavefoundry MCP **`code_ask`** and/or **`docs_search`** before synthesizing (server: `.cursor/mcp.json` → `wavefoundry`).
    3. Complete Guru **Pass 3** (`code_outline`, targeted `code_read`, `code_keyword`) — never answer from the `code_ask` `answer` field or memory alone.
    4. For deep technical pipelines, follow Guru **architecture write-up escalation** (architecture-reviewer + council when enabled).

    ## Cursor-specific delegation

    - Prefer MCP tools over raw `grep`/`read` for orientation when the index is healthy (`wave_index_health`).
    - For large investigations, use a **read-only subagent** (Task) with `docs/agents/guru.md` as the prompt and return cited findings to the parent thread.
    - Operators do **not** need to say **Guru**; the explicit shortcut remains in `docs/prompts/index.md`.
    """
)

CLAUDE_AUTO_GURU_SECTION = dedent(
    """\
    ## Code and documentation questions (auto-Guru)

    - Follow **Codebase and documentation questions (auto-Guru)** in `AGENTS.md` and `docs/agents/guru.md`.
    - **Delegate** code/doc Q&A to the **`guru`** subagent (`.claude/agents/guru.md`) when the investigation is large or would flood the main thread — Claude selects it automatically from the subagent `description` when appropriate.
    - Use **wavefoundry** MCP (`code_ask`, `docs_search`) when attached (`.mcp.json` at repo root).
    """
)

CURSOR_PROJECT_CONTEXT_BLOCK = dedent(
    """\
    ## Code and documentation questions (auto-Guru)

    Follow **`.cursor/rules/auto-guru.mdc`** (always-on Guru routing for code and doc Q&A).
    """
)

CLAUDE_GURU_AGENT = dedent(
    """\
    ---
    name: guru
    description: PROACTIVELY use when the user asks how this repository's source code or project documentation works — behavior, architecture, specs, framework scripts, indexing, chunking, retrieval, or where to find implementation. Do not use for wave lifecycle commands (Plan feature, Implement wave, Close wave, Prepare wave, etc.).
    tools: Read, Grep, Glob, Bash, ToolSearch, mcp__wavefoundry__code_ask, mcp__wavefoundry__code_search, mcp__wavefoundry__code_keyword, mcp__wavefoundry__code_lexical, mcp__wavefoundry__code_read, mcp__wavefoundry__code_outline, mcp__wavefoundry__code_definition, mcp__wavefoundry__code_references, mcp__wavefoundry__code_callhierarchy, mcp__wavefoundry__code_dependencies, mcp__wavefoundry__code_impact, mcp__wavefoundry__code_list_files, mcp__wavefoundry__code_constants, mcp__wavefoundry__code_pattern, mcp__wavefoundry__code_callgraph, mcp__wavefoundry__code_graph_path, mcp__wavefoundry__code_graph_community, mcp__wavefoundry__docs_search, mcp__wavefoundry__seed_get
    model: sonnet
    ---

    # Guru (Claude Code subagent — optional native surface)

    Canonical role for **all** hosts: `docs/agents/guru.md` and `AGENTS.md` § **Codebase and documentation questions (auto-Guru)**.

    ## Your job

    Answer code and documentation questions with **indexed, cited evidence** — not memory.

    1. Follow the retrieval loop, mechanism completeness, and citation rules in `docs/agents/guru.md`.
    2. Use the **wavefoundry** MCP server when attached: `code_ask`, `docs_search`, `code_search`, `code_outline`, `code_read`, `code_keyword`, `code_definition`, `code_references`, `code_dependencies`. Load and prefer these over `grep`/`Read` for locating and understanding code; when your host defers MCP tool schemas, load them once via `ToolSearch` (e.g. `select:mcp__wavefoundry__code_ask,mcp__wavefoundry__code_references`) before falling back to shell.
    3. Treat `code_ask` `answer` as a navigation pointer only; validate with Pass 3 reads before responding.
    4. Return a complete answer with file:line citations and a short list of files/ranges you read.

    ## Boundaries

    - Read-only in this subagent — do not edit source, seeds, or wave records here.
    - Architecture doc drafts and journal writes belong in the main session per `docs/agents/guru.md` write permissions.
    - Wave lifecycle execution stays with the main agent / wave-coordinator prompts.
    """
)

CODEX_AUTO_GURU_SKILL = dedent(
    """\
    ---
    name: auto-guru
    description: PROACTIVELY use when the user asks how repository source code or project documentation works — locating behavior, explaining pipelines, architecture, specs, framework scripts, indexing, chunking, retrieval, or MCP tools. Not for wave lifecycle commands (Plan feature, Implement wave, Close wave, etc.).
    ---

    # Auto-Guru (Codex skill — optional native surface)

    Canonical rules for **all** hosts: `AGENTS.md` § **Codebase and documentation questions (auto-Guru)** and `docs/agents/guru.md`.

    ## Trigger

    Use this skill for **code** and **documentation** Q&A. Skip when the user is running a wave lifecycle shortcut from `docs/prompts/index.md`.

    ## Instructions

    1. Read `AGENTS.md` § **Codebase and documentation questions (auto-Guru)**.
    2. Read and follow `docs/agents/guru.md` (classification, retrieval loop, Pass 3, citations).
    3. MCP server loads automatically from the committed `.codex/config.toml`; attach the `wavefoundry` server from the project-local config.
    4. Prefer **`code_ask`** and **`docs_search`** over ad-hoc search when MCP is available.
    5. Complete Pass 3 validation before answering; never paraphrase only the `code_ask` `answer` field.

    ## Codex notes

    - Operators do not need to say **Guru**; this skill is the default path for code/doc questions.
    - Explicit shortcut **Guru** remains in `docs/prompts/index.md`.
    """
)

CODEX_MCP_CONFIG_TOML = dedent(
    """\
    [mcp_servers.wavefoundry]
    command = "python3"
    args = [".wavefoundry/framework/scripts/server.py"]
    """
)

# Wave 1p9pe (renderer-overwrite-safety): `.codex/config.toml` is an
# operator-extensible surface (approval modes, tool policy, other MCP servers).
# The renderer owns ONLY the marked region below; everything outside it is
# operator-owned and must survive every render byte-for-byte. TOML `#` comment
# markers mirror the markdown MARKER_BEGIN/MARKER_END precedent.
CODEX_CONFIG_MARKER_BEGIN = (
    "# waveframework:codex-mcp begin — generated by render_agent_surfaces.py; "
    "do not edit inside this region; add operator config outside it"
)
CODEX_CONFIG_MARKER_END = "# waveframework:codex-mcp end"

_CODEX_FRAMEWORK_KEYS = ("command", "args")

# Review-fix (1p9pe follow-up hardening): line-anchored marker-region match.
# Both markers must sit on their own lines (they are TOML comments) — a marker
# string embedded inside an operator string value must never select the
# replace-region branch, or the substitution would slice through the string.
# The line tails tolerate a trailing \r so a CRLF-rewritten config (editor or
# tooling re-encoded the file) still matches its marker region and gets a
# fresh framework block instead of perpetually fail-safing with a stale one.
_CODEX_MARKER_REGION_RE = re.compile(
    "^"
    + re.escape(CODEX_CONFIG_MARKER_BEGIN)
    + r"[ \t\r]*\n.*?^"
    + re.escape(CODEX_CONFIG_MARKER_END)
    + r"[ \t\r]*(?:\n|\Z)",
    re.MULTILINE | re.DOTALL,
)

# Review-fix: the unmarked-table migration must accept the TOML-equivalent
# header spellings — quoted keys ([mcp_servers."wavefoundry"]) and whitespace
# around the dot / inside the brackets — so those shapes MIGRATE instead of
# being re-declared by the append branch (a duplicate table is invalid TOML).
_CODEX_TABLE_HEADER_RE = re.compile(
    r"""^\[\s*(?:mcp_servers|"mcp_servers"|'mcp_servers')\s*\.\s*"""
    r"""(?:wavefoundry|"wavefoundry"|'wavefoundry')\s*\]\s*$"""
)

# Review-fix: hard bound on multi-line value absorption. The framework template
# has only ever emitted one-line values; a continuation run longer than this is
# a bracket-count desync (e.g. an unbalanced "[" inside an operator-edited
# string), and absorbing further would eat operator content.
_CODEX_ABSORB_MAX_VALUE_LINES = 10


def _codex_value_bracket_delta(fragment: str) -> int:
    """Net bracket-nesting delta for a TOML value fragment.

    Used only to absorb multi-line ``command``/``args`` values during the
    one-time unmarked-table migration. Plain counting cannot see string
    boundaries, so an unbalanced bracket INSIDE a string desyncs the count —
    ``upsert_codex_mcp_config`` guards that with the continuation-line cap
    and the end-of-absorption ``value_depth != 0`` fail-safe.
    """
    return (
        fragment.count("[")
        + fragment.count("{")
        - fragment.count("]")
        - fragment.count("}")
    )


def _codex_marker_in_multiline_string(value) -> bool:
    """True if any string in a parsed TOML value tree embeds a marker line.

    A MULTILINE operator string (triple-quoted) whose body reproduces a marker
    comment as a whole physical line defeats the line-anchored region regex:
    the region replace would slice through the string, and the sliced result
    can still parse, so a parse check alone is blind to the loss. Legitimate
    marked regions keep marker text only in TOML comment lines — which the
    parser drops — so marker text inside a PARSED string value that spans
    lines is always an embedding and no rewrite is safe. Single-line strings
    cannot line-anchor the regex (their opening quote precedes the marker on
    the physical line) and are tolerated.
    """
    if isinstance(value, str):
        return "\n" in value and (
            CODEX_CONFIG_MARKER_BEGIN in value or CODEX_CONFIG_MARKER_END in value
        )
    if isinstance(value, dict):
        return any(_codex_marker_in_multiline_string(item) for item in value.values())
    if isinstance(value, list):
        return any(_codex_marker_in_multiline_string(item) for item in value)
    return False


def _codex_normalized_doc(doc: dict) -> dict:
    """Normalize a parsed config for the semantic-equivalence exit guard.

    Strips exactly the differences a legitimate upsert makes — the framework-
    owned ``command``/``args`` keys of ``[mcp_servers.wavefoundry]`` (refreshed
    to the current template) and the creation of that table (or its
    ``mcp_servers`` parent) where it was absent. Marker comments are invisible
    to the parser and need no tolerance. After normalization, ANY difference
    between the existing and candidate documents is operator-owned content the
    merge would corrupt — valid-TOML content loss a parse check cannot flag.
    """
    normalized = copy.deepcopy(doc)
    servers = normalized.get("mcp_servers")
    if isinstance(servers, dict):
        table = servers.get("wavefoundry")
        if isinstance(table, dict):
            table.pop("command", None)
            table.pop("args", None)
            if not table:
                del servers["wavefoundry"]
        if not servers:
            del normalized["mcp_servers"]
    return normalized


def upsert_codex_mcp_config(
    existing: str | None,
    on_fail_safe=None,
) -> str:
    """Return new `.codex/config.toml` content with the framework region upserted.

    Non-destructive by contract (AGENTS.md: "Never overwrite project-local
    customizations"):

    - No file / empty file: return just the marked framework region.
    - Marker region present (both markers on their own lines; CRLF line
      endings tolerated): replace only the region between them; all operator
      content outside survives byte-for-byte, and a re-render is idempotent.
    - Markers absent but an unmarked top-level ``[mcp_servers.wavefoundry]``
      table exists (pre-marker renders; TOML-equivalent quoted/whitespace
      header spellings included): one-time migration — absorb the contiguous
      framework-owned ``command``/``args`` lines into the marked region
      without duplicating the table. Because the markers are TOML comments,
      any operator-added keys left in place directly after the end marker
      still belong to ``[mcp_servers.wavefoundry]``.
    - Neither markers nor table: append the marked region after the operator
      content.

    Single-exit fail-safe (review hardening): every branch that MERGES with
    operator content computes a candidate that is validated before being
    returned — it must parse with ``tomllib`` AND be semantically equivalent
    to the parsed existing content after normalizing the framework-owned
    differences (see ``_codex_normalized_doc``). If validation fails — or the
    merge looks ambiguous up front (marker text outside a well-formed region
    or embedded in a multiline string value, bracket-depth desync, oversized
    absorption) — the existing content is returned unchanged (a stale
    framework block is recoverable; a corrupted operator config is not). When
    that happens the optional ``on_fail_safe(reason)`` callback is invoked so
    the caller can warn loudly and skip reporting the file as written. One
    deliberate exception to the validated exit: the no-existing-content branch
    returns the constant framework block directly — it is renderer-constant
    content with no operator merge, so there is nothing to corrupt.
    """

    def fail_safe(reason: str) -> str:
        if on_fail_safe is not None:
            on_fail_safe(reason)
        return existing if existing is not None else ""

    import tomllib

    block = (
        f"{CODEX_CONFIG_MARKER_BEGIN}\n"
        f"{CODEX_MCP_CONFIG_TOML.rstrip()}\n"
        f"{CODEX_CONFIG_MARKER_END}\n"
    )
    if existing is None or existing.strip() == "":
        # Unvalidated by design: constant framework content, no operator merge.
        return block

    # Parse the existing content once, up front. An unparseable operator file
    # (already broken before we arrived) keeps the historical branch behavior:
    # the string-embedding pre-check and the semantic-equivalence exit guard
    # below both require a parsed baseline and are skipped.
    existing_doc: dict | None = None
    try:
        existing_doc = tomllib.loads(existing)
    except Exception:
        existing_doc = None

    # Fail-safe BEFORE branch selection: a multiline operator string that
    # reproduces a marker comment as a whole physical line would match the
    # line-anchored region regex and slice the string — and the sliced result
    # can still parse, so only this structural check catches it early with a
    # precise reason (the equivalence exit guard is the backstop).
    if existing_doc is not None and _codex_marker_in_multiline_string(existing_doc):
        return fail_safe(
            "marker text found inside a multiline operator string value; "
            "region matching would slice the string — cannot upsert safely"
        )

    candidate: str
    region_match = _CODEX_MARKER_REGION_RE.search(existing)
    if region_match is not None:
        candidate = existing[: region_match.start()] + block + existing[region_match.end():]
    elif CODEX_CONFIG_MARKER_BEGIN in existing or CODEX_CONFIG_MARKER_END in existing:
        # Marker text exists but not as a well-formed whole-line region (e.g.
        # inside an operator string, or a half-deleted region). Any rewrite
        # here risks slicing operator content — leave the file alone.
        return fail_safe(
            "marker text present outside a well-formed marker region; "
            "cannot upsert safely"
        )
    else:
        lines = existing.splitlines(keepends=True)
        header_index = next(
            (
                index
                for index, line in enumerate(lines)
                if _CODEX_TABLE_HEADER_RE.match(line.strip())
            ),
            None,
        )
        if header_index is None:
            candidate = existing.rstrip("\n") + "\n\n" + block
        else:
            # One-time absorption of the unmarked framework table: consume the
            # header plus the contiguous run of framework-owned assignments
            # (with multi-line value continuations). Stop at the first
            # operator-authored line (comment, unknown key, blank-line-then-
            # next-table) so operator content — including subtables like
            # [mcp_servers.wavefoundry.tools.*] — stays in place.
            absorbed_end = header_index + 1
            index = header_index + 1
            value_depth = 0
            continuation_lines = 0
            while index < len(lines):
                stripped = lines[index].strip()
                if value_depth > 0:
                    continuation_lines += 1
                    if continuation_lines > _CODEX_ABSORB_MAX_VALUE_LINES:
                        return fail_safe(
                            "unmarked-table migration would absorb more than "
                            f"{_CODEX_ABSORB_MAX_VALUE_LINES} value-continuation "
                            "lines — likely a bracket-count desync"
                        )
                    value_depth += _codex_value_bracket_delta(stripped)
                    index += 1
                    absorbed_end = index
                    continue
                if stripped == "":
                    # Tentatively skip: absorbed only if more framework lines follow.
                    index += 1
                    continue
                key, separator, value = stripped.partition("=")
                if separator == "=" and key.strip().strip("\"'") in _CODEX_FRAMEWORK_KEYS:
                    value_depth = _codex_value_bracket_delta(value)
                    continuation_lines = 0
                    index += 1
                    absorbed_end = index
                    continue
                break
            if value_depth != 0:
                # Bracket depth never returned to zero: an unbalanced bracket
                # (typically inside an operator-modified string) desynced the
                # counter and absorption would silently eat operator content
                # — possibly producing VALID TOML the parse guard below cannot
                # flag. Fail safe instead.
                return fail_safe(
                    "unmarked-table migration ended with unbalanced bracket "
                    "depth — refusing to absorb (operator content would be lost)"
                )
            candidate = "".join(lines[:header_index] + [block] + lines[absorbed_end:])

    # Single exit: no merged content leaves this function unvalidated.
    try:
        candidate_doc = tomllib.loads(candidate)
    except Exception:
        # Never write a config Codex cannot parse. Leaving the file
        # untouched keeps the operator's working config; the framework
        # block simply stays stale until resolved manually.
        return fail_safe("merged result would not parse as TOML")
    # Semantic-equivalence guard: the parse check alone is blind to
    # valid-TOML content loss (an absorption desync or string slice can
    # eat operator content and still produce parseable TOML). After
    # normalizing the framework-owned differences, existing and candidate
    # must describe the SAME document; anything else is operator content
    # the merge would silently drop or alter.
    if existing_doc is not None and (
        _codex_normalized_doc(existing_doc) != _codex_normalized_doc(candidate_doc)
    ):
        return fail_safe(
            "merged result would change operator-owned parsed content "
            "(valid-TOML content loss the parse check cannot flag) — "
            "refusing to write"
        )
    return candidate


def guru_available(repo_root: Path) -> bool:
    return (repo_root / GURU_ROLE_REL).is_file()


def upsert_marked_region(text: str, region: str) -> str:
    block = f"{MARKER_BEGIN}\n{region.rstrip()}\n{MARKER_END}"
    pattern = re.compile(
        re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END),
        re.DOTALL,
    )
    if pattern.search(text):
        return pattern.sub(block, text, count=1)
    return text.rstrip() + "\n\n" + block + "\n"


def insert_after_heading(text: str, heading: str, inner: str) -> str:
    """Insert marked block after the first line matching ``heading`` (markdown ## title)."""
    if MARKER_BEGIN in text:
        return upsert_marked_region(text, inner)
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines):
        if line.strip() == heading:
            insert_at = index + 1
            while insert_at < len(lines) and lines[insert_at].strip() == "":
                insert_at += 1
            marked = f"{MARKER_BEGIN}\n{inner}\n{MARKER_END}"
            new_lines = lines[:insert_at] + ["\n", marked, "\n"] + lines[insert_at:]
            return "".join(new_lines)
    marked = f"{MARKER_BEGIN}\n{inner}\n{MARKER_END}"
    return text.rstrip() + "\n\n" + marked + "\n"


def strip_legacy_auto_guru_section(text: str) -> str:
    """Remove unmarked ``## Code and documentation questions (auto-Guru)`` sections."""
    pattern = re.compile(
        r"\n## Code and documentation questions \(auto-Guru\)\n.*?(?=\n## |\n<!-- waveframework:|\Z)",
        re.DOTALL,
    )
    return pattern.sub("\n", text)


def strip_legacy_auto_guru_lines(text: str) -> str:
    """Remove hand-seeded auto-Guru bullets superseded by marker blocks."""
    pattern = re.compile(
        r"^\- Code and documentation Q&A:.*\n",
        re.MULTILINE,
    )
    if MARKER_BEGIN in text:
        parts = []
        in_marker = False
        for line in text.splitlines(keepends=True):
            if MARKER_BEGIN in line:
                in_marker = True
                parts.append(line)
                continue
            if MARKER_END in line:
                in_marker = False
                parts.append(line)
                continue
            if in_marker:
                parts.append(line)
                continue
            if line.strip().startswith("- Code and documentation Q&A:"):
                continue
            parts.append(line)
        return "".join(parts)
    return pattern.sub("", text)


def patch_thin_pointer(
    path: Path,
    inner: str,
    *,
    after_heading: str | None = None,
) -> bool:
    if not path.is_file():
        return False
    original = strip_legacy_auto_guru_section(
        strip_legacy_auto_guru_lines(path.read_text(encoding="utf-8"))
    )
    if after_heading:
        updated = insert_after_heading(original, after_heading, inner)
    else:
        updated = upsert_marked_region(original, inner)
    if updated != original:
        path.write_text(updated, encoding="utf-8")
        return True
    return False


def patch_root_bridge(path: Path) -> bool:
    """Ensure the root CLAUDE.md is a real ``@AGENTS.md`` import (1p5xc).

    Replaces the legacy prose pointer ("Thin pointer. Read `AGENTS.md` first…")
    with a marked ``@AGENTS.md`` import block so Claude loads AGENTS.md
    deterministically. Idempotent. This is the only ``@import`` the framework
    adopts and only at the root — never per-folder.
    """
    if not path.is_file():
        return False
    original = path.read_text(encoding="utf-8")
    text = original

    # Refresh an existing bridge block in place.
    bridge_re = re.compile(
        re.escape(ROOT_BRIDGE_MARKER_BEGIN) + r".*?" + re.escape(ROOT_BRIDGE_MARKER_END),
        re.DOTALL,
    )
    if bridge_re.search(text):
        text = bridge_re.sub(ROOT_BRIDGE_BLOCK, text, count=1)
        if text != original:
            path.write_text(text, encoding="utf-8")
            return True
        return False

    # Replace the legacy prose pointer if present; otherwise insert after the H1.
    if _LEGACY_THIN_POINTER_RE.search(text):
        text = _LEGACY_THIN_POINTER_RE.sub(ROOT_BRIDGE_BLOCK + "\n", text, count=1)
    else:
        lines = text.splitlines(keepends=True)
        insert_at = 0
        for index, line in enumerate(lines):
            if line.startswith("# "):
                insert_at = index + 1
                while insert_at < len(lines) and lines[insert_at].strip() == "":
                    insert_at += 1
                break
        block = ROOT_BRIDGE_BLOCK + "\n"
        new_lines = lines[:insert_at] + ["\n", block, "\n"] + lines[insert_at:]
        text = "".join(new_lines)

    if text != original:
        path.write_text(text, encoding="utf-8")
        return True
    return False


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # newline="" disables newline translation so the embedded line terminators are written
    # VERBATIM, byte-identical on every rendering host (mirrors render_platform_surfaces.write_text,
    # wave 1p7tz). With the default newline=None, a re-render on native Windows translates every
    # "\n" → os.linesep ("\r\n"), so the freshly generated agent surfaces (auto-guru.mdc, guru.md,
    # SKILL.md, config.toml) would gain CRLF and diff full-file on re-render. The source strings
    # already carry LF terminators, so newline="" is right for all hosts.
    with path.open("w", encoding="utf-8", newline="") as handle:
        handle.write(content)


def _carrier_protocol_block(carrier: ReviewProtocolCarrier) -> str:
    """Return the shared minimum plus any destination-specific obligations."""

    block = REVIEW_PROTOCOL_CARRIER_BLOCK
    if carrier.source_seed in {
        "221-code-reviewer.prompt.md",
        "239-qa-reviewer.prompt.md",
    }:
        block += "\n\n" + INDEPENDENT_REFERENCE_CARRIER_BLOCK
    if carrier.destination != "docs/agents/qa-reviewer.md":
        return block
    return block + "\n\n" + dedent(
        """\
        ### QA evidence integrity

        Required QA evidence must run with zero unintended skips, reach the
        named public path, use realistic boundary values, make non-vacuous
        assertions, and demonstrate detection of the known-bad behavior. A
        skipped, vacuous, impossible-shape, or wrong-reason failure is not
        approval evidence.
        """
    ).strip()


def _upsert_review_protocol_region(text: str, block: str) -> str | None:
    """Return text with the owned protocol block refreshed, or ``None`` on malformed markers."""

    begin_count = text.count(REVIEW_PROTOCOL_MARKER_BEGIN)
    end_count = text.count(REVIEW_PROTOCOL_MARKER_END)
    if begin_count != end_count or begin_count > 1:
        return None
    marked = (
        f"{REVIEW_PROTOCOL_MARKER_BEGIN}\n"
        f"{block}\n"
        f"{REVIEW_PROTOCOL_MARKER_END}"
    )
    if begin_count == 1:
        region = re.compile(
            r"^" + re.escape(REVIEW_PROTOCOL_MARKER_BEGIN) + r"[ \t\r]*\n.*?^"
            + re.escape(REVIEW_PROTOCOL_MARKER_END) + r"[ \t\r]*(?=\n|\Z)",
            re.MULTILINE | re.DOTALL,
        )
        if not region.search(text):
            return None
        return region.sub(marked, text, count=1)
    # Project-authored bytes are an exact prefix on first adoption. Do not use
    # rstrip(): trailing spaces and blank lines outside the owned region belong
    # to the project even when they look cosmetically redundant.
    separator = "" if not text or text.endswith("\n") else "\n"
    return text + separator + "\n" + marked + "\n"


def _initial_review_carrier_text(repo_root: Path, carrier: ReviewProtocolCarrier) -> str:
    """Return a usable canonical minimum for a missing enabled carrier.

    Most carrier seeds are themselves complete role/prompt bodies, so the
    public renderer can materialize them directly.  The two bootstrap-owner
    seeds (100 and 209) describe several outputs rather than one file; those
    destinations receive a small durable pointer instead of an unrelated full
    bootstrap document.  Later project-specific refreshes may extend either
    form outside the owned protocol region.
    """

    if carrier.destination == "docs/prompts/create-wave.prompt.md":
        return dedent(
            """\
            # Create Wave

            New waves must use `wave_create_wave` when MCP is available. The
            scaffold creates an empty sibling `events.jsonl`, declares
            `review-evidence-source: events.jsonl` in `wave.md`, renders the
            non-authoritative `## Finding Synthesis` current-state projection,
            and records the zero-record proof in
            `docs/waves/review-evidence-adoptions.json`.

            Never put canonical JSONL inside `wave.md`. Without MCP, create the
            sibling as an exactly empty file, reproduce this minimal Markdown
            declaration/projection, and run a public lifecycle tool as soon as
            available to persist the zero-record adoption proof:

            review-evidence-source: events.jsonl

            ## Finding Synthesis

            No review findings recorded.
            """
        )
    seed_path = repo_root / ".wavefoundry" / "framework" / "seeds" / carrier.source_seed
    if carrier.source_seed not in {
        "100-project-prompt-surface-bootstrap.prompt.md",
        "209-agent-harness-core.prompt.md",
    } and seed_path.is_file():
        return seed_path.read_text(encoding="utf-8")
    title = Path(carrier.destination).stem.replace(".prompt", "").replace("-", " ").title()
    return (
        f"# {title}\n\n"
        f"Canonical framework source: `.wavefoundry/framework/seeds/{carrier.source_seed}`.\n\n"
        "This minimum carrier was materialized by the public Wavefoundry "
        "setup/upgrade renderer. Project-specific guidance may be added "
        "outside the framework-owned region below.\n"
    )


_AGENT_ROLE_LINE_RE = re.compile(r"^Role:\s+", re.MULTILINE)
_AGENT_CATEGORY_LINE_RE = re.compile(r"^Category:\s+", re.MULTILINE)


def _ensure_agent_frontmatter(content: str, destination: str) -> str:
    """Inject the `Role:`/`Category:` frontmatter a fresh ``docs/agents/**`` carrier needs.

    The agent-metadata docs-lint validator requires every ``docs/agents/**/*.md`` to
    declare ``Role:`` (equal to the filename slug) and ``Category:`` (path-derived). A
    carrier materialized fresh from a seed body that omits those lines would fail the
    pack's own validator (the failure that blocked a 1.13.0 upgrade at the docs gate),
    so inject the missing field(s) here — **only when absent**, never overwriting a
    value the seed or an existing project-authored file already provides. Category is
    derived from the validator's own ``_expected_agent_category`` so the two never
    drift; a destination the validator exempts (category ``None``) gets nothing.
    Destinations the validator does not govern (e.g. ``docs/prompts/**``) are returned
    unchanged. Applied on the fresh-carrier path only, so the update path is untouched.
    """

    if not (destination.startswith("docs/agents/") and destination.endswith(".md")):
        return content
    # Local import: defer the wave_lint_lib edge to call time so module load stays
    # decoupled across the setup/upgrade/hook subprocess contexts that run rendering.
    from wave_lint_lib.wave_validators import _expected_agent_category

    dest = Path(destination)
    category = _expected_agent_category(dest)
    if category is None:
        return content
    needed: list[str] = []
    if not _AGENT_ROLE_LINE_RE.search(content):
        needed.append(f"Role: {dest.stem}")
    if not _AGENT_CATEGORY_LINE_RE.search(content):
        needed.append(f"Category: {category}")
    if not needed:
        return content
    block = "\n".join(needed)
    status_match = re.search(r"^Status:.*$", content, re.MULTILINE)
    if status_match:
        idx = status_match.end()
        return content[:idx] + "\n" + block + content[idx:]
    heading_match = re.search(r"^#\s.*$", content, re.MULTILINE)
    if heading_match:
        idx = heading_match.end()
        return content[:idx] + "\n\n" + block + content[idx:]
    return block + "\n\n" + content


def _contained_review_carrier_path(repo_root: Path, destination: str) -> Path:
    """Resolve one registered carrier and refuse writes outside ``repo_root``.

    Carrier destinations are fixed by the typed registry, but an existing
    repository can place a symlink at the destination or in one of its parent
    directories.  Setup, upgrade, and direct rendering must not follow that
    repository-controlled path into a sibling directory.  Returning the
    resolved path also prevents a later open from re-following the symlink
    chain that was checked here.
    """

    root = repo_root.resolve()
    candidate = repo_root / destination
    try:
        resolved = candidate.resolve(strict=False)
    except OSError as exc:
        raise RuntimeError(
            f"review carrier path cannot be resolved safely: {destination}: {exc}"
        ) from exc
    if not resolved.is_relative_to(root):
        raise RuntimeError(
            "review carrier path escapes the repository root through a symlink: "
            f"{destination}"
        )
    return resolved


def _write_review_carrier_text(path: Path, content: str) -> None:
    """Write a checked carrier without following a raced final symlink."""

    path.parent.mkdir(parents=True, exist_ok=True)
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    try:
        fd = os.open(path, flags, 0o666)
    except OSError as exc:
        raise RuntimeError(f"review carrier write refused for {path}: {exc}") from exc
    with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
        handle.write(content)


def _agent_surface_output_destinations(repo_root: Path) -> list[str]:
    """Return every non-registry agent destination this pass may write."""

    if not guru_available(repo_root):
        return []
    destinations = [
        ".codex/skills/auto-guru/SKILL.md",
        ".codex/config.toml",
    ]
    if (repo_root / ".cursor").exists():
        destinations.append(".cursor/rules/auto-guru.mdc")
    if (repo_root / ".claude").exists():
        destinations.append(".claude/agents/guru.md")
    for optional in (
        "CLAUDE.md",
        ".junie/guidelines.md",
        "WARP.md",
        ".github/copilot-instructions.md",
        ".cursor/rules/project-context.mdc",
    ):
        if (repo_root / optional).is_file():
            destinations.append(optional)
    return destinations


def preflight_agent_surface_paths(repo_root: Path) -> None:
    """Refuse every registered/native agent escape before the first write."""

    destinations = [
        *(carrier.destination for carrier in review_protocol_carriers(repo_root)),
        *_agent_surface_output_destinations(repo_root),
    ]
    for destination in dict.fromkeys(destinations):
        _contained_review_carrier_path(repo_root, destination)


def reconcile_review_protocol_surfaces(repo_root: Path) -> list[str]:
    """Reconcile framework-owned protocol regions without replacing project prose.

    The public setup/upgrade renderer materializes missing canonical minimums
    for enabled framework carriers and repairs their protocol section. Guru,
    repo-local reviewers, and native wrappers remain explicitly existing-only
    so rendering cannot silently enable optional capabilities. A malformed
    marker pair fails safe and leaves the file untouched with a loud diagnostic.
    """

    carriers = review_protocol_carriers(repo_root)
    preflight_agent_surface_paths(repo_root)
    written: list[str] = []
    for carrier in carriers:
        path = _contained_review_carrier_path(repo_root, carrier.destination)
        if not path.is_file():
            if carrier.conditional_existing or not carrier.create_if_missing:
                continue
            original = _initial_review_carrier_text(repo_root, carrier)
            # Fresh-only: guarantee a docs/agents/** carrier carries the Role:/Category:
            # frontmatter the pack's own docs-lint requires, even if the seed omits it.
            original = _ensure_agent_frontmatter(original, carrier.destination)
        else:
            with path.open("r", encoding="utf-8", newline="") as handle:
                original = handle.read()
        updated = _upsert_review_protocol_region(original, _carrier_protocol_block(carrier))
        if updated is None:
            print(
                "render_agent_surfaces: WARNING — left "
                f"{path} unchanged (malformed executable-review-evidence markers)",
                file=sys.stderr,
            )
            continue
        if updated != original:
            _write_review_carrier_text(path, updated)
            written.append(carrier.destination)
    return written


def render_agent_surfaces(repo_root: Path) -> list[str]:
    """Render auto-Guru tier 2–3 surfaces. Returns paths written or updated."""
    # Wave 1skt1: this must run before the historical Guru-availability early
    # return so setup/upgrade/render can repair review carriers in repositories
    # that intentionally do not expose Guru.
    preflight_agent_surface_paths(repo_root)
    review_written = reconcile_review_protocol_surfaces(repo_root)
    if not guru_available(repo_root):
        return review_written

    # Preflight every path this Guru-enabled pass may write before the first
    # native/thin-pointer mutation.  The initial carrier census intentionally
    # ignores a missing native wrapper, so a symlinked wrapper directory with
    # no leaf file would otherwise escape during materialization and be noticed
    # only by the second carrier reconciliation.
    preflight_agent_surface_paths(repo_root)

    written: list[str] = list(review_written)

    # Tier 3 — optional native surfaces
    if (repo_root / ".cursor").exists():
        cursor_rule = repo_root / ".cursor" / "rules" / "auto-guru.mdc"
        write_text(cursor_rule, CURSOR_AUTO_GURU_MDC)
        written.append(cursor_rule.relative_to(repo_root).as_posix())  # Wave 1p6dx: forward-slash

    if (repo_root / ".claude").exists():
        claude_agent = repo_root / ".claude" / "agents" / "guru.md"
        write_text(claude_agent, CLAUDE_GURU_AGENT)
        written.append(claude_agent.relative_to(repo_root).as_posix())  # Wave 1p6dx: forward-slash

    codex_skill = repo_root / ".codex" / "skills" / "auto-guru" / "SKILL.md"
    write_text(codex_skill, CODEX_AUTO_GURU_SKILL)
    written.append(codex_skill.relative_to(repo_root).as_posix())  # Wave 1p6dx: forward-slash

    # Wave 1p9pe (renderer-overwrite-safety): upsert the framework-managed
    # region only — never clobber operator-authored TOML (approval modes,
    # tool policy, other [mcp_servers.*] tables). Read with newline="" so
    # operator bytes round-trip verbatim (no universal-newline translation),
    # matching write_text's newline="" discipline (wave 1p7tz/1p9ix).
    codex_mcp_config = repo_root / ".codex" / "config.toml"
    existing_codex_config: str | None = None
    if codex_mcp_config.is_file():
        with codex_mcp_config.open("r", encoding="utf-8", newline="") as handle:
            existing_codex_config = handle.read()
    codex_fail_safe_reasons: list[str] = []
    merged_codex_config = upsert_codex_mcp_config(
        existing_codex_config, on_fail_safe=codex_fail_safe_reasons.append
    )
    if codex_fail_safe_reasons:
        # Review-fix: a fail-safe merge must be LOUD (name the file and the
        # reason) and must NOT report the path as written — the file was left
        # untouched and the framework region may be stale or missing.
        print(
            f"render_agent_surfaces: WARNING — left {codex_mcp_config} unchanged "
            f"(fail-safe: {codex_fail_safe_reasons[0]}); resolve the conflict "
            "manually so the framework MCP region can be upserted",
            file=sys.stderr,
        )
    else:
        write_text(codex_mcp_config, merged_codex_config)
        written.append(codex_mcp_config.relative_to(repo_root).as_posix())  # Wave 1p6dx: forward-slash

    # Root @import bridge — make CLAUDE.md a real @AGENTS.md import (1p5xc).
    # The single, contained @import; replaces the prose "read AGENTS.md first"
    # pointer so AGENTS.md is the deterministic single source of truth.
    if patch_root_bridge(repo_root / "CLAUDE.md"):
        written.append("CLAUDE.md")

    # Tier 2 — thin pointers (marker blocks)
    claude_path = repo_root / "CLAUDE.md"
    if claude_path.is_file():
        claude_body = CLAUDE_AUTO_GURU_SECTION.strip()
        claude_block = f"{MARKER_BEGIN}\n{claude_body}\n{MARKER_END}"
        text = strip_legacy_auto_guru_lines(claude_path.read_text(encoding="utf-8"))
        if MARKER_BEGIN in text:
            text = re.sub(
                re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END),
                claude_block,
                text,
                count=1,
                flags=re.DOTALL,
            )
        else:
            # Replace legacy hand-authored section if present
            legacy = re.compile(
                r"\n## Code and documentation questions \(auto-Guru\)\n.*?(?=\n## |\Z)",
                re.DOTALL,
            )
            if legacy.search(text):
                text = legacy.sub("\n" + claude_block + "\n", text, count=1)
            else:
                text = insert_after_heading(text, "## Startup Order", claude_block)
        if text != claude_path.read_text(encoding="utf-8"):
            claude_path.write_text(text, encoding="utf-8")
            written.append("CLAUDE.md")

    pointer_specs: list[tuple[Path, str]] = [
        (repo_root / ".junie" / "guidelines.md", "## Key Rules"),
        (repo_root / "WARP.md", "## Key Rules"),
        (repo_root / ".github" / "copilot-instructions.md", "## Key Guardrails"),
    ]
    for path, heading in pointer_specs:
        if patch_thin_pointer(path, AUTO_GURU_BULLET, after_heading=heading):
            written.append(path.relative_to(repo_root).as_posix())  # Wave 1p6dx: forward-slash

    cursor_ctx = repo_root / ".cursor" / "rules" / "project-context.mdc"
    if cursor_ctx.is_file():
        text = strip_legacy_auto_guru_section(
            strip_legacy_auto_guru_lines(cursor_ctx.read_text(encoding="utf-8"))
        )
        updated = upsert_marked_region(text, CURSOR_PROJECT_CONTEXT_BLOCK.strip())
        if updated != cursor_ctx.read_text(encoding="utf-8"):
            cursor_ctx.write_text(updated, encoding="utf-8")
            written.append(cursor_ctx.relative_to(repo_root).as_posix())  # Wave 1p6dx: forward-slash

    # Native Guru wrappers are materialized above, after the initial carrier
    # census. Reconcile again so the first public render gives them the same
    # protocol minimum and later renders cannot overwrite it away.
    for rel in reconcile_review_protocol_surfaces(repo_root):
        if rel not in written:
            written.append(rel)

    # Dedupe while preserving order (CLAUDE.md may be touched by both the
    # root-bridge step and the auto-Guru tier-2 step).
    deduped: list[str] = []
    for rel in written:
        if rel not in deduped:
            deduped.append(rel)
    return deduped


def main() -> int:
    import argparse
    import sys

    from render_platform_surfaces import discover_repo_root

    parser = argparse.ArgumentParser(description="Render auto-Guru agent routing surfaces.")
    parser.add_argument("--repo-root", default="", help="Repository root (default: auto-discover).")
    args = parser.parse_args()
    repo_root = Path(args.repo_root).resolve() if args.repo_root else discover_repo_root()
    try:
        paths = render_agent_surfaces(repo_root)
    except RuntimeError as exc:
        print(f"render_agent_surfaces: ERROR — {exc}", file=sys.stderr)
        return 1
    if not paths:
        if not guru_available(repo_root):
            print(f"skip: {GURU_ROLE_REL} not found", file=sys.stderr)
        return 0
    for rel in paths:
        print(rel)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
