#!/usr/bin/env python3
"""Run Wavefoundry framework unit tests without writing __pycache__ under scripts/.

Test cache
----------
After a successful run, the result is recorded in
``.wavefoundry/framework/test-cache.json`` (gitignored, excluded from the
distribution zip).  Subsequent invocations hash all test-relevant files under
the framework directory and compare to the stored hash.  If the hash matches
the last green run, the suite is skipped and the cached count is reported.

    python3 run_tests.py              # skip if nothing has changed
    python3 run_tests.py --no-cache   # force a full run regardless

The hash covers every file under ``.wavefoundry/framework/`` except packaging
artifacts (``VERSION``, ``MANIFEST``), the cache file itself, and the binary
index directory.  This includes all Python scripts, seed documents, dashboard
assets, and any test fixture files — anything that could change a test result.
"""

from __future__ import annotations

import datetime
import hashlib
import json
import sys
import unittest
from pathlib import Path

sys.dont_write_bytecode = True

_SCRIPT_DIR = Path(__file__).resolve().parent
_TESTS_DIR = _SCRIPT_DIR / "tests"
_FRAMEWORK_DIR = _SCRIPT_DIR.parent
_CACHE_FILE = _FRAMEWORK_DIR / "test-cache.json"

# Ensure scripts/ is on sys.path explicitly — tests/__init__.py handles this
# for individual-file runs; repeat it here so run_tests.py is self-contained
# and does not rely on Python's implicit entry-point path insertion.
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))


# Files and directories under _FRAMEWORK_DIR excluded from the cache hash.
# These are packaging artifacts, runtime state, or generated bytecode — changes
# to them do not affect test outcomes.
_HASH_EXCLUDE_NAMES = {"VERSION", "MANIFEST", "test-cache.json"}
_HASH_EXCLUDE_DIRS = {"index", "__pycache__", ".pytest_cache"}


def _hash_inputs() -> str:
    """Return a SHA-256 digest of all test-relevant files under the framework directory.

    Covers Python scripts, seed documents, dashboard assets, and any other
    fixture files that could change a test result.  Excludes packaging
    artifacts (VERSION, MANIFEST), the cache file itself, and the binary
    index directory.

    Both relative paths and file contents are hashed so renames, additions,
    deletions, and edits all produce a different digest.
    """
    h = hashlib.sha256()
    for path in sorted(_FRAMEWORK_DIR.rglob("*")):
        if path.is_dir():
            continue
        rel = path.relative_to(_FRAMEWORK_DIR)
        if rel.parts[0] in _HASH_EXCLUDE_DIRS:
            continue
        if rel.name in _HASH_EXCLUDE_NAMES:
            continue
        h.update(rel.as_posix().encode())
        h.update(path.read_bytes())
    return h.hexdigest()


def _read_cache() -> dict | None:
    """Read and parse the test cache file, returning None on any error."""
    try:
        return json.loads(_CACHE_FILE.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return None


def _write_cache(inputs_hash: str, test_count: int) -> None:
    """Write a successful test cache entry.  Silent on failure (non-fatal)."""
    data = {
        "inputs_hash": inputs_hash,
        "ran_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "test_count": test_count,
        "result": "ok",
    }
    try:
        _CACHE_FILE.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    except Exception:  # noqa: BLE001
        pass  # cache write failure is non-fatal


def _clean_pycache() -> None:
    """Remove all __pycache__ directories under the framework directory.

    Called immediately before running the test suite to ensure no stale
    bytecode affects test behaviour.  Silent on any I/O error.
    """
    import shutil
    for pycache in _FRAMEWORK_DIR.rglob("__pycache__"):
        if pycache.is_dir():
            try:
                shutil.rmtree(pycache)
            except Exception:  # noqa: BLE001
                pass


def _cache_hit(inputs_hash: str) -> dict | None:
    """Return the cached entry if its hash matches and the run was passing, else None."""
    cache = _read_cache()
    if cache is None:
        return None
    if cache.get("inputs_hash") == inputs_hash and cache.get("result") == "ok":
        return cache
    return None


def main() -> int:
    # Strip --no-cache before forwarding remaining args to unittest discover.
    no_cache = "--no-cache" in sys.argv
    discover_argv = [a for a in sys.argv[1:] if a != "--no-cache"]

    # Compute the hash once — before any test execution — so the cache entry
    # always reflects the state that caused the run, not post-run file changes.
    inputs_hash = _hash_inputs()

    if not no_cache:
        hit = _cache_hit(inputs_hash)
        if hit:
            ts = hit.get("ran_at", "")[:19].replace("T", " ")
            print(
                f"Tests current — {hit.get('test_count', '?')} passed"
                + (f" at {ts} UTC" if ts else "")
                + ". Run with --no-cache to force."
            )
            return 0

    # Remove stale bytecode before running so no cached .pyc can influence results.
    _clean_pycache()

    argv = [
        sys.argv[0],
        "discover",
        "-s",
        str(_TESTS_DIR),
        "-p",
        "test_*.py",
        "-v",
        *discover_argv,
    ]
    program = unittest.main(module=None, argv=argv, exit=False)
    assert program.result is not None

    if program.result.wasSuccessful():
        _write_cache(inputs_hash, program.result.testsRun)
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
