#!/usr/bin/env python3
"""Run Wavefoundry framework unit tests without writing __pycache__ under scripts/.

Test cache
----------
After a successful run, the result is recorded in
``.wavefoundry/framework/test-cache.json`` (gitignored, excluded from the
distribution zip).  Subsequent invocations hash all test-relevant files under
the framework directory and compare to the stored hash.  If the hash matches
the last green run, the suite is skipped and the cached count is reported.

    python3 run_tests.py              # skip if nothing has changed
    python3 run_tests.py --no-cache   # force a full run regardless

The hash covers every file under ``.wavefoundry/framework/`` except packaging
artifacts (``VERSION``, ``MANIFEST``), the cache file itself, and the binary
index directory.  This includes all Python scripts, seed documents, dashboard
assets, and any test fixture files — anything that could change a test result.

Parallel execution
------------------
Each test file runs in its own subprocess.  Up to 6 files run concurrently
(capped below cpu_count to leave headroom for subprocess-heavy test files).
Output is buffered and printed file-by-file after all workers finish so that
output lines are never interleaved.
"""

from __future__ import annotations

import concurrent.futures
import datetime
import hashlib
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

sys.dont_write_bytecode = True

# Suppress dashboard browser open for the entire test suite (see dashboard_lib).
os.environ.setdefault("WAVEFOUNDRY_SUPPRESS_DASHBOARD_BROWSER", "1")

_SCRIPT_DIR = Path(__file__).resolve().parent
_TESTS_DIR = _SCRIPT_DIR / "tests"
_FRAMEWORK_DIR = _SCRIPT_DIR.parent
_CACHE_FILE = _FRAMEWORK_DIR / "test-cache.json"
_LOCK_FILE = _FRAMEWORK_DIR / "test-run.lock"

# Wave 1p9j0: msvcrt.locking (native Windows) is mandatory byte-range, so the run lock is taken on
# a SENTINEL byte at this high fixed offset — NOT byte 0 — so the same-handle pid write/truncate at
# byte 0 below is not blocked, mirroring dashboard_lib.py's sentinel-offset rationale.
_LOCK_BYTE_OFFSET = 1 << 30  # 1 GiB — well beyond the short pid line written at byte 0

# Ensure scripts/ is on sys.path explicitly — tests/__init__.py handles this
# for individual-file runs; repeat it here so run_tests.py is self-contained
# and does not rely on Python's implicit entry-point path insertion.
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

import subprocess_util  # UTF-8 child env for worker spawns (wave 1p9j0)
import venv_bootstrap  # the single venv resolver (wave 1p7pl)

# Activate the shared tool venv IN-PROCESS before any heavy work (wave 1p7pl/1p802 AC-3): every
# direct-launch entry self-bootstraps so a bare `python run_tests.py` runs the suite with the venv
# packages. No-op when already in the venv or when it does not exist yet (fresh bootstrap).
venv_bootstrap.activate_tool_venv()


# Files and directories under _FRAMEWORK_DIR excluded from the cache hash.
# These are packaging artifacts, runtime state, or generated bytecode — changes
# to them do not affect test outcomes.
_HASH_EXCLUDE_NAMES = {"VERSION", "MANIFEST", "test-cache.json"}
_HASH_EXCLUDE_DIRS = {"index", "__pycache__", ".pytest_cache"}


def _hash_inputs() -> str:
    """Return a SHA-256 digest of all test-relevant files under the framework directory.

    Covers Python scripts, seed documents, dashboard assets, and any other
    fixture files that could change a test result.  Excludes packaging
    artifacts (VERSION, MANIFEST), the cache file itself, and the binary
    index directory.

    Both relative paths and file contents are hashed so renames, additions,
    deletions, and edits all produce a different digest.
    """
    h = hashlib.sha256()
    for path in sorted(_FRAMEWORK_DIR.rglob("*")):
        if path.is_dir():
            continue
        rel = path.relative_to(_FRAMEWORK_DIR)
        if rel.parts[0] in _HASH_EXCLUDE_DIRS:
            continue
        if rel.name in _HASH_EXCLUDE_NAMES:
            continue
        h.update(rel.as_posix().encode())
        h.update(path.read_bytes())
    return h.hexdigest()


def _read_cache() -> dict | None:
    """Read and parse the test cache file, returning None on any error."""
    try:
        return json.loads(_CACHE_FILE.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return None


def _write_cache(inputs_hash: str, test_count: int) -> None:
    """Write a successful test cache entry.  Silent on failure (non-fatal)."""
    data = {
        "inputs_hash": inputs_hash,
        "ran_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "test_count": test_count,
        "result": "ok",
    }
    try:
        _CACHE_FILE.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    except Exception:  # noqa: BLE001
        pass  # cache write failure is non-fatal


def _clean_pycache() -> None:
    """Remove all __pycache__ directories under the framework directory.

    Called immediately before running the test suite to ensure no stale
    bytecode affects test behaviour.  Silent on any I/O error.
    """
    import shutil
    for pycache in _FRAMEWORK_DIR.rglob("__pycache__"):
        if pycache.is_dir():
            try:
                shutil.rmtree(pycache)
            except Exception:  # noqa: BLE001
                pass


def _cache_hit(inputs_hash: str) -> dict | None:
    """Return the cached entry if its hash matches and the run was passing, else None."""
    cache = _read_cache()
    if cache is None:
        return None
    if cache.get("inputs_hash") == inputs_hash and cache.get("result") == "ok":
        return cache
    return None


def _test_runner_python() -> str:
    """Return the Python executable used for per-file test workers.

    Builds the path via the single resolver (wave 1p7pl); semantics unchanged
    (venv Python when it exists, else the current interpreter).
    """
    venv_python = venv_bootstrap.tool_venv_python()
    return str(venv_python if venv_python.exists() else Path(sys.executable))


def _acquire_run_lock():
    """Acquire the runner lock or return (None, diagnostic) when already held.

    Wave 1p9j0: branch on ``os.name`` so the runner imports and runs on native Windows —
    ``fcntl`` does not exist there. Mirrors dashboard_lib.py's fcntl/msvcrt split: POSIX uses
    ``fcntl.flock``; Windows uses ``msvcrt.locking`` on a SENTINEL byte (``_LOCK_BYTE_OFFSET``)
    so the same-handle pid write/truncate at byte 0 below is not blocked. POSIX mutual-exclusion
    ("already running" busy diagnostic) is preserved unchanged.
    """
    try:
        lock_file = _LOCK_FILE.open("a+", encoding="utf-8")
    except Exception as exc:  # noqa: BLE001
        return None, f"Could not open test runner lock file {_LOCK_FILE}: {exc}"

    busy_msg = f"Another run_tests.py invocation is already running; lock file busy: {_LOCK_FILE}"
    try:
        if os.name == "nt":
            import msvcrt
            lock_file.seek(_LOCK_BYTE_OFFSET)
            try:
                msvcrt.locking(lock_file.fileno(), msvcrt.LK_NBLCK, 1)
            except OSError:
                lock_file.close()
                return None, busy_msg
        else:
            import fcntl
            try:
                fcntl.flock(lock_file, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError:
                lock_file.close()
                return None, busy_msg
    except Exception as exc:  # noqa: BLE001
        lock_file.close()
        return None, f"Could not acquire test runner lock: {exc}"

    try:
        lock_file.seek(0)
        lock_file.truncate()
        lock_file.write(f"{os.getpid()}\n")
        lock_file.flush()
    except Exception:  # noqa: BLE001
        pass

    return lock_file, None


def _release_run_lock(lock_file) -> None:
    """Release the runner lock and close the underlying file handle."""
    try:
        if os.name == "nt":
            import msvcrt
            lock_file.seek(_LOCK_BYTE_OFFSET)  # unlock the SAME sentinel byte we locked
            msvcrt.locking(lock_file.fileno(), msvcrt.LK_UNLCK, 1)
        else:
            import fcntl
            fcntl.flock(lock_file, fcntl.LOCK_UN)
    except Exception:  # noqa: BLE001
        pass
    try:
        lock_file.close()
    except Exception:  # noqa: BLE001
        pass


def _run_file(file_path: Path) -> tuple[str, int, str, int]:
    """Run one test file in a subprocess.

    Returns (filename, returncode, combined_output, test_count).
    unittest writes its verbose output to stderr; stdout carries any print()
    calls made by tests themselves.  Both are captured and merged.
    A 600 s per-file timeout prevents a hung test from blocking the whole run;
    timeout is surfaced as a failure rather than propagating.
    """
    env = os.environ.copy()
    env["WAVEFOUNDRY_SUPPRESS_DASHBOARD_BROWSER"] = "1"
    # Wave 1p52p: the test suite is hardware-INDEPENDENT (CI has no GPU, so it must pass on CPU).
    # Force the CPU provider so tests never build/run the real CoreML/CUDA embedder OR cross-encoder
    # reranker — that downloads models, pays the ~20s CoreML compile per process, runs ~0.8s/rerank
    # across the many code_ask integration tests, and (with 6 files in parallel) widens the
    # onnx/protobuf+CoreML abort surface. The GPU accel paths are unit-tested via mocks
    # (make_embedder/make_reranker dispatch); real-GPU parity is an operator-side validation.
    # A test that specifically needs a GPU provider can override this in its own env.
    env.setdefault("WAVEFOUNDRY_EMBED_PROVIDER", "cpu")
    # Wave 1p52p (CPU reranker fallback): with the CPU INT8 reranker, `EMBED_PROVIDER=cpu` would now
    # build a REAL CPU reranker in the integration tests (~960 ms/query → slow suite). The dedicated
    # disable flag turns reranking off entirely for the suite — fast + deterministic. Tests that
    # exercise the reranker mock `_get_reranker`/`make_reranker` directly.
    env.setdefault("WAVEFOUNDRY_DISABLE_RERANKER", "1")
    # Wave 1p9j0 (F13): force UTF-8 in the worker so its output is emitted as UTF-8 regardless of
    # the host locale (native Windows defaults to cp1252), and decode the captured text as UTF-8
    # with an error-tolerant policy — consistent with the timeout branch's replace-decode below.
    # utf8_child_env sets PYTHONUTF8=1 AND PYTHONIOENCODING=utf-8: an inherited
    # PYTHONIOENCODING=cp1252 would otherwise win over PYTHONUTF8 in the child.
    env = subprocess_util.utf8_child_env(env)
    try:
        result = subprocess.run(
            [_test_runner_python(), "-B", "-m", "unittest", "discover",
             "-s", str(_TESTS_DIR), "-p", file_path.name, "-v"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            cwd=str(_SCRIPT_DIR),
            env=env,
            timeout=600,
        )
        output = (result.stdout + result.stderr) if result.stdout else result.stderr
        rc = result.returncode
    except subprocess.TimeoutExpired as exc:
        out = exc.stdout.decode(errors="replace") if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        err = exc.stderr.decode(errors="replace") if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        output = (out + err if out else err) + f"\nTIMEOUT: {file_path.name} exceeded 600 s per-file limit.\n"
        rc = 1
    m = re.search(r"Ran (\d+) tests?", output)
    count = int(m.group(1)) if m else 0
    return file_path.name, rc, output, count


def main() -> int:
    no_cache = "--no-cache" in sys.argv

    # Compute the hash once — before any test execution — so the cache entry
    # always reflects the state that caused the run, not post-run file changes.
    inputs_hash = _hash_inputs()

    if not no_cache:
        hit = _cache_hit(inputs_hash)
        if hit:
            ts = hit.get("ran_at", "")[:19].replace("T", " ")
            print(
                f"Tests current — {hit.get('test_count', '?')} passed"
                + (f" at {ts} UTC" if ts else "")
                + ". Run with --no-cache to force."
            )
            return 0

    lock_file, lock_error = _acquire_run_lock()
    if lock_error is not None:
        print(lock_error, file=sys.stderr)
        return 1

    try:
        # Remove stale bytecode before spawning workers.
        _clean_pycache()

        test_files = sorted(_TESTS_DIR.glob("test_*.py"))
        # Cap at 6: many test files spawn subprocesses; beyond 6 concurrent workers
        # the system gets CPU/IO-saturated and individual file times balloon.
        workers = min(len(test_files), min(os.cpu_count() or 4, 6))

        wall_start = time.monotonic()
        file_results: list[tuple[str, int, str, int]] = []

        print(f"Running {len(test_files)} test files across {workers} workers …", flush=True)

        with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
            futures = {executor.submit(_run_file, f): f for f in test_files}
            done_count = 0
            for future in concurrent.futures.as_completed(futures):
                result = future.result()
                name, rc, _output, count = result
                done_count += 1
                status = "ok" if rc == 0 else "FAIL"
                print(f"  [{done_count}/{len(test_files)}] {name} — {count} tests {status}", flush=True)
                file_results.append(result)

        wall_elapsed = time.monotonic() - wall_start

        # Print each file's full output in stable filename order.
        file_results.sort(key=lambda r: r[0])
        failed_files: list[str] = []
        total_tests = 0

        for name, rc, output, count in file_results:
            total_tests += count
            if rc != 0:
                failed_files.append(name)
                print(f"\n{'=' * 70}")
                print(f"FAILED: {name}")
                print("=" * 70)
                print(output, end="")

        print(f"\n{'-' * 70}")
        if failed_files:
            print(f"FAILED ({', '.join(failed_files)})")
            print(f"Ran {total_tests} tests across {len(test_files)} files in {wall_elapsed:.3f}s")
            _clean_pycache()
            return 1

        print(f"Ran {total_tests} tests across {len(test_files)} files in {wall_elapsed:.3f}s")
        print("OK")
        _clean_pycache()
        _write_cache(inputs_hash, total_tests)
        return 0
    finally:
        _release_run_lock(lock_file)


if __name__ == "__main__":
    raise SystemExit(main())
